### ISSUE TITLE
Add links to info about views on the course view page

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1000]
## Describe your problem or feature you'd like added
On the course view tiles, add a link to more information about the view.  This will help instructors learn more about a view when they are considering whether to turn it on or not.

## Describe the solution you'd like
On each visualization tile for a course, add an information icon that links to the online help for that page view.

**Comment by jennlove-um** [comment]
Links to help:

Resources Accessed: https://its.umich.edu/academics-research/teaching-learning/my-learning-analytics/support/resources-accessed

Assignment Planning: https://its.umich.edu/academics-research/teaching-learning/my-learning-analytics/support/assignment-planning

Grade Distribution: https://its.umich.edu/academics-research/teaching-learning/my-learning-analytics/support/grade-distribution

**Comment by chrisrrowland** [comment]
@jennlove-um As this is to help instructors learn more about the course, is the link supposed to only appear when the user is an instructor?  An instructor or admin?  Anyone?

**Comment by jennlove-um** [comment]
The information in the links is generic.  While the initial reason for adding it was for instructors, there's no reason not to provide the link for anyone who wants to know more about the view.  Go ahead and have the link display for all user types.

**Comment by chrisrrowland** [comment]
Any issues with adding it like this?  It will be visible for everyone.

![image](https://user-images.githubusercontent.com/17617998/89674217-cab8a480-d8b5-11ea-9256-d967d16f17dc.png)

**Comment by jennlove-um** [comment]
I like it!

**Comment by jennlove-um** [comment]
testing passes.  info links work for the 3 views being used this fall
