### ISSUE TITLE
Investigate redundant css imports

### ISSUE THREAD

**Issue by chrisrrowland** [tl-its-umich-edu/my-learning-analytics#1001]
## Expected behavior (A clear and concise description of what you expected to happen) : 
Minimal required imports
## Describe the bug (Tell us what happens instead of the expected behavior) :
I think there is unnecessary redundancy in the imports in [base.html](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/8d11c1f8dfdfaaa0ad3fa042857f9fd2986a01a6/dashboard/templates/base.html#L16-L18)

By name alone I'd figure all.css contains, all fontawesome styles, while fontawesome.min.css and fontawesome.css are functionally identical, and would both be included in all.

Could be a non issue but creating this issue so it's not forgotten.

**Comment by chrisrrowland** [comment]
I replaced all.css with all.min.css and removed the other 2 imports and it resulted in a reduction of 213.4 KB and a quick look around  I didn't notice anything looking different, but I have only been looking at myla for a short time.  The test instance was down at the moment so I couldn't do a side by side comparison.

**Comment by jennlove-um** [comment]
Closing this issue as complete.
