### ISSUE TITLE
Upgrade to Django 3.1 and add two cookie middleware

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1005]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added

When it's convenient we should upgrade to Django 3.1. Django 3.1 adds new features as well as built in SameSite middleware.

Currently we are [using a custom Middleware](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/dashboard/middleware/samesite.py) that will need to be removed as it has no affect over version 3.1. However there is a problem with Safari in that it still doesn't work with SameSite=None, so I believe we'll need a two cookie Middleware.

Currently when testing Safari it says
`“Your browser prohibits to save cookies in the iframes. Click here to open content in the new tab.”`

This message is from the PyLTI 1.3 library and at least it allows it to work. 

* Update requirements to Django 3.1
* Remove this samesite.py middleware
* Add the [two cookie middleware](https://gist.github.com/acu192/315d27f8fe9ff58638c3571c91c4d1ca) for Safari and backward compatibility
* Add support for the CSRF_COOKIE_SAMESITE to this two cookie middleware

**Comment by jonespm** [comment]
This will also increase the user first_name field to be longer, an issue that recently occurred for MWrite.

**Comment by jennlove-um** [comment]
This should have been taken care of with the upgrade to Django 3.1 and added support for the CSRF_COOKIE_SAMESITE to this two cookie middleware.  

@jonespm Is there anything else we need to do, or is this done?

**Comment by jonespm** [comment]
It looks like this was mostly fixed in #1261. I haven't heard of any issues around this yet. We'll have to change this eventually to a better method for LTI launch but that's still in draft. I think this can be closed.
