### ISSUE TITLE
Come up with a flow for experimental view like Assignment redesign view for display 

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#1007]
The approach we have manually disabled the assignment redesign view. Course view option will enable all the view by defaults. It will be confusing for instructor if we give then the options to chose and if they chose both then it will be confusing for students. For Fall we are giving the option in hands of instructor so manual approach won't work

If we introduce certain experimental views like assignment redesign,  Discussion, Modules into MyLA and still in usability test how do these view be shown to instructors vs admins 

Also have UI indication that the view is a global disabled

**Comment by pushyamig** [comment]
@jennlove-um Thoughts???

**Comment by jennlove-um** [comment]
For these experimental views, it would be better for the instructor never to see them.  Could we find some way to allow only MyLA admins to turn on those views?

**Comment by pushyamig** [comment]
Here is an idea....
We can have a different DB table that defines which view are experimental, Admin can probably chose which view is experimental going via Django admin
experimental_course_view
view          | state_experimental
-----------------------------------------
assignment_v1 | False
Assignment_v2 | True
Grades        | False
Resources     | True
Modules       | False

Course view option by default enabled all the views when a course is created. 

But when sending (VIA API CAll) course details to Frontend for display.. We could only as this

Instructor:
`{ra: 1, ga: 1, ap: 1}`

Admins
`{ra: 1, ga:1, ap:1, apv2: 1, md: 1}`

Thoughts???

**Comment by jennlove-um** [comment]
This seems like a reasonable approach.

**Comment by jennlove-um** [comment]
This can be closed.
