### ISSUE TITLE
Support the become user and course link features for LTI 1.3 from Tool

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#1009]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 
Currently with LTI 1.3 become user feature and using course link for navigating to a particular course are not working. As LTI 1.3 broke then to in support from canvas itself

## Steps to Reproduce :
1. Launch to MyLA via LTI and make sure you have the is_staff role enabled in `auth_user` table
2. If you have is_staff roles enabled you should be able to launch the admin view
3. Go to course and click on the link for a particular course, it will be blank
4. logging in as user will be broken as well

**Comment by pushyamig** [comment]
If you try to become user from Myla and if that user is in 2 courses in MyLA DB when becoming user admin will see 2 courses showing up on the `/courses` route. This is happening because become user redirect it to / path and at that point it i don't have course info like /course/12233. This is just for admin student and instructors won't see this behavior since they will always launch the tool from the Canvas

Become User feature recommended to use of validating data with views.

**Comment by jennlove-um** [comment]
testing passes.  as an admin, I can view other courses and become user.
