### ISSUE TITLE
event data is lost for new students

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/my-learning-analytics#1012]
## Expected behavior:

Students' complete event data should be loaded.

## Describe the bug:

If a student is added to a course and begins using resources (e.g., viewing MiVideo or LC media) shortly thereafter, events of those usages will not be included in the `resource_access` table.

## Steps to reproduce :

1. Add student **_A_** to active Canvas course  (I.e., "active" in the sense that the course is in progress, students have used its resources, and their usage is visible in MyLA.)
1. Student **_A_** uses course resources immediately; other course students continue using resources, too
1. MyLA is updated with course students' usages via cron job, which doesn't include usage by student **_A_**, because they are not on the course roster in UDW
1. Wait 𝒏 hours (24 or more?) for UDW to show student **_A_** in course roster
1. Again, MyLA is updated with course students' usages via cron job, this time student **_A_** is included, but only their usage since the last time MyLA was updated is included (I.e., their activity between the time they were added to Canvas and the time MyLA could find them in UDW is not recorded in MyLA's DB.)

## Additional context:

This bug is caused by a difference between the time users are added to a Canvas course and the time that course's user data is updated in the Unizin Data Warehouse (UDW).  The greater the delay in updating the course roster in UDW, the more likely events will be lost.  The current delay appears to be more than 24 hours.

**Comment by lsloan** [comment]
This may be a duplicate of #1006.

**Comment by jennlove-um** [comment]
Assigned to me for testing with the latest release.

**Comment by jennlove-um** [comment]
This can be closed.  It was fixed with #1006.
