### ISSUE TITLE
Allow instructors to see a preview of the views before enabling them for students

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1013]
## Describe your problem or feature you'd like added
Instructors should be able to see a preview of each visualization for their course before enabling the view for students.  This will allow them to make informed decisions about whether to turn a view on for students.

## Describe the solution you'd like
On the course views page, allow instructors to view a visualization even when it is disabled for students. When they are on the individual view, provide a banner or other visual marker that indicates this view is not enabled for students.  Text: "Preview Mode: This view is currently disabled for students."

**Comment by chrisrrowland** [comment]
Is this good or should it use a different color?  This is using the existing AlertBanner component.

![image](https://user-images.githubusercontent.com/17617998/90033272-46876800-dc8d-11ea-904e-9e0e7af4a8cb.png)

**Comment by jennlove-um** [comment]
The blue makes sense to me. Thanks!! This looks good!

**Comment by jennlove-um** [comment]
This works.  As an instructor, I can see the views for the course.  When I enable a view, students can also see the view.  When a view is disabled, I can see it as an instructor, but the students cannot.
