### ISSUE TITLE
Clicking in the title area of a SelectCard but not on text does not act as a link to the view

### ISSUE THREAD

**Issue by chrisrrowland** [tl-its-umich-edu/my-learning-analytics#1015]
## Expected behavior (A clear and concise description of what you expected to happen) : 
The whole area should be a link

## Describe the bug (Tell us what happens instead of the expected behavior) :
The whole area is not a link

## Steps to Reproduce :
1.  Place mouse over title area.  Ensure pointer is not on view title.
2. Click.
3. Profit

**Comment by jennlove-um** [comment]
testing passes for all 4 title view cards
