### ISSUE TITLE
Support global disable of course views for course members

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#1019]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 
We have assignment redesign, which is still an experimental feature and is currently shown to all. That feature is will be confusing if enabled for Fall. There is a existing support of property "VIEWS_DISABLED" that disables at global level

When the Prop is set as `"VIEWS_DISABLED":["show_assignment_planning"] make the course view option as this {"ap": 0, "apv1": 1, "gd": 1, "ra": 1}

Instructor course view options flow will show all the view assuming it has be disabled earlier since the option will be show as say ap = 0

To deal with this scenario the better approach will be to send it like this `{"apv1": 1, "gd": 1, "ra": 1}` i.e remove the `ap` option

For admin it should show all the view including global disable i.e send it like this {"ap": 0, "apv1": 1, "gd": 1, "ra": 1} and admins can toggle the view

If global disable is not set it should display all the course view options

A long term solution is doing all this with DB and is tackled as separate issue here #1007 

## Steps to Reproduce :
1. In the env.json set `"VIEWS_DISABLED": ["show_assignment_planning"]`,
2. log in as instructor, the view will still show assignment redesign as disable option
3.

**Comment by jennlove-um** [comment]
There seems to be a disconnect between the UI and Django admin for this one.  

UI: As an admin, I see the new assignment planning, and I can click to enable/disable it.  This is working as expected.
Django admin: The new assignment planning is not available at all as an option. Enabling it or disabling it through the UI has no effect.  I also can't enable or disable it via Django admin.

**Comment by pushyamig** [comment]
I think we discussed on this before and it was said it was ok to not show it in the Django admin/

**Comment by jennlove-um** [comment]
This is ok for this release.  I'll create a new issue to to address providing a way for admins to enable/disable hidden views like the new assignment planning.

Testing passes
