### ISSUE TITLE
Enable mypy type hinting for VScode

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1022]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added
As we're starting to use type hints, we should minimally enable the mypy type hinting checker for VSCode. Otherwise any errors might not be noticed.

**Comment by jonespm** [comment]
To test this a developer will need to open up a file with type hinting and they should either see errors or no errors.

**Comment by pushyamig** [comment]
I am Qa'ing this issue and I don't see any error being reported in VSCode when opened `views.py`. This file don't have much type hinting to it. Am I missing something?

**Comment by pushyamig** [comment]
Test passes
