### ISSUE TITLE
ETL incompatible with old queries

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1025]
## Expected behavior (A clear and concise description of what you expected to happen) : 
Existing queries should continue to work after #826 change.

## Describe the bug (Tell us what happens instead of the expected behavior) :

This exception is thrown now when using existing queries without the user_login_name column.
```
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5018, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['user_login_name'] not found in axis"
```

It looks like we *could* just add errors="ignore" to this statement to keep it going. I'm thinking it might be better to do a try/except instead here to log a message to the user that they may want to look at updating to use the new query format (if necessary).

```
                resource_access_df = resource_access_df.drop(
                    columns='user_login_name', errors="ignore")
```

**Comment by jonespm** [comment]
I don't know, maybe we should just add the errors="ignore". . . I can't think of a good log message.

**Comment by zqian** [comment]
the "user_login_name" column has been added into config/env_sample.json file. Maybe the only change needed is the env.json update?

**Comment by zqian** [comment]
How about making this as a subtask in [issue_826](https://github.com/tl-its-umich-edu/my-learning-analytics/issues/826)?

**Comment by jonespm** [comment]
Well I figured it would be nice if the previous configuration worked without people having to change their configuration. Unless you're adding the Kaltura query or another that has user login names instead of canvas ids you shouldn't need to do anything. 

This isn't so much for us as Unizin schools. It's an easy fix to get it working.

**Comment by lsloan** [comment]
Why can't deployment of this change include a requirement to update the config file?

**Comment by lsloan** [comment]
Updating the queries in the config file before deploying the updated application should be safe.  The additional columns returned by the queries shouldn't affect the code.

On the other hand, if it were necessary to handle this in the code, then I'd add a check for the presence of the `user_login_name` column in the results.  If it's there, do the special handling, if not, give a warning about the missing column.

**Comment by jonespm** [comment]
We kind of already do what you're describing [here](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/6a4dc145c9f8818eabd6fb1a75e885c84e709bd5/dashboard/cron.py#L311), just checking on if there `user_id`'s instead of if there's `user_login_name`

I just like to keep things backward compatible unless it's not easily possible to do so and this is easy. 

We can and should include this in the release notes but I believe the majority of people don't read the release notes and we haven't even written anything documenting this change yet. It's not obvious from the logs when this fails why it's failing.

**Comment by lsloan** [comment]
OK.  I'll add a check for the column.  It will either use it or issue a warning.

Would warning via `logger.warning()` be appropriate?

**Comment by jonespm** [comment]
Yeah, sounds great!
