### ISSUE TITLE
Improve configuration of resource (BigQuery queries)

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1039]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added
I believe that if we defined our queries with JSON instead of a Raw SQL it would make the configuration more flexible and easier to add new entries in the future. It would also make it more clear which columns are needed.

## Describe the solution you'd like

Here's my idea, have a JSON with columns (and their names) with the SQL that will pull each column from the event_store

Then have a LIST of where clauses to drill down to that column. That *should* be all we need.

Then in the code it will generate the SQL queries from this data.

```
{
  "canvas": {
    "columns": {
      "resource_id": "SUBSTR(JSON_EXTRACT_SCALAR(event, '$.object.id'), 35))",
      "user_id" : "SUBSTR(JSON_EXTRACT_SCALAR(event, '$.membership.member.id')",
      "course_id" : "(SUBSTR(JSON_EXTRACT_SCALAR(event, '$.group.id'), 31)"
      },
    "table": "event_store.events",
    "where": [
      "JSON_EXTRACT_SCALAR(event, '$.edApp.id') IN UNNEST(['http://m.canvas.umich.edu/' , 'http://umich.instructure.com/' ])",
      "type = 'NavigationEvent'"
      ]
  }
}
```

**Comment by jennlove-um** [comment]
How does the new expanded table available in the UDP, how does this affect this issue?  Does #1246 replace this issue?

**Comment by jennlove-um** [comment]
This was a useful idea, but we have not had anyone report problems defining the BigQuery queries.  Closing this issue.
