### ISSUE TITLE
Provide a clearer error message when instructor tries to view MyLA using Canvas's Student View

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1043]
## Describe your problem or feature you'd like added
MyLA does not support the Canvas Student View as an LTI.  Currently, when an instructor uses the Student View and then clicks on My Learning Analytics, they get a white screen with the error message {"lti_error": "Launch failed due to 'email'"}.

This will be confusing for instructors.

## Describe the solution you'd like
Provide a clearer error message: "Student view is not available for My Learning Analytics."

**Comment by pushyamig** [comment]
Can the message be in this format {"lti_error": "Student view is not available for My Learning Analytics."}? or with out the JSON string with lti_error

This error occurs during the LTI launch so we have a pattern designed like that

**Comment by pushyamig** [comment]
This is before the Frontend code load so it won't be pretty since React isn't loaded yet

**Comment by jennlove-um** [comment]
Yes, I think that pattern would be fine.  The important part is that text letting them know that student view is not available.  If it's  possible to do it without the JSON string, that would be even clearer for instructors, but if not, it's okay.

**Comment by jennlove-um** [comment]
Testing passes - error message has been changed.
