### ISSUE TITLE
Update in-tool link to use new MyLA logo

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1048]
A new logo has been designed for MyLA.  Replace the current image with this one for the in-tool links in MyLA.

![Logo - MyLA (My Learning Analytics Underneath)](https://user-images.githubusercontent.com/39634416/91185248-9289d200-e6bb-11ea-86e2-d8262758168b.png)

I also have a .svg version of the image, if that is preferable.

**Comment by pushyamig** [comment]
can you provide me with the svg version of the image?

**Comment by jennlove-um** [comment]
testing passes
