### ISSUE TITLE
The logout link in the profile menu should be removed for the LTI

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1053]
The logout link does not make sense for the LTI.  It doesn't necessarily break anything if a user logs out but it looks wrong.  They can easily access MyLA again by launching the LTI.

## Steps to Reproduce :
1. Launch MyLA
2.Under the profile menu, click Logout
3.User is logged out & Django login screen displays

## Screenshots/Video (If possible, add media to help explain your problem) :
![image](https://user-images.githubusercontent.com/39634416/91227967-6ee37d80-e6f5-11ea-8395-ed6605a60be8.png)

**Comment by jennlove-um** [comment]
This may be related to #1060

**Comment by ssciolla** [comment]
@zqian, why was this issue closed? I think we still need to disable the "Log out" option for the Avatar dropdown, right?

**Comment by jennlove-um** [comment]
This is a duplicate of #1079
