### ISSUE TITLE
add support for LTI config by URL

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/my-learning-analytics#1054]
Besides "manual entry" and "paste JSON" methods, LTI configuration can be done via "enter URL".  That method takes a "JSON URL", from which presumably the JSON used in the "paste JSON" method can be retrieved from a service.

Add a new entry to the MyLA API that can be used to generate the JSON.  Give the URL of that API entry to the LMS configuration to let it load the JSON itself.

Bonus points for:

* Including the template for the config JSON in the `env.json` file
* Include code to auto-generate the various key files needed

The goal is to greatly reduce the number of steps required to configure the tool while keeping it safe and secure.

### Test main feature
1. Go to Canvas' LTI Developer Key creation page:
    * https://umich.instructure.com/accounts/1/developer_keys#lti_key_modal_opened
1. In the "Method" menu, select the "Enter URL" item.
1. Copy the following URL and paste it into the "JSON URL" field:
    * https://nnnnnnnnnnnn.ngrok.io/lti/config/
    * Replace "nnnnnnnnnnnn" with the ID number of your ngrok server.
1. Copy the following URL and paste it into the "Redirect URIs" field:
    * https://nnnnnnnnnnnn.ngrok.io/lti/launch/
    * Replace "nnnnnnnnnnnn" with the ID number of your ngrok server.
1. (Optional, recommended) Enter meaningful values into the "Key Name", "Owner Email", and "Notes" fields.
1. Click the "Save" button.

### Test `LTI_CONFIG_TEMPLATE_PATH` property in `env.json`
1. Copy `assets/config/lti_config_template.json` from the project directory to the `/secrets` directory on the Docker machine (i.e., `/secrets/lti_config_template.json`).
1. Make some changes to `/secrets/lti_config_template.json`. (E.g., change the `title` or `description`, remove some values from `scopes`, etc.)
1. Change or add the `LTI_CONFIG_TEMPLATE_PATH` property to the `env.json` that will be used by the Docker machine.  It should look something like:
    * `"LTI_CONFIG_TEMPLATE_PATH": "/secrets/lti_config_template.json",`
1. Stop and restart the Docker machine to get MyLA running with the just-edited `env.json`.
1. In a web browser, request the config.  If using ngrok, the URL will be something like:
    * https://nnnnnnnnnnnn.ngrok.io/lti/config/
    * Replace "nnnnnnnnnnnn" with the ID number of your ngrok server.
1. Verify that the configuration JSON received corresponds to that in the file you edited.
1. With the Docker machine running, rename the file `/secrets/lti_config_template.json` to something else.  (E.g., `/secrets/lti_config_template-FUBAR.json`.)
1. Again, in a web browser, request the config.  If using ngrok, the URL will be something like:
    * https://nnnnnnnnnnnn.ngrok.io/lti/config/
    * Replace "nnnnnnnnnnnn" with the ID number of your ngrok server.
1. Verify that you receive error messages similar to the following:
    * In the web browser: `{"lti_error": "Error reading LTI template file \"/secrets/lti_config_template.json\": ([Errno 2] No such file or directory: '/secrets/lti_config_template.json')"}` (This should also have an HTTP status code of 500.  The status may not be easy to find in all browsers.  It may be useful to use `curl`, like `curl -i https://nnnnnnnnnnnn.ngrok.io/lti/config/`.)
    * In the Docker console output: `student_dashboard  | [2020-10-23 16:20:27 -0400] [ERROR] [lti_new.py:39] LTI error: Error reading LTI template file "/secrets/lti_config_template.json": ([Errno 2] No such file or directory: '/secrets/lti_config_template.json')`

**Comment by jonespm** [comment]
I'm going to move this to the next release for now. I think it would be really helpful to get in, especially for other schools.

**Comment by zqian** [comment]
Test is successful:

- added MyLA test as an LTI tool via URL configuration, named "MyLA autoconfig-2020-12-11T14:39:25.789546"
- enabled the tool in one course site in Canvas test server
- launched the tool successfully in Canvas test server
