### ISSUE TITLE
Only enable django backend login methods if explicitly loaded or not  other auth.

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1060]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added
`DjangoModelBackend` seems to be loaded if either LTI or SAML are not loaded, not either. 

## Describe the solution you'd like
It should really only be enabled at the end of the settings of there is no other `AUTHENTICATION_BACKENDS` available OR if explicitly enabled via a config (which can be useful for a test server).

**Comment by jennlove-um** [comment]
This may be related to #1053.  We need to test.

**Comment by jonespm** [comment]
This has a complicated test plan because of all the possibilities.

* In all modes:
  /admin/login should no longer work

* Either LTI and/or SAML Enabled
  * /accounts/login should display a "Page not found" or blank page

* Either LTI and/or SAML Enabled and setting "ENABLE_BACKEND_LOGIN" set to True
  * /accounts/login should display a login page and work

* Neither LTI or SAML Enabled
  * /accounts/login should display a login screen and allow login

LTI and SAML should also still work when enabled.

**Comment by pushyamig** [comment]
I was able to test with LTI and Local Django Forms. I couldn't test this with SAML as this needs a change in Test setting

**Comment by lsloan** [comment]
I concur.  I didn't test with SAML settings, because I can't, but the combinations of LTI and BACKEND (while SAML is false) worked as described.

:shipit:

**Comment by jonespm** [comment]
I consider this a pass but we should document this better.

* You can't use ENABLE_BACKEND_LOGIN together with SAML. SAML takes priority over the URLS.
* You can enable SAML and LTI, they work together.
* If you enable LTI and BACKEND_LOGIN then the Logout button appears and doesn't work for LTI. (This may be fixable but IMHO is low priority)
* If you had DJANGO_LOGOUT_REDIRECT_URL for SAML you need to unset this or set it to `/`
