### ISSUE TITLE
remove redundant log warning message for MyLA admin

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1061]
There are redundant warning messages in the MyLA log file for admin users:

[2020-08-27 08:05:00 -0400] [WARNING] [db_util.py:113] Couldn't find user <admin user id> in enrollment info. The user could be an admin, or enrollment data has not been populated yet.

Admins never have problem for accessing MyLA tool. Those messages can be removed.

**Comment by jonespm** [comment]
This is on this line

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/6a4dc145c9f8818eabd6fb1a75e885c84e709bd5/dashboard/common/db_util.py#L114

We'd could just a Django lookup to see if they're a super user or not here and not print the warning in that case.

**Comment by pushyamig** [comment]
Or Make it logging at info level

**Comment by chrisrrowland** [comment]
Is this issue only relevant w/ standalone?

**Comment by zqian** [comment]
Verified in test-myla: 

1. login as admin user
2. go to MyLA admin page, and then Courses dashboard
3. find a MyLA course, and click on the "Link" in COURSE LINK column, to go to MyLA site for that course
4. verified that there is no such message in the MyLA log file: "Couldn\'t find user {username} in enrollment info. The user could be an admin, or enrollment data has not been populated yet."
