### ISSUE TITLE
add JWK management tool for LTI config

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/my-learning-analytics#1065]
The next version of the LTI specification will _require_ tools provide their public key via JWKS URL.  This info was provided by Bracken Mosbacker (IMS Global), Eric Preston (Blackboard), and Viktor Haag (D2L) in a conversation on IMS Global's Slack workspace (https://imsglobal.slack.com/messages/C04GUTJTN/p1598555022006400).

This conversation started as I (@lsloan) asked the IMS Global community about whether PEM or JWK public key is preferred.  I asked because I was trying to update our documentation (wiki) to include the option of using the generated JWK instead of the PEM.

Make a Django management tool to give JWK JSON, when necessary.

See also: #1103 (update LTI config docs)

## Testing

See the `getjwk` section of the LTI deployment documentation at https://github.com/tl-its-umich-edu/my-learning-analytics/wiki/Deploy:-Configuration-for-LTI-1.3-Deployment#using-mylas-django-management-tool

**Comment by pushyamig** [comment]
Currently MyLA is configured to use Public key via JWKs URL. it's just a matter of configuration for the tool. Locally I have being using JWKS URL
```
urlpatterns += (
        path('lti/login/', lti_new.login, name="login"),
        path('lti/launch/', lti_new.launch, name="launch"),
        path('lti/jwks/', lti_new.get_jwks, name="get_jwks"),
    )

```

**Comment by zqian** [comment]
verified retrieving jwk values are retrievable via` https://test-myla.tl.it.umich.edu/lti/jwks/`,  and also `curl https://test-myla.tl.it.umich.edu/lti/jwks/ | jq -c '.keys[0]'`
