### ISSUE TITLE
LTI doc cleanup, move keygen program to repo

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/my-learning-analytics#1066]
As discussed in MyLA-Fall-2020.03.02 release planning meeting on 28 August 2020 at 11:00:

* Clean up the LTI 1.3 configuration documentation.
* Move key generation program to repo.  If possible, make it available as a Django management tool.

**Comment by pushyamig** [comment]
`key generation` is working as expected

**Comment by pushyamig** [comment]
The LTI docs looks clean as well, but the page says it is still under construction do we want to remove that?
