### ISSUE TITLE
Hide object level data on the confirmation page in admin delete page in Django

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1067]
## Expected behavior (A clear and concise description of what you expected to happen) : 
When an administrator deletes a MyLA course in Django, they get a confirmation page.  That page should only have the summary of the data being deleted.  It should not list all of the individual objects since that list can get long and does not provide additional value in determining whether to delete the course.

## Describe the bug (Tell us what happens instead of the expected behavior) :
Sometimes deleting  course that has a lot of resources and resources_accessed  information was taking take a long time and generated a 504. While the 504 no longer occurs, the list of resources is still long and unnecessary.

## Steps to Reproduce :
1. Add some courses and run the cron, the courses need to have a decent amount of resources and resource_access data pulled in.
2. Select to delete the course
3. The confirmation page displays with summary and list of objects. The object list is unnecessary.

## Additional context (Add any other context about the problem here) :

Ideally we can just have it display the summary with just the details or skip the confirmation page.

I found this article describing a little about that: https://stackoverflow.com/questions/28365331/how-to-skip-delete-confirmation-page-in-django-admin-for-specific-model

I don't think we need the details.

**Comment by ssciolla** [comment]
https://docs.djangoproject.com/en/3.1/ref/contrib/admin/actions/#actions-that-provide-intermediate-pages

**Comment by ssciolla** [comment]
@jonespm, I was able to override the admin templates so they don't show all those details; see https://github.com/tl-its-umich-edu/my-learning-analytics/commit/93f64e7a272dfe9264d941293c9dcdec600e775a The pages are still loading pretty slowly, which I guess makes sense since the data is still behind the template. I could modify the views to try to change how it loads things, but feels tricky. Maybe some degree of slowness is unavoidable if we're talking about deleting 500 or more Resource Access records?

**Comment by ssciolla** [comment]
Okay, now I'm not sure what to do. After talking with @jennlove-um and doing some testing, this only seems to be an issue on the `test` instance (and by association, Canvas test). Production works fine, and renders hundreds of related objects pretty quickly.

The template overrides I created did not fix the problem on the test instance when I deployed them. I'm not sure what the resource limits or settings we have for the test MyLA deployment and DB, but this feels like a Canvas test bottleneck to me. Even loading the course list in the admin is pretty slow.

**Comment by jonespm** [comment]
Well the test instance is still prod data but maybe it has more data? It doesn't even connect to Canvas Test aside from the LTI launch. The server and database are provisioned the same though Canvas Test has older courses. Hmm!

**Comment by ssciolla** [comment]
Yeah, I don't know exactly why, but things are a lot slower in the Canvas Test LTI version, specifically talking about the admin interface. Thanks for the info, I'll keep looking at this as time allows.

**Comment by jonespm** [comment]
Might be debug toolbar related, only big difference I can think of. When I
was load testing accidently with this on it was about 10x slower. I think
we'll be able to merge #1076 tomorrow and we can see then.

**Comment by jennlove-um** [comment]
Sam and I looked at this in test, and we were not able to reproduce the 504 error.  However, it would still be useful to hide the list of resources accessed in the confirmation page.  That data is not useful to administrators in deciding whether to delete a course and can be overwhelming to look at on the page.  On the confirmation page, we only need Summary data, not the list of Objects.

**Comment by jonespm** [comment]
Sounds good! Not sure if this issue still needs to be in this project or can be bumped to the next. I don't think it was a hard fix but not as important if it's just improving the admin deletion workflow.

**Comment by ssciolla** [comment]
I'll try to finish it, I think I basically did all the work already.

**Comment by ssciolla** [comment]
@jennlove-um, please note that we'll need to test both the "Delete" workflow from the edit page for a specific course, and the "Delete Selected" workflow from the list of courses in the admin. Please reach out to me if you need some clarification.

**Comment by jennlove-um** [comment]
Testing passes: 
- Delete 1 course from course list
- Delete course from course detail page
- Delete multiple coursers from course list

In all cases, the confirmation page displayed summary counts without the list of objects.
