### ISSUE TITLE
Provide a way to handle the Canvas test student (Student View)

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1069]
Canvas allows instructors to view their courses as a student, and in doing so creates a test student user for the course. When teacher tries to view MyLA as this user, we provide a basic error message that indicates MyLA is not available for the student view.

Further discussion is needed about how to handle the test student:
- Investigate whether the test student data is being sent to MyLA and is included in any of the visualizations.  If it is, this will need to be filtered out.
- Determine whether MyLA will support the student view functionality in Canvas.  If so, design the view.  If not, design a more user-friendly message for instructors than the current basic JSON one.

**Comment by jonespm** [comment]
Actually right now in production the message sent is:
![image](https://user-images.githubusercontent.com/27447/91735216-f7d93980-eb79-11ea-9d35-3494c2d0567e.png)

It looks like this user doesn't get any email sent so if we did support them it would have to be a special generic case. 

It does send this over as a role.
`http://purl.imsglobal.org/vocab/lti/system/person#TestUser`

The only visualization this might be in would be the Resource Accessed if this data is actually in Caliper. There wouldn't be any other data for this user in the UDW. 

With being able to reset I'm not sure what it would be possible to show the test user. The grade distribution (the instructor can already see this). Maybe we should really just have a message **"No data can be provided when in Student View, please start MyLA from a regular view"**

**Comment by jennlove-um** [comment]
#1043 with the next release provides the clearer error message.  Sorry for the confusion.  Per that issue, the message is set to read "Student view is not available for My Learning Analytics."

But we could change that to the text you suggested @jonespm.

**Comment by jonespm** [comment]
So this kind of feels like a duplicate of that #1043. The only thing I feel like we really can do here is research that the test user's caliper events aren't coming up in the views but that's also an open issue at #764

**Comment by jennlove-um** [comment]
Per the discussion notes in this issue, it replicates other issues.  I'm closing this one.
