### ISSUE TITLE
Disable logout URL when LTI is configured

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1079]
If you're launching via LTI we should disable the logout link in the UI as it really won't do anything. Maybe should just pass something to the myla globals whether or not to show the logout? This was kind of mentioned on this ticket.

However it's possible to ENABLE_BACKEND_LOGIN and login that way. In that case we should still have the logout link. So this might not be completely straightforward to fix.

**Comment by jonespm** [comment]
This might be something we want to try to get in for the 03.02 release, have to see how it's working after the fixes to see if we can bump it or not.

**Comment by jennlove-um** [comment]
Testing passes.  The logout link does not display for students, teachers, or admins in the profile menu.
