### ISSUE TITLE
Remove the package django-settings-export

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1084]
It looks like the package djang-settings-export is no longer used and can be removed as well as this SETTINGS_EXPORT variable.

#784 has moved a lot of this to the views. We only were using this to make these values easily available to the templates. 

> do we need to have this package django-settings-export? since the 
> 1. login/logout is not be using in the template and 
> 2. GA_ID is passed in via myla globals and 
> 3. I am not sure `RESOURCE_VALUES` is actually used it like that
> 4. I am not sure DEBUG is any values
> 
> If this package is not needed we need to clean up
> 
> _Originally posted by @pushyamig in https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1073#discussion_r486367772_

**Comment by zqian** [comment]
verified in MyLA test.
