### ISSUE TITLE
Exception/tracebacks when loading frontend/index.html template

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#1088]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 

We shouldn't be regularly seeing exceptions and tracebacks in the logs.

### Describe the bug (Tell us what happens instead of the expected behavior) :

There seems to be some exception and tracebacks logged at the `DEBUG` level when trying to load the `frontend/index.html` template.

```
[base.py:867] Exception while resolving variable 'content' in template 'frontend/index.html'.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 828, in _resolve_lookup
     current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'content'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'content'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 847, in _resolve_lookup
   raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [content] in None
```

### Steps to Reproduce :
1. Monitor the logs when the application is initially loading in a browser.

**Comment by jennlove-um** [comment]
Zhen will verify whether this is still an issue.

**Comment by jonespm** [comment]
This is still an issue, this is just a problem locally when flatpages content isn't set

**Comment by zqian** [comment]
Tested on MyLA test instance where debug mode is on:

- Removed the content of /copyright/ flat page
- checked the log file and found no occurrence of above stack trace.
- Added the content back in /copyright/ flat page
