### ISSUE TITLE
STUDENT_DASHBOARD_LTI should be renamed

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1094]
The config value "`STUDENT_DASHBOARD_LTI`" should really be something like

`ENABLE_LTI `

Since the project is no longer student dashboard. We also have STUDENT_DASHBOARD_SAML but that should be deprecated.

You'd want both to work so use the STUDENT_DASHBOARD_LTI as the default value if this isn't set for backward compatibility. 

`ENV.get('ENABLE_LTI', ENV.get('STUDENT_DASHBOARD_LTI', False))
`
https://github.com/tl-its-umich-edu/my-learning-analytics/blob/a3f624fc868af2c2cfb1e5a62735506655865779/config/env_sample.json#L94

**Comment by jonespm** [comment]
This setting can probably be removed with #1212

**Comment by jonespm** [comment]
#1212 was done but this still should be cleaned up too.

**Comment by pushyamig** [comment]
I will QA this.

**Comment by pushyamig** [comment]
I used the old key STUDENT_DASHBOARD_LTI = true and I can see the test passing
I used the new key Enable_LTI=true and test passes.

Test Passes
