### ISSUE TITLE
update LTI config docs (wiki)

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/my-learning-analytics#1103]
Related to #1065 (from which this was split out) and document(s) received from Rafael at Unizin.

Finish updating the LTI configuration documentation in the wiki of this repository.

The docs are confusing and difficult to follow.  Changes made so far include:

* Remove recommendation to pass around public key JWK as part of the configuration.  The LMS can get it automatically from MyLA when needed.
* Added instructions for using `createkeys` and `getjwk` Django management tools.
* Moved development instructions to a separate document.

Other changes to be made:

* [x] Incorporate ideas from Unizin documentation.
* [x] Add documentation for new "config by URL" feature, #1054.

## Testing
Please proofread the new versions of the LTI configuration documents at:

* https://github.com/tl-its-umich-edu/my-learning-analytics/wiki/Deploy:-Configuration-for-LTI-1.3-Deployment-NEW
* https://github.com/tl-its-umich-edu/my-learning-analytics/wiki/Dev:-Configuration-for-LTI-1.3-Development-NEW

**Comment by jennlove-um** [comment]
@pushyamig I proofread the linked documents for basic readability and language.  But I can't proofread in terms of telling if the information is correct.  Would you be able to do a quick read-through for testing from the development perspective?  Thanks!

**Comment by pushyamig** [comment]
This looks good to me
