### ISSUE TITLE
Add pop-up to gather student feedback when using MyLA

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1107]
### Describe your problem or feature you'd like added
For research purposes, add a pop-up window to MyLA to collect feedback from students about their experience using MyLA. This feature needs to be configurable so that it can be turned on and off for a MyLA instance.  It does not have to be configurable at the course level.

### Describe the solution you'd like
TBD: The details of when to pop up the question, what question(s) to use, and how often to show the question are still being determined. 

### Describe any possible alternatives you've considered
We could consider using Qualtrics surveys and using embed codes.

**Comment by jennlove-um** [comment]
Sample Qualtrics popup: https://umich.qualtrics.com/jfe/form/SV_5AcTDiXHdBGknTn
Embed: <iframe src="https://umich.qualtrics.com/jfe/form/SV_5AcTDiXHdBGknTn" height="800px" width="600px"></iframe>

**Comment by jennlove-um** [comment]
@jonespm I created a simple survey with a couple of question types that we can experiment with for a sidebar survey.

**Comment by jennlove-um** [comment]
Also capture the student identity and course when they submit the survey.

**Comment by jonespm** [comment]
Current TODO (From meeting)

* Make survey button a little more noticable (Just change the text color?
* Explore using parameters to capture more about the survey taker, course, etc. qualtrics.com/support/survey-platform/survey-module/survey-flow/standard-elements/passing-information-through-query-strings
* Make the text of the button configurable in constance. Default to "Take Survey"

**Comment by jennlove-um** [comment]
All of the issues listed in the TODO comment above have been tested and pass.  Testing passes for adding the survey to MyLA and having it pop up for students when they click the survey button.  Testing also passes for no survey button displaying when no survey URL is present in the configuration on the admin screens.
