### ISSUE TITLE
Problem starting up when not setting GUNICORN_RELOAD

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1108]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 

If you don't set the environment variable GUNICORN_RELOAD it doesn't look like it's starting up. This is related to a change on #998. 

### Describe the bug (Tell us what happens instead of the expected behavior) :

Because "${GUNICORN_RELOAD}" is quoted now it's causing a problem for the command line. I think that we should reconfigure these GUNICORN options to just allow you to pass whatever you want. Also it should probably reload when in development (or PTVSD) mode. 

### Steps to Reproduce :
1. Don't set GUNICORN_RELOAD
2. Try to startup
3. Error of "gunicorn: error: unrecognized arguments: "

**Comment by jonespm** [comment]
Locally in docker-compose.yml this was set GUNICORN_RELOAD=True so we didn't see this locally. To test this you'll have to.

- Comment out the `GUNICORN_RELOAD=True` in `docker.compose.yml`
- Don't set `PTVSD_ENABLE` (or have it set to false) in the yaml configuration.

**Comment by pushyamig** [comment]
Not related to this directly but in a way... Now when PTVSD is enabled it is using GUNICORN with single worker, I see when when debugger is enabled in VSCODE and when it stops at a breakpoint after certain time ( very short duration) the debugger is disconnected by itself. This was not happening when PTVSD was enabled with Django default Server

**Comment by jonespm** [comment]
Thanks for the info! It looks like it was somewhat related as I'd forgotten to pass the `GUNICORN_TIMEOUT` and it looks like it's causing the PTVSD to timeout. I'll set this to unlimited when debugging.

**Comment by pushyamig** [comment]
I tested this locally, test passes and this is not an issue in MylA test as well
