### ISSUE TITLE
upgrade Python LTI module

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/my-learning-analytics#1109]
The `PyLTI1p3` module for Python has a newer versions available than the v1.7.0 release MyLA uses.  It includes new features which would simplify MyLA's LTI support code and thereby reduce the possibility of bugs in its codebase.

**Comment by lsloan** [comment]
@jennlove-um, I think this may be a candidate for the `MyLA-Winter-2021.01.01` project.
`

**Comment by jennlove-um** [comment]
We updated PyLTI1p3 to 1.9.1 in the MyLA-2021.03.02 release in #1286. I'm closing this issue.
