### ISSUE TITLE
Make the Assignment Planning view easier to scroll and see

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1113]
### Describe your problem or feature you'd like added
UX testing and feedback from students indicated that they want to be able to see the progress bar, goal, and assignments at the same time.  They also had difficulty scrolling through the two parts of the screen.  We need to simplify the view to address this.

### Describe the solution you'd like
Make the top section of the screen with the progress bar and goal smaller.  Make the top bar and the goal field sticky so that they stay in view when scrolling through assignments. For desktop view, the goal and progress bar could be placed next to one another to save space.

**Comment by pushyamig** [comment]
I started to work more are less we need to make both Progress bar and table header sticky i.e table header needs to stack with Progress bar. I felt Goal and progress bar will be in single line so I changed it as 

![Screen Shot 2020-11-17 at 9 53 37 AM](https://user-images.githubusercontent.com/8579775/99405525-df480800-28ba-11eb-9456-460bc85d0ed4.png)

Table Header needs to be sticky for the table content and sticky to the progress bar. I am running in to this issue where both header and progress are stacks up confusingly as you scroll

![Screen Shot 2020-11-17 at 9 59 35 AM](https://user-images.githubusercontent.com/8579775/99406393-d441a780-28bb-11eb-91d7-3120d8de41c6.png)

**Comment by pushyamig** [comment]
I did not see the feasibility of making the Top portion ( goal + progress ) stack on top of Table header. It's like stacking 2 things and since the table introduces the scroll this make double scroll avoidable with standalone tool and 3 scroll bar with LTI. 

Having a triple scroll would be very annoying but something to keep in mind for next time when we introduce a scroll.

**Comment by chrisrrowland** [comment]
The goal text now overlaps the Grade Progress text
![image](https://user-images.githubusercontent.com/17617998/102415228-d20b5f80-3fc5-11eb-86a6-90226ac8d6fa.png)
![image](https://user-images.githubusercontent.com/17617998/102415243-d6d01380-3fc5-11eb-8af9-ee7124d83e95.png)

**Comment by ssciolla** [comment]
Thanks, @chrisrrowland. This is something we knew about and I showed to @jennlove-um before proceeding with the new layout. I'm going to work on a solution for this (I had one but it was nixed), but this is an edge case (most people won't be entering goals that low).

**Comment by jennlove-um** [comment]
Testing passes: The scrolling is less confusing and putting the goal and bar next to one another has provided more room for the list of assignments.
