### ISSUE TITLE
Ensure LTI launches can work even if sis id is not set

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1120]
### Expected behavior (A description of what you expected to happen) : 

When launching from a course in LTI, we **should** only need to use the Canvas ID's rather than any other ids to determine the launch information. Student users with incomplete information should still work and be available in MyLA

### Describe the bug (Tell us what happens instead of the expected behavior) :

It looks like when MyLA creates the user it's using the username. It seems like this should be available and work but we'd need to verify this.

`        user_obj = User.objects.create_user(username=username, email=email, password=password, first_name=first_name,last_name=last_name)`

However when creating the instructors it uses `user_sis_id` which may not be available. We also want to ensure that the check that the user can access the course can work if sis_id is not available from the LTI launch.
 
### Steps to Reproduce :
1. Create a user in Canvas without an SIS ID
2. Add this user to a course in Canvas
3. Try to use MyLA as this user, once the ETL is run after the UDW has run the user should have access to the course.

**Comment by jennlove-um** [comment]
@zqian Can you help with testing this? I haven't been able to figure out how to get a user with no SIS id enrolled in a Canvas course.

**Comment by jennlove-um** [comment]
Testing passes: I am able to launch MyLA from a Canvas course when masquerading as a user with no SIS ID.
