### ISSUE TITLE
Create a different icon and description for each assignment view

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1121]
Thank you for contributing to this project!

### Describe your problem or feature you'd like added
Each assignment view (the v1 and the current) both have the same icons and description if enabled. We should add some additional text/image to differentiate them so users know they're two different tools. Also in the dropdown menu they should have a different name.

### Describe the solution you'd like
Create a new image and add a new description. Not sure if we should just leave it as Assignment Planning (V1) and Assignment Planning as the two names or have something more creative?

- [x] Provide a new icon for the new assignment planning
- [ ] Rename old assignment (Assignment Planning V1)
- [x] Provide a better description for the new assignment planning

### Describe any possible alternatives you've considered
Ideally we'll remove Assignment Planning (V1) but we're not ready for this yet.

**Comment by chrisrrowland** [comment]
@jonespm We want the title of assignment planning V1 to be "Assignment Planning V1" in the UI? 
Seems like we would want to rename the new version to V2 until V2 replaces it?

**Comment by jonespm** [comment]
In the backend, we called the new one just "Assignment Planning" and the old one "Assignment Planning V1". I'm not sure what we should name them in the UI though. I'd think they are different and should have had different names like "Assignment Overview" (old) and "Assignment Goal Planning" (new). Maybe others have ideas

**Comment by jonespm** [comment]
The ultimate goal is to delete the old one but these should have been better differentiated.

**Comment by chrisrrowland** [comment]
What is the 2nd checkbox regarding specifically?

**Comment by chrisrrowland** [comment]
I just tweaked a screenshot to get this.  Is this acceptable or is there something more specific that we're looking for?

![image](https://user-images.githubusercontent.com/17617998/100894229-42749580-348a-11eb-9dea-90ce4d752ca8.png)


![image](https://user-images.githubusercontent.com/17617998/100893951-ead62a00-3489-11eb-9c79-3cb36954800c.png)

**Comment by chrisrrowland** [comment]
@jennlove-um do you have a new description for assignment planning v2?

**Comment by chrisrrowland** [comment]
@jonespm Do you know what was specifically meant with the 2nd checkbox

> Rename old assignment (Assignment Planning V1)

**Comment by chrisrrowland** [comment]
> I just tweaked a screenshot to get this. Is this acceptable or is there something more specific that we're looking for?
> 
> ![image](https://user-images.githubusercontent.com/17617998/100894229-42749580-348a-11eb-9dea-90ce4d752ca8.png)
> 
> ![image](https://user-images.githubusercontent.com/17617998/100893951-ead62a00-3489-11eb-9c79-3cb36954800c.png)

@jennlove-um  does this look ok?  I just took a screenshot and cleaned it up a tiny bit.

**Comment by chrisrrowland** [comment]
@jennlove-um Would this come from you or the researchers or should I just write something?

> Provide a better description for the new assignment planning

**Comment by jonespm** [comment]
It looks okay to me, maybe we'll just have to wait to talk about it on Friday. 

Also I noticed the color accessibility of the Goal line on that blue background really isn't very good. It only has a 1.84:1 contrast ratio and looks invisible to me. We should probably change the color of this bar. 

Either a much brighter green like #12FF0A or a better contrasting color like yellow like #FFF700. (Which would might look better for Michigan anyway)

**Comment by jennlove-um** [comment]
For the description, let's add a reference to goal setting: See what assignments have the greatest impact on your grade and set grade goals.

**Comment by jennlove-um** [comment]
@chrisrrowland I think the image is okay.  I couldn't remember if the images for the other cards are SVGs.  If so, I could try to recreate it as an SVG.

**Comment by pushyamig** [comment]
@jennlove-um the images are not SVG https://github.com/tl-its-umich-edu/my-learning-analytics/tree/master/assets/images

**Comment by jonespm** [comment]
Yeah, the images are fine, it might have looked a little better responsive if they were SVG and I thought they might have been too but they seem to look fine on Mobile.

We do have an SVG image that we embed into Canvas.

**Comment by jennlove-um** [comment]
Testing passes: The new icon and text display correctly on the tile for the new Assignment Planning view.
