### ISSUE TITLE
On the home page, cards with the i-icon compress the text below the title 

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1123]
### Expected behavior (A description of what you expected to happen) : 
All title cards should have the i-icon to link to help documentation.  When the i-icon is added, it should not cause the title and background to expand so much that it compresses the text below the title.

### Describe the bug (Tell us what happens instead of the expected behavior) :
When the i-icon is added to the title, text below the visualization title gets compressed.

### Steps to Reproduce :
1.  Go to the homepage for a MyLA course
2. Compare the cards with an i-icon to the one without to see an example

### Screenshots/Video (If possible, add media to help explain your problem) :

![MyLA_HomePageCardsWithIcons](https://user-images.githubusercontent.com/39634416/99841197-c69a5500-2b3b-11eb-8c3c-9d22f95e5cb5.png)

**Comment by jonespm** [comment]
I don't know if this is entirely a problem with that icon. When running in a reduced view (launched from Canvas) with only 2 cards to a row, it also reduces the size even though it looks like the space available is the same. 

Reducing the padding in the browser of jss18 from 8px to 4px makes this look better but I don't 100% know where that padding is defined or if there's a better fix. Maybe this is in the CourseList.js? 

```
.jss18 {
  color: black;
  height: 100%;
  padding: 8px;
}
```

![image](https://user-images.githubusercontent.com/27447/99844785-a1104a00-2b41-11eb-98e8-c1d89f7c69d8.png)

**Comment by jennlove-um** [comment]
Testing passes for this release.  The text displays cleanly on the tiles inside a Canvas course.
