### ISSUE TITLE
Assignment-Redesign: Current grade and max Possible grade line is not shown for students 

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#1125]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 
The current/Max possible grades line is show for the default admin view but it is not visible after you become student. This was working before some where recent changes to the assignment planning v2 broke this. 

### Steps to Reproduce :
1. Become as a student user and current/max grade line is missing
2. 
3.

**Comment by pushyamig** [comment]
This problem seems to happen for certain courses only and not for ever course. Needs to figure out what is the root cause for this.

**Comment by pushyamig** [comment]
Test plan: 
1. Choose a course where some of the assignments points_possible =0 
2. you can also set any of the assignments `points_possible `column to 0 in `assignment` table to trigger this case

**Comment by jennlove-um** [comment]
Testing passes: Current and max possible grades display correctly when a course has an assignment with 0 points.
