### ISSUE TITLE
Switch from PTVSD to debugpy

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1128]
PTVSD is deprecated [according to their Github 
](https://github.com/microsoft/ptvsd#-%E1%B4%98%E1%B4%9B%E1%B4%A0s%E1%B4%85-%C9%AAs-%E1%B4%85%E1%B4%87%E1%B4%98%CA%80%E1%B4%87%E1%B4%84%E1%B4%80%E1%B4%9B%E1%B4%87%E1%B4%85-) and replaced with [debugpy](https://github.com/microsoft/debugpy/).

We should switch to that to ensure the debugging support continues. It looks like this will involve some slight code changes.

**Comment by jonespm** [comment]
To test this locally you need to be using VSCode with MyLA and setup the configuration with the steps in the [Contributing Guide](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/CONTRIBUTING.md#testing-tips).

**Comment by pushyamig** [comment]
I tested this locally. So test passes

**Comment by pushyamig** [comment]
I take that back. I see on Test Myla server it says `Starting Gunicorn for DEBUGPY debugging` why is this? I don't see DeBUGPY variable being set

**Comment by jonespm** [comment]
Yeah, there's something wrong here. I'm seeing that too, but not on localhost when I remove this setting.

It should say "Starting Gunicorn for production"

**Comment by jonespm** [comment]
I've fixed this on #1177 and put in a PR

**Comment by pushyamig** [comment]
I am going to close this as done. We review it again with #1177
