### ISSUE TITLE
Split out pip install from apt-get step in Dockerfile

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1129]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Describe the bug (Tell us what happens instead of the expected behavior) :
We should split out the pip install from the RUN line in the docker file that installs OS dependencies. This step takes almost 4 minutes for each step and really slows down development when just changing and testing requirements.

I think we also could add a little more cleanup in here to reduce image size.

**Comment by zqian** [comment]
It is a good practice to separate out the pip install statement. However, I did not see much performance improvement. This is what I have tested:

Without the PR: 

1. docker-compose down
2. docker-compose build
3. change the requirements.txt -pandas==1.0.5 +pandas==1.1.4
4. docker-compose build

Here is the step with "apt-get" and "pip install" COMBINED: 
 => [app 4/11] RUN apt-get update &&     apt-get install -y --no-install-recommends     build-essential default-libmysqlclient-dev  libpq-dev netcat vim-tiny jq python3-dev  163.7s

With the PR:

1. docker-compose down
2. docker-compose build
3. change the requirements.txt -pandas==1.0.5 +pandas==1.1.4
4. docker-compose build

Here is the step with "apt-get" and "pip install" SEPARATED:
 
 => [app 4/12] RUN apt-get update &&     apt-get install -y --no-install-recommends     build-essential default-libmysqlclient-dev  libpq-dev netcat vim-tiny jq python3-dev   69.1s
 => [app 5/12] RUN pip install --no-cache-dir -r requirements.txt                                                                                                             105.8s

Those two steps took about the same amount of time compared to the prior PR code.

**Comment by jonespm** [comment]
Yeah, the only time you'd notice is if you're changing around the python requirements.txt, since every layer before would be cached. Without this it would also re-install the Ubuntu packages. 

This also removes the caching from the python packages (should have been in there before) and will help us if we want to reduce the size of the layers later.

It's a minor change overall.
