### ISSUE TITLE
Add a date field to the courses table to capture when the course was added to MyLA

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1135]
### Describe your problem or feature you'd like added
Capture the date that an instructor adds MyLA to their course as an LTI.  This data is useful for administrators in troubleshooting issues.

### Describe the solution you'd like
Add a field to the courses table that captures the date and time that a course was added to MyLA.

**Comment by jonespm** [comment]
PR merged Test Plan
1) Verify in the admin interface that existing courses don't have any date created set
2) Add a course, verify that it has the date that it was created
3) Wait a few minutes, verify that the date hasn't changed

I feel like one edge case is that if this value is null and the course is saved it might add a date there. I think only an admin could do this and don't know how likely an issue is. It should be tested if this happens. I don't think an instructor changing the views should add a date but I didn't test this. 

I think to avoid this we'd have to have it set the dates to *something* other than null by default. Like if they were 2018-01-01 for instance, before MyLA existed.

**Comment by jennlove-um** [comment]
Tested in beta:

- Tested adding a new course.  The added date displayed correctly.
- Tested an instructor changing the views on a course.  No date was added to course with null date.  No date was changed in course with date. 
- Tested admin updating course and saving in Django.  No date was added to course with null date.  No date was changed in course with date.
