### ISSUE TITLE
Make the top navigation "fixed"

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1137]
Thank you for contributing to this project!

### Describe your problem or feature you'd like added
The top navigation bar should remain on the page as the page is scrolled down. Users may want to interact with this at any time and we may want to add more content in here.

### Describe the solution you'd like
This may be similar to #1113 and maybe have some fixed position.

**Comment by jonespm** [comment]
Was looking at some other sites that have a top nav like MyLA. Seems like the only site I've found that doesn't do this is Github. Gitlab is kind of what I'm thinking about.

__Not Sticky__
Github - Top bar isn't sticky, scrolls off page

__Sticky__
Gitlab - Top bar is sticky
Facebook - Top bar is sticky, stays on top
Twitter - Top, left and right navigation are sticky
Gmail - There's no way to scroll the main area, individual areas are scrollable

**Comment by pushyamig** [comment]
Myla Top navigation bar uses Material UI AppBar I suppose something in the library properties should be used to make it work. My hunch is this should be simple change. 

But this tool is embedded inside canvas and we user goes to outer scroll that's  when I feel the User experience differs

**Comment by jonespm** [comment]
Looks like just changing static to fixed does this
https://stackoverflow.com/questions/43647661/dock-app-bar-to-top-of-window-in-react-material-ui
