### ISSUE TITLE
Assignment filtering is selected and assignment goal change is not updated in UI 

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#1139]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 
When ever user selects a assignment filter option and changes a assignment goal grade the UI is not updating with change. But this is not an issue when no filter option is selected
### Steps to Reproduce :
1. Set a Course goal grade
2. select a assignment filter
3. Change assignment goal grade and UI is not updating, I can almost say the UI update is not happening every-time. But I can see user setting saved alert is trigged for it sometime

**Comment by pushyamig** [comment]
This issue is related to https://github.com/tl-its-umich-edu/my-learning-analytics/issues/1114

**Comment by jennlove-um** [comment]
Testing passes: The course goal could be changed and displayed correctly in the UI when one ore more of the assignment filters was active.  I tested with each filter individually as well as with multiple filters.
