### ISSUE TITLE
Change text on the goal box from “Math may no longer add up” to “Scores no longer match goal”

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1140]
### Change requested
When the assignment goals set by the student no longer match the course goal that they set, an information message displays on the course goal text box.  Currently, that text is "Math may no longer add up."  Change that text to be "Scores no longer match goal."

**Comment by jennlove-um** [comment]
This passes in myla-test.

**Comment by jennlove-um** [comment]
@zqian This passed several weeks ago but is failing today.  Can you take a look?

**Comment by jonespm** [comment]
Looks like this change was reverted by the PR on #1119 for issue #1113

**Comment by jennlove-um** [comment]
Ok, I'll move this to the next release instead.

**Comment by jennlove-um** [comment]
This passes in testing.
