### ISSUE TITLE
Improve color contrast of goal bar line

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1144]
Also I noticed the color accessibility of the Goal line on that blue background really isn't very good. It only has a 1.84:1 contrast ratio and looks invisible to me. We should probably change the color of this bar. 

Either a much brighter green (like #12FF0A) or a better contrasting color like most yellows (like #FFF700). (Which would might look better for Michigan anyway)

![image](https://user-images.githubusercontent.com/27447/101534364-04cdac00-3965-11eb-80e3-c2c96a7c13be.png)

_Originally posted by @jonespm in https://github.com/tl-its-umich-edu/my-learning-analytics/issues/1121#issuecomment-740930784_

**Comment by pushyamig** [comment]
Closing the issue after hearing the comment from @gsilver

`It is sufficient for accessibility that the green line extends above the bar so that the meaning is still clear to the user. `

So the Green line that is extended  still clear to the user  (green/white contrast is accessible)

**Comment by jennlove-um** [comment]
Since there were no changes needed for this issue, I'm removing it from the release.
