### ISSUE TITLE
Assignments are not sorted by due date

### ISSUE THREAD

**Issue by chrisrrowland** [tl-its-umich-edu/my-learning-analytics#1146]
Assignments are sorted by week, but within the week do not appear to be sorted by due date.

I'd assume they should be sorted by Week > Due Date > Group (*This is new) > Name 

![image](https://user-images.githubusercontent.com/17617998/101539761-0a2ef480-396d-11eb-8982-397bb26b1951.png)

**Comment by jennlove-um** [comment]
Testing passes: Assignments are displaying in order by due date within each week.
