### ISSUE TITLE
Add aria-label="same value as the title of the 'i' link" to IndexPage buttons

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1151]
Based on the accessibility review done in #907, we need to add the aria-label="same value as the title of the 'i' link" to IndexPage buttons.

**Comment by pushyamig** [comment]
I am closing the issue after consulting with @gsilver since it doesn't need any more fixes. Things Looks good!

**Comment by pushyamig** [comment]
Also removing from the Winter project
