### ISSUE TITLE
Add Assignment Planning V2 help link

### ISSUE THREAD

**Issue by chrisrrowland** [tl-its-umich-edu/my-learning-analytics#1166]
With the assignment planning redesign set to replace the original version, the new version needs a help url.
This will cause the info link to appear on the card.

The help url should be set in settings.py

`URL_VIEW_ASSIGNMENT_PLANNING = ENV.get("URL_VIEW_ASSIGNMENT_PLANNING", None)`

similarly as it is to the  original version

`URL_VIEW_ASSIGNMENT_PLANNING_V1 = ENV.get("URL_VIEW_ASSIGNMENT_PLANNING_V1", "https://its.umich.edu/academics-research/teaching-learning/my-learning-analytics/support/assignment-planning")`

Given that the new help content would likely contain screenshots of the content, it may be something that has to be added after the initial release.

**Comment by jennlove-um** [comment]
Let's use this URL as a placeholder until I can get the new page: https://its.umich.edu/academics-research/teaching-learning/myla-for-students

**Comment by jennlove-um** [comment]
Testing passes: The link works with the temporary URL.  We'll need to update that URL to the new Assignment Planning help page as soon as it is avaialable.
