### ISSUE TITLE
After recent change, if DEBUGPY_ENABLE not set the server still uses debug mode

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1177]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 
If DEBUGPY_ENABLE is not set in the config then system starts up in debug mode. It should start up in production mode.

### Describe the bug (Tell us what happens instead of the expected behavior) :
Relates to #1128, it seems like the check for whether or not the variable is set isn't working correctly.

### Steps to Reproduce :
1. Don't define `DEBUGPY_ENABLE` anywhere at all
2. Start up MyLA
3. You should see **"Starting Gunicorn for production"** in the logs
4. Then in the environment set `"DEBUGPY_ENABLE": false,` restart and you should see in the logs the same message **"Starting Gunicorn for production"**
5. Finally set `"DEBUGPY_ENABLE": true,` restart you should see **"Starting Gunicorn for DEBUGPY debugging"** in the logs

**Comment by zqian** [comment]
Verified in the test myla instance, where "DEBUGPY_ENABLE" is not set, the server log shows "Starting Gunicorn for production"
