### ISSUE TITLE
Change the title of the goal box from “My Minimum Goal” title to “My Minimum Goal (%)”

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1179]
To make it clearer to students that the minimum course goal should be set as a percentage, change the wording of the title for the goal box from  “My Minimum Goal” title to “My Minimum Goal (%)”

![image](https://user-images.githubusercontent.com/39634416/102540313-d9417480-407c-11eb-9117-f07a8f8b6b73.png)

The text inside the box does not need to be changed.

**Comment by jennlove-um** [comment]
@ssciolla or @chrisrrowland Would you have time to do this?

**Comment by ssciolla** [comment]
Yes, @jennlove-um, you can assign me.

**Comment by jennlove-um** [comment]
Testing passes: The label now reads "My Minimum Goal (%)"
