### ISSUE TITLE
Update default URL for assignment planning

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1197]
### Describe the bug (Tell us what happens instead of the expected behavior) :

The new assignment planning view url default in the code should be

`"URL_VIEW_ASSIGNMENT_PLANNING": "https://its.umich.edu/academics-research/teaching-learning/my-learning-analytics/support/assignment-planning-goals",`

**Comment by zqian** [comment]
Verified the right target URL is used on MyLA test server.
