### ISSUE TITLE
When a course/term has no start/end date message should just be info and indicate which course/term

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1198]
### Expected behavior (A description of what you expected to happen) : 
When a course/term doesn't have a date_start or date_end a warning is currently printed from models without any details of the problematic course term. Also this message can just be INFO.

### Describe the bug (Tell us what happens instead of the expected behavior) :
The messages are similar to the ones below.
```

[2021-01-13 08:22:06 -0500] [WARNING] [models.py:219] No date_start value was found for course or term; setting to current date and time
[2021-01-13 08:22:06 -0500] [WARNING] [models.py:226] No date_end value was found for course or term; setting to two weeks from now
```

Reduce these to INFO and print out the actual course or term that has a problem.

### Steps to Reproduce :
1. Add a course or term without a date_start, date_end and no term. Like a brand new course that hasn't gotten into UDW yet.
1. You also can just add MyLA to a course that hasn't yet run the cron on it, and launch it. This error will also print for that course, and it shouldn't be a warning.
1. Add a term that doesn't have date_start or date_end (Might be harder to test, and wasn't the problem here but it does say term in the log message)

**Comment by saputran** [comment]
Hi - I hope you're doing well! I'm a student in EECS 481 and am interested in working on this issue. One quick question - are we allowed to create test courses within the "admin" page for testing (e.g. with random canvas course ids and names)?

**Comment by saputran** [comment]
I'm trying to reproduce this error but am unable to - I created a new course in admin called "test course" with id "123" but it gave me no errors when I didn't put a start or end date. Where is this error supposed to show up/am I doing the wrong steps to reproduce?
![image](https://user-images.githubusercontent.com/44738429/159763396-87fa4df1-3a62-4a2c-881c-1535c38c847b.png)

**Comment by jonespm** [comment]
Hi!

Sure you can create any sites locally.

This error looks like it occurs when you access the site normally as a user. The link on this top of this page **View on Site** or the course link on the main admin courses page would take you there. 

It looks like we wanted to adjust these warnings to INFO and ideally include the course ID that was causing the problem.

`canvas_id` looks like it should be available in that property method.

**Comment by saputran** [comment]
I see it now - thank you! Is there no front-end warning to the user themselves (e.g. we would only see them in the logs)? How would the user know that there is a warning?

**Comment by jennlove-um** [comment]
@jonespm Is this something I can test?  Or is the error only apparent in the docker logs (which I don't have access to)?

**Comment by jonespm** [comment]
Yeah, it's only in the logs, we'll have to verify.

**Comment by jonespm** [comment]
I do see these two messages in the logs.

It looks like the second should be "No date_end value" though.

```
[2022-04-29 13:32:04 -0400] [INFO] [models.py:222] No date_start value was found for course Jonespm's it's over 9001 (437407) or term; setting to current date and time
[2022-04-29 13:32:04 -0400] [INFO] [models.py:229] No date_start value was found for course Jonespm's it's over 9001 (437407) or term; setting to current date and time
```

**Comment by jonespm** [comment]
Okay update the message, looks good now.
