### ISSUE TITLE
Two Assignment Planning links appear in "hamburger" if you have both enabled.

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1199]
### Expected behavior (A description of what you expected to happen) : 
When clicking the hamburger icon, 2 links to assignment planning appear if you have both enabled. A issue in a recent release in #1121 updated the icon and description but the title wasn't updated.

### Describe the bug (Tell us what happens instead of the expected behavior) :
As the behavior said this is what the dropdown looks like.
![image](https://user-images.githubusercontent.com/27447/104458547-8672b400-5579-11eb-814d-629fe87fb299.png)

We should probably call the new assignment planning "Assignment Goal Planning" or "Assignment Planning with Goals"? I'm not 100% sure what to call it?

### Steps to Reproduce :
1. Login as admin or with all views enabled 
2. Click on the upper right icon, notice both links have the same name
3.

**Comment by jonespm** [comment]
@jennlove-um Have any thoughts on what titles to use here? This probably won't be so much a problem for us but for the short term if other schools have both enabled. We could also rename the previous one?

**Comment by jennlove-um** [comment]
How about Assignment Planning & Goals?  The goal piece is the main functionality that differentiates the two views.

**Comment by jennlove-um** [comment]
This is working as expected, and we plan to remove the old AP view.
