### ISSUE TITLE
Allow for null or invalid LTI deployment IDs

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1207]
To accommodate piloting in environments where a deployment ID is generated for each pilot course using MyLA, there needs to be an additional configuration variable that disables deployment ID validation.

Add LTI_CONFIG_DISABLE_DEPLOYMENT_ID_VALIDATION (default false) which will disable deployment id validation if true.

**Comment by zqian** [comment]
Verified the test instance works fine with LTI launch without LTI_CONFIG_DISABLE_DEPLOYMENT_ID_VALIDATION setting in env.json file.
