### ISSUE TITLE
Support Additional data source for Resource Access (LRS db connection)

### ISSUE THREAD

**Issue by andrew-gardener** [tl-its-umich-edu/my-learning-analytics#1209]
### Describe your problem or feature you'd like added
UBC's LRS is not setup on BigQuery. Adding (optional) support for a more generic data source connection would help us use the Resources Accessed view

### Describe the solution you'd like
Add an optional generic LRS data source (similar to DATA_WAREHOUSE)

**Comment by jennlove-um** [comment]
@andrew-gardener @justin0022 This is set to go in the MyLA 2021.02.01 release which we're scheduling to be ready for this Thursday, Feb 18. 

If there is any additional testing or feedback you'd like to do before then, let us know.

**Comment by justin0022** [comment]
Hi @jennlove-um, I can confirm that this feature is working using UBC's custom Learning Record Store.

**Comment by jennlove-um** [comment]
Thanks, @justin0022!  This is confirmed for inclusion in the release.

**Comment by justin0022** [comment]
No problem :)
