### ISSUE TITLE
Remove the SAML code 

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#1212]
Since Myla initially stated with SAML for authentication and now we moved out of that with LTI. we should totally remove the code associated with it.

**Comment by ssciolla** [comment]
The libraries associated with SAML (https://pypi.org/project/djangosaml2/ and https://pypi.org/project/pysaml2/) are starting to get out of date, with our current versions being one or two major releases behind for each.

**Comment by jonespm** [comment]
Yup, I think we've given people enough time to switch over to LTI. No need to keep this stuff in here.

**Comment by jonespm** [comment]
I did a search for all SAML code. I believe the test would be that it still starts up and launches with and without LTI enabled.

**Comment by ssciolla** [comment]
Yes, may also want to test anything related to authentication, like if the default backend and `ENABLE_BACKEND_LOGIN` still work.

**Comment by zqian** [comment]
verified all SAML related config variables are removed from env*.json file in test server.
