### ISSUE TITLE
Pass user info in link to survey

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1216]
### Describe your problem or feature you'd like added
Explore using parameters to capture more about the survey taker, course, etc.

### Describe the solution you'd like
Include information about the logged in user who is submitting the survey when they submit survey responses.

Information to collect:
- user identifier
- course identifier
- view user is on when they take the survey

This was the information about Qualtrics passing to the Survey https://www.qualtrics.com/support/survey-platform/survey-module/survey-flow/standard-elements/passing-information-through-query-strings/

The initial idea was that we would append fixed parameters generated by MyLA to the URL like 
`?userID=<user>&courseID=<course>&view=<assignment|grades|resources>`

We may also want to look at [Q_EED](https://www.qualtrics.com/support/survey-platform/survey-module/survey-flow/standard-elements/passing-information-through-query-strings/#QEED) encoding as mentioned on this page. 

Would have to see how to embed this into qualtrics and document this and test out how it works. 

* Stretch goal: This could be used to block the user from taking the survey again, or block them from taking it again in a different course. That would be a really nice feature. I'm not sure if this is possible or not. This [document on building a retake link](https://www.qualtrics.com/support/survey-platform/data-and-analysis-module/retake-survey-link/#BuildingARetakeLink) might be relevant.

**Comment by lsloan** [comment]
## Implementation

* Test survey admin: https://umich.ca1.qualtrics.com/Q/EditSection/Blocks?ContextSurveyID=SV_eE8ji6on437uQap
* Test survey link: https://umich.qualtrics.com/jfe/form/SV_eE8ji6on437uQap

**Comment by jennlove-um** [comment]
Testing passes for these data elements: 
- userName
- courseID
- view (note: if student is on the home page, then null is passed)

userID is currently passing only Undefined, which is okay for this release.

I was able to create a new Qualtrics survey, add those embedded data elements, configure MyLA to use the survey, and get data from the survey responses.
