### ISSUE TITLE
Make the survey button more noticeable

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1217]
### Describe your problem or feature you'd like added
Experiment with button and text color to draw users' attention to the survey button.
Get feedback from the research team about the display.

**Comment by jonespm** [comment]
It looks like 
![image](https://user-images.githubusercontent.com/27447/106921169-bffe9100-66d9-11eb-9e17-d548571406cb.png)

**Comment by jonespm** [comment]
Blue on white inverted
![image](https://user-images.githubusercontent.com/27447/106921367-f2a88980-66d9-11eb-9c7c-94b9eb2df3f7.png)

**Comment by lsloan** [comment]
![image](https://user-images.githubusercontent.com/20786/106921567-2388be80-66da-11eb-90b2-540a3dcc0f6f.png)

**Comment by jonespm** [comment]
This is with the darker blue
![image](https://user-images.githubusercontent.com/27447/106921609-2edbea00-66da-11eb-9ca1-87abbb5917d6.png)

**Comment by jonespm** [comment]
Yeah one of my inspirations was to put the button text in the Nyan cat rainbow. But I think we'd need our own colorful mascot rather than using theirs. 
Similar to: https://codepen.io/yongxu/pen/WQbaPG

**Comment by lsloan** [comment]
![nyan](https://user-images.githubusercontent.com/20786/106922089-ad388c00-66da-11eb-932b-642d22b2c8cb.gif)

**Comment by jennlove-um** [comment]
Testing passes with the new color scheme
