### ISSUE TITLE
Write release notes for MyLA 2021.02.01

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1218]
Draft release notes and add to the wiki.  Add a section (or a separate page) for Unizin and others who are deploying the application. Prior versions of release notes have been focused on a user audience only, and Unizin has requested more detailed notes for deployment and configuration.

**Comment by jennlove-um** [comment]
Add a technical section to the release notes

**Comment by zqian** [comment]
I will mark this as done now since the release doc has been attached to the [v2021.02.01 tag](https://github.com/tl-its-umich-edu/my-learning-analytics/releases/tag/2021.02.01) in git.
