### ISSUE TITLE
Code Clearnup: Move nest DB params in settings JSON 

### ISSUE THREAD

**Issue by andrew-gardener** [tl-its-umich-edu/my-learning-analytics#1220]
As suggested in https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1210#discussion_r563970306 refactor the DB params to be object form.

ex:
```
"LRS": {
  "ENGINE": ...,
  "DATABASE": ...,
  . . .
}
```
instead of 
```
"LRS_ENGINE": ...,
"LRS_DATABASE": ..,
...
```

**Comment by pushyamig** [comment]
I have tested this locally and on the Myla Test and it is working as expected. If the configuration are not set properly the site itself won't load
