### ISSUE TITLE
Code Cleanup: remove sample queries for Lecture Capture tool and MiVideo tool events from env_sample.json

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1222]
### Expected behavior (A description of what you expected to happen) : 

env_sample.json should only provide generic Canvas event query

### Describe the bug (Tell us what happens instead of the expected behavior) :

[env_sample.json](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/config/env_sample.json) contains event queries for UMich specific learning tools (Lecture Capture and MiVideo). Those queries should be removed from the env_sample.json. We can put those queries into [institution deployment wiki page](https://github.com/tl-its-umich-edu/my-learning-analytics/wiki/Deploy:-Institution-Architectures) for documentation purpose

**Comment by zqian** [comment]
Remove the video event queries from env_sample.json.  Saved those to [Institution Architecture](https://github.com/tl-its-umich-edu/my-learning-analytics/wiki/Deploy:-Institution-Architectures) page.

**Comment by pushyamig** [comment]
This is just removing the text from env_sample.json and I don't think have any destructive impact. NO test needed on this
