### ISSUE TITLE
Friendlier display names

### ISSUE THREAD

**Issue by andrew-gardener** [tl-its-umich-edu/my-learning-analytics#1226]
### Describe your problem or feature you'd like added
Displaying the account username to logged users may not be the most friendly in all cases. In particular UBC populates usernames with a PUID which is very unfriendly 

### Describe the solution you'd like
Instead, display the first + last name (or initials for avatars). Also ensure that first and last names are always populated on each LTI launch (in case there are changes in the ISS which will eventually filter down on launch)

**Comment by jennlove-um** [comment]
@andrew-gardener For the avatar, could we stick with displaying just the first initial?  That would avoid issues with folks who have multiple names or hyphenated last names.  That regardless of the name, everyone would see their first initial only (or the first letter of their username if no first name is available).

**Comment by jennlove-um** [comment]
Testing passes: First and last name display as the logged in user.  The first initial displays for the avatar. If no first and last name are available in MyLA, then the username displays instead.
