### ISSUE TITLE
Improve Git Info handling when environment variables are not set

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#1236]
I tested by adding a build step to `Dockerfile`: `RUN rm -R /code/.git` and commenting out the volume mapping `.:/code:delegated` under `web` in `docker-compose.yml`. Nothing breaks with these changes, but the resulting Git info block for admins looks kinda silly:
<img width="400" alt="Screen Shot 2021-02-09 at 1 21 35 PM" src="https://user-images.githubusercontent.com/35741256/107409187-e48faa00-6ad9-11eb-9e9e-3152b550e2d2.png">

@zqian, I will propose some changes to the `util` function that does this work (and maybe the template), so that this just gets hidden instead when there's no `.git`. As a fallback, I think it would be okay to release as is, since nothing breaks and it's only an admin feature.

_Originally posted by @ssciolla in https://github.com/tl-its-umich-edu/my-learning-analytics/issues/1206#issuecomment-776143809_

I'm creating this as a separate issue for better tracking purposes. Issue #1206 can be moved to Done.

**Comment by pushyamig** [comment]
I reviewed the PR and it is working fine. If that is suffice then we can mark this a tested!
