### ISSUE TITLE
"Course xxxx does not exist." error when student launches MyLA tool first before instructor does

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1247]
### Describe the bug (Tell us what happens instead of the expected behavior) :

The student will see "Course xxx does not exist." when opens MyLA tool.

### Steps to Reproduce :
1. The instructor enables MyLA tool for the course site, but does NOT click on the MyLA tool link in the course
2. A student clicks on the MyLA tool link first.
3. The students sees "Course xxx does not exist." in browser
4. In the MyLA log file, here is the corresponding error log "Couldn't find user xxxxxx in enrollment info. Enrollment data has not been populated yet."

### Screenshots/Video (If possible, add media to help explain your problem) :

![image](https://user-images.githubusercontent.com/359944/110173427-9023d580-7dcc-11eb-92f3-c5f9b14913c2.png)

**Comment by jonespm** [comment]
I believe the LTI only creates the course in MyLA on an instructor launch. 

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/6a7a9757eebfbecea60eece4ff0294f67800ff32/dashboard/lti_new.py#L252

I'm not sure why this restriction was put in there. It could **probably** create it on a student launch too, just with all of the view options disabled. It wouldn't actually be usable until an instructor comes in so I don't know if there's that much of a difference between giving this error you have here and a course with nothing enabled. The only advantage is it would allow the data to get populated one day faster.

**Comment by jennlove-um** [comment]
Change the error message: This course has not been set up in MyLA.  Contact your instructor for more information.

**Comment by jennlove-um** [comment]
Testcase added to test for this on the release testcase template.
1. Instructor adds MyLA to course navigation.
2. Instructor does NOT click on MyLA to launch LTI and add course to MyLA database
3. Student clicks on MyLA --> updated error message displays.

**Comment by jennlove-um** [comment]
Testing passes in MyLA beta - Updated error messages displays telling the student to contact the instructor.
