### ISSUE TITLE
Add an event log report to the Django admin

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1253]
### Describe your problem or feature you'd like added
As schools start using MyLA where administrators don't have direct access to the database to get information about usage, reports need to be added to the Django admin screens.

One useful report that has been identified is information from the event log.

### Describe the solution you'd like
Add a report on MyLA event log for specified courses. Ideally, admins would be able to select all courses, all courses in a term, or a list of specified courses to run the report.

Users should be able to export that data into a csv file as well.

**Comment by jonespm** [comment]
This could possibly be achieved with the package
https://github.com/django-import-export/django-import-export

However it might need to be added to the eventlog package.

We might also want to have a way to disable deleting and adding logs, but that might also either require customizing this package or extending this locally.
