### ISSUE TITLE
LTI login in /lti/config incorrect when backend enabled

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1262]
### Expected behavior (A description of what you expected to happen) : 
The LTI login link in the config should always be `/lti/login` but there's cases where it will be `/accounts/login/`

### Describe the bug (Tell us what happens instead of the expected behavior) :
The LTI login in the config should always be `/lti/login/`, instead it if you have `"ENABLE_BACKEND_LOGIN": true,` it will come up as `/accounts/login/`.

This looks like it's because the **name** for `/accounts/login/` and `/lti/login` are both "login" so when it does a reverse it gets the wrong one. We need to have a separate name and also update the name in `lti_new.py`.

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/f288ad3c77c3911f1831bf484a2ff275194e768b/dashboard/urls.py#L95

### Steps to Reproduce (Will require a dev) :
1. Configure MyLA for LTI based on the instructions
2. Check the URL /lti/config. The `oidc_initiation_url` should always be `/lti/login`. However it can sometimes be `/accounts/login`.
3. Switch the setting in the config ENABLE_BACKEND_LOGIN to both true and false and test that it is always `/lti/login` in both cases

The problem is this comes up as `/accounts/login/` it doesn't work and it's a little confusing to debug.

**Comment by pushyamig** [comment]
@jonespm is this my related to this issue  issues https://github.com/tl-its-umich-edu/my-learning-analytics/issues/1261 or different

**Comment by jonespm** [comment]
I'm pretty sure this is a different issue as this none of the Openshift instances are configured like this. This is more likely to happen in localhost or **possibly** in a setup that another client does if they use the new LTI configuration method.
