### ISSUE TITLE
Rewrite existing cron queries to get data from UDP and validate data matches UDW data queries

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1267]
From #489 
Rewrite each of the queries and ensure the data retrieved is identical for a select group of courses. 

Note: The BigQuery can be excluded as it won't be needed to change

**Comment by jonespm** [comment]
@zqian mentioned that Kyle already took a pass at rewriting these queries. The queries are here. https://gitlab.com/unizin-community/data-analysis/udp-workspace/udp-myla.

This is 9 months old but probably would help whoever is doing this work get started.

**Comment by zqian** [comment]
Please refer to [issue-1266](https://github.com/tl-its-umich-edu/my-learning-analytics/issues/1266) for implementation.
