### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by huntr-helper** [tl-its-umich-edu/my-learning-analytics#1269]
👋 Hello, we've received a report for a potential medium severity security issue in your repository.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-tl-its-umich-edu/my-learning-analytics** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by jonespm** [comment]
Looks like this is the solution for this
https://stackoverflow.com/a/59758479/3708872

Remove it from the Dockerfile and use this pattern in the settings

**Comment by JamieSlome** [comment]
@jonespm - I have re-marked as valid on the advisory as the previous attempt failed - apologies for this.

Are you also able to confirm the fix on the advisory page?

**Comment by zqian** [comment]
fix has been confirmed by Matt in huntr
