### ISSUE TITLE
provide better error message when blocked by Brave browser shield settings

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1270]
### Expected behavior (A description of what you expected to happen) : 

When one uses Brave browser with the "Cross-site cookies blocked" shield setting on by default, MyLA LTI tool cannot be opened. It shows "Server Error(500)" in browser and the following error in log file:
```
  File "/usr/local/lib/python3.8/site-packages/pylti1p3/message_launch.py", line 631, in set_launch_data_storage
    raise LtiException("Missing %s cookie" % session_cookie_name)
pylti1p3.exception.LtiException: Missing session-id cookie
```

### Describe the bug (Tell us what happens instead of the expected behavior) :

We call "enable_check_cookies" in our code. But that work is done in the pylti1p3 library. It looks like we can configure the messages here at least too.

dashboard/lti_new.py:274
`    return oidc_login.enable_check_cookies().redirect(target_link_uri)
`

### Steps to Reproduce :
1. Open Brave browser with default setting on
2. Launch MyLA LTI tool from one Canvas course site
3. User sees "Server Error(500)" in the browser window.
4. click on the shields icon, turn off shield or update settings to "All cookies allowed". MyLA tool loads again.

### Screenshots/Video (If possible, add media to help explain your problem) :

![image](https://user-images.githubusercontent.com/359944/120390429-b1c52800-c2fb-11eb-96bd-b0260141c2fb.png)

**Comment by jennlove-um** [comment]
I'm closing this issue since Canvas does not support the Brave browser.
