### ISSUE TITLE
Upgrade backend dependencies, including Django to 3.2

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1286]
Upgrade Django to 3.2

**Comment by ssciolla** [comment]
Notes from Django 3.2 update (including Django related dependencies):
- Possible issue with `django-cron`: https://github.com/Tivix/django-cron/issues/169

**Comment by jonespm** [comment]
I've wanted to remove this module for awhile #664 but haven't gotten around to it. I don't think anyone is running it as a cron and it's not very intuitive. We'd probably want to keep the model for keeping track of the runs though, but it these jobs scripts could be run more directly. If this is a blocker we can work on that issue.

**Comment by ssciolla** [comment]
@jonespm, I'm seeing these Django warnings, some of which already existed I think. Should we handle them as part of this issue or separately?

```
student_dashboard        | dashboard.AssignmentWeightConsideration.consider_weight: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
student_dashboard        | 	HINT: Use BooleanField(null=True) instead.
student_dashboard        | database.Constance: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
student_dashboard        | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
student_dashboard        | django_cron.CronJobLog: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
student_dashboard        | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
student_dashboard        | eventlog.Log: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
student_dashboard        | 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
```

**Comment by jonespm** [comment]
For the Autofield issues we should just put in settings.py

`DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'`

As this is what we've been using. We could wait till Django 4.0 on the first one but it looks like a minor fix.

**Comment by zqian** [comment]
Verified the above warning message is not in log file, with the suggested setting in place: DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
