### ISSUE TITLE
Webpack doesn't seem to be live reloading the frontend anymore on OSX with certain options

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1293]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 
When developing and changing the code we used to see changes in the frontend rebuilding. This is the point of webpack_watcher. However it doesn't look like this happens in OSX Docker if you have the option Use gRPC FUSE unchecked.

<img src=https://user-images.githubusercontent.com/27447/128252331-f23a5db9-9cc1-46e8-89e5-3560e6a97790.png width=50%>

Unchecking this can give a disk performance boost when developing. 

### Describe the bug (Tell us what happens instead of the expected behavior) :
It seems like the fix for this is to both switch the watchOptions poll to true and also switch `delegated` to `cached` for the mount options.

Note the `delegated` and `cached` are not used on Windows and don't appear to be used in OSX if the Docker option _"Use gRPC FUSE for file sharing"_ is checked.

### Steps to Reproduce :
1. On OSX Docker General have the option Use "gRPC FUSE" unchecked and Apply/Restart.
2. Start up MyLA for development
2. Modify some frontend javascript code
3. The changes should be updated. If you look at the `docker logs webpack_watcher` it should also show changes compiled.

This will only affect development

**Comment by zqian** [comment]
Verified the frontend rebuilding of webpack-watcher, with the above mentioned settings.
