### ISSUE TITLE
Console error about Material-UI being renamed

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1295]
### Describe the bug (Tell us what happens instead of the expected behavior) :

Saw this error message in the browser console when using MyLA recently. Should fix this so it goes away and doesn't eventually break on us.
```
createTheme.js:94 Material-UI: the createMuiTheme function was renamed to createTheme.

You should use `import { createTheme } from '@material-ui/core/styles'`

```

### Steps to Reproduce :
1. Go to any page
2. Look for errors in the browser console

**Comment by jennlove-um** [comment]
Testing passes - I am unable to find that error in the console messages.
