### ISSUE TITLE
Console errors in Resources Accessed related to d3 `preventDefault` method

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#1298]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 

We should not be seeing excessive console errors in the Resource Accessed view.

### Describe the bug (Tell us what happens instead of the expected behavior) :

When you scroll around in the Resources Accessed view, a lot of repetitive errors are logged to the console with the message "Unable to preventDefault inside passive event listener invocation." We should look at whether this line is necessary, or determine the root cause and another solution.
https://github.com/tl-its-umich-edu/my-learning-analytics/blob/f8ac513925ed13bd4eaad8bad7be28a57b91341c/assets/src/components/d3/createResourceAccessChart.js#L253-L257

### Steps to Reproduce :
1. Go to the Resources Accessed View.
2. Scroll a bit.
3. Look at the console.

**Comment by jennlove-um** [comment]
Testing passes - the errors no longer display when I scroll up and down on the Resources Accessed page.
