### ISSUE TITLE
Remove unused resolve_courses method in GraphQL query

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1301]
### Describe the bug (Tell us what happens instead of the expected behavior) :

The method `resolvecourses` in query.py doesn't appear to be ever used and is also flagged with an SQL injection vulnerability. This could be fixed by passing a parameter to the raw SQL but since it's not used there's no way to test it. 

So it seems better just to remove it. The ideal would be if this was rewritten either using `Course.objects.extra` pattern or adding a `ForeignKey` so that the raw method wasn't even needed.

The relevant graphql that exists only queries a single course

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/assets/src/hooks/useAssignmentData.js

**Comment by jennlove-um** [comment]
Testing passes in that there were no errors in regression for any of the views.
