### ISSUE TITLE
Disable editing, removing and adding event logs and cron logs

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1325]
### Expected behavior (A description of what you expected to happen) : 

In Django Admin, there shouldn't be any way to remove logs from this interface. That's more of a system operator level and these logs should be considered immutable.

**Comment by jennlove-um** [comment]
This passes in Test.

Cron job logs & Logs: Admins can view and export log files.  They cannot add or delete logs.
