### ISSUE TITLE
Improve verify_course_ids to only consider courses with local data

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1327]
When validating the courses, we should also check to see if the courses have any data in other tables because we consider it invalid.

There are cases where a course is too new and we haven't even pulled down data for it yet.

I think for an easier solution we could also just check the `data_last_updated` column and check to see if that has a value. It would still be an "invalid course" but one that can just be skipped if it was never processed and has no data.

This method is intended to protect removing data in the case that the data warehouse has a problem.

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/719a29c69ea1c690026170fb5b347de722ff644a/dashboard/cron.py#L121

**Comment by ssciolla** [comment]
I remembered this other issue that is related, but with some data model changes and LTI, the picture has certainly changed a bit now: https://github.com/tl-its-umich-edu/my-learning-analytics/issues/383

**Comment by jonespm** [comment]
To test this

* Launch the course from an actual course that would have data in the database
* Either launch it from a brand new course that doesn't yet have data, or just manually add a Course directly to the admin with an invalid id (like 999999999)
* Try to run the cron. It should only process the valid course and the last updated value on the other course shouldn't have been updated.

**Comment by jennlove-um** [comment]
Tested in beta: 
1. Course that has data in the UDW:  Data added and last updated date updated.
2. Course that does not have data in UDW: No data, no error, and last updated date is still null.

Testing passes in beta.

**Comment by jennlove-um** [comment]
Tested in beta:

1. Course that has data in the UDW: Data added and last updated date updated.
2. Course that does not have data in UDW: No data, no error, and last updated date is still null.

**Comment by jennlove-um** [comment]
Tested in beta:

Course that has data in the UDW: Data added and last updated date updated.
Course that does not have data in UDW: No data, no error, and last updated date is still null.
