### ISSUE TITLE
add the ability to skip certain data frame column(s) for comparison in the UDW/UDP validation script 

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1343]
### Describe the bug (Tell us what happens instead of the expected behavior) :

As of now, the [UDW<->UDP validation script](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/scripts/data_validation/validate_udw_vs_udp.py) is doing full pandas data frame comparison between UDW and UDP query results. It is desirable to add the ability to skip certain data frame columns if needed for debugging purposes.

Matt suggested a [good article]( https://towardsdatascience.com/how-to-show-all-columns-rows-of-a-pandas-dataframe-c49d4507fcf) about how to get pandas to avoid truncating output:

Should probably make those changes to the script too to aid debugging.
pd.set_option("max_rows", None)
pd.set_option("max_colwidth", None)
pd.set_option('max_columns', None)

**Comment by jennlove-um** [comment]
No longer needed.
