### ISSUE TITLE
Avoid pulling some unused personal data from the cron

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1344]
Thank you for contributing to this project!

### Describe your problem or feature you'd like added

Since we've switched over to LTI, Canvas provides some data that we were previously pulling from the UDW that's slightly different pulling from the UDP and unnecessary now. This includes things like name and email address. But it might also include UMID as person_sourcedid. 

Some of this was retained because of SAML but SAML was removed in the 2021.03.01 release. We should see what really needs to be pulled from the database and clean up unused columns and queries. 

It's good practice to also only store the data completely necessary to run the application.

**Comment by jennlove-um** [comment]
Testing passes in beta

**Comment by jonespm** [comment]
This is the rollback if needed for this issue

```
ALTER TABLE `user` ADD name varchar(255) NULL after user_id;
DELETE FROM django_migrations WHERE name='0024_remove_user_name';
```

**Comment by jennlove-um** [comment]
Testing passes in test.
