### ISSUE TITLE
Duplicated resource access records returned when user is enrolled in multiple courses

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1345]
### Describe the bug (Tell us what happens instead of the expected behavior) :
The resource access count for individual users are duplicated, if the user is enrolled in multiple courses 

### Steps to Reproduce :
1. choose a user enrolled in multiple MyLA courses 
2. go to the Resource Access view, mouse-over to the resource access chart, and read the line of "You access this resource X times."
3. the number is proportional to the user enrollment of MyLA course count

**Comment by jonespm** [comment]
This is related to #1276 where it seems like it wasn't fully completed and there was still a regression.

**Comment by jennlove-um** [comment]
testing passes in myla-test.  Counts in the UI match data in the database for students who have only one class with MyLA as well as for students who have multiple courses with MyLA.
