### ISSUE TITLE
Improve resources_access query to replace sis_name

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1349]
In the resources_access query, we should probably be either using the Canvas ID or the internal ID on the user table (which is a combination of course_id and user_id) rather than referencing sis_name. This feels like it's somewhat a holdover from when we had ID's from Shibboleth.

There might be more places where this exists.

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/f4a4bdcdb1821adb09130486ac85792a2f576548/dashboard/views.py#L368

**Comment by jennlove-um** [comment]
This relies on #489 being done first.

**Comment by jennlove-um** [comment]
This change cannot be made because Kaltura uses this data - #1443.  This could be fixed at a later date if Kaltura changes the data they send in events data.
