### ISSUE TITLE
Remove or provide alternative for person_sourcedid to pass certification

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1353]
[http://www.imsglobal.org/spec/lti/v1p3/#learning-information-services-lis-claim](https://purl.imsglobal.org/spec/lti/claim/lis) is an optional claim value that isn't supported by the certification. There isn't any intention in supporting this optional claim.

We need to either remove it and get this value from a different source (UDW), remove it if we don't need it at all, or be able to also optionally pass it as part of a custom claim parameter.

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/f4a4bdcdb1821adb09130486ac85792a2f576548/dashboard/lti_new.py#L230

**Comment by jonespm** [comment]
Maybe if we needed this it would be better to just use the [variable substitution](https://canvas.instructure.com/doc/api/file.tools_variable_substitutions.html) of Person.sourcedId.

Though I'm still not sure if this value is even needed/used by the app yet either.

**Comment by zqian** [comment]
I do not think the user_sis_id is used in MyLA. We could remove that field from the data model.

**Comment by jonespm** [comment]
Yeah, it was added in #993 but I don't even see where it was used in that PR. I was just looking over the logic of this method again. 

We have **sis_id** in a few places in the code. I don't remember if that's legacy or useful.
