### ISSUE TITLE
Remove .git from git https remote

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1358]
It looks like when you clone (or add a remote) git is adding a .git at the end. I don't think it was always like this and not sure when it happened.

https://github.com/tl-its-umich-edu/my-learning-analytics.git

In any case our code should handle removing this. Currently it will only remove it if it's a ssh source, not https. 

It'll likely be fixed here and just replace .git everywhere.

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/474de8d4eb230587f826ad7d72f4a0ec80dbf687/dashboard/common/utils.py#L18

To reproduce just clone with the current remote that has a .git extension and https scheme. 

_Originally posted by @saputran in https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1357#discussion_r830399788_

**Comment by niurcaq** [comment]
Hey, I'm an EECS 481 student (niurcaq@umich.edu) that is willing to solve this issue! My partner (ltheresea@umich.edu) and I will try to fix this issue. I tried to recreate the issue and was able to in https, however I was also able to recreate it in ssh as well. So, I'm not sure if I'm just not recreating the issue correctly or this is problem for ssh and https.

**Comment by jonespm** [comment]
Yeah, I don't 100% remember much about this issue. It looks like my feedback was just as you say that we should be doing a replacement/cleanup no matter what the format is, so probably just need to refactor out the `.replace(".git", "")` from the if statement and do it for everything.

**Comment by zqian** [comment]
Tested successfully with the four test cases specified in [PR #1571](https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1571)
