### ISSUE TITLE
change the DJANGO_DEBUG setting

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1359]
### Describe the bug (Tell us what happens instead of the expected behavior) :
The config/env_sample.hjson contains DJANGO_DEBUG setting as:

`
"DJANGO_DEBUG": true,
`

Need to change the default setting as the following:

`
"DJANGO_DEBUG": false,
`

**Comment by jonespm** [comment]
This looks good and I've tested the default is false now.
