### ISSUE TITLE
navigation on home page

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#136]
We need a something on the home page for a user so if they launch dashboard without a link or go back to the main page they'll have thing to do. I left this hardcoded at the moment. Maybe we want to give them access to all of their sites, and maybe users with no data should have any access. This is for another ticket too.

**Comment by jonespm** [comment]
Currently if the user is in one course /courses/ will show them that course. The homepage shows them nothing. I think this is more of a phase 2 idea and we'll just want launches from Canvas for the Pilot.

**Comment by justin0022** [comment]
I believe with the new React front-end this issue is resolved.
