### ISSUE TITLE
Update `d3`

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#1367]
Upgrading `d3` is a significant piece still to be done, and which I think we'll tackle separately. We're behind two major releases and the `d3-tip` companion library seems to have been archived on GitHub (https://github.com/caged/d3-tip). I found a migration guide for version 6, but no equivalent yet for version 7: https://observablehq.com/@d3/d3v6-migration-guide

_Originally posted by @ssciolla in https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1363#discussion_r844336733_

As of now (4/8/22), I don't think `d3` version 5 poses any vulnerabilities, but updating it is something we'll have to face at some point.

**Comment by jennlove-um** [comment]
Focus testing on Resources Accessed, Grade Distribution, and old Assignment Planning to verify nothing breaks.

**Comment by jennlove-um** [comment]
Testing passes in beta.  Views are loading and filters are working with no errors.
