### ISSUE TITLE
Update Google Analytics to support GA4 (By July 2023)

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1371]
I saw a notification today that Google analytics team is sunsetting current version Universal Analytics and it is replacing with [Google analytics 4](https://support.google.com/analytics/answer/10089681?utm_campaign=2022-q1-gbl-all-gafree&utm_source=google-growth&utm_medium=email&utm_content=ga-sunset-msa-ua-only-admin). I think we are using a react-ga library which is still support [Universal analytics](https://github.com/react-ga/react-ga).

At some point i believe this library will update as well. I don't know what is difference between existing and new one. It looks like we need to configure this GA4 from our GA console as well. I think there may be some work from that in future

Here is the the current possible replacement package: 
 https://github.com/PriceRunner/react-ga4

_Originally posted by @pushyamig in https://github.com/tl-its-umich-edu/my-learning-analytics/issues/1363#issuecomment-1104286765_

**Comment by jennlove-um** [comment]
This looks good in test - I like the new analytics reports!
