### ISSUE TITLE
Resources Accessed does not load when the course contains files with a semicolon in the filename

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1378]
### Expected behavior (A description of what you expected to happen) : 
The Resources Accessed should display resources in the course that have non-alphanumeric characters in the file name.

### Describe the bug (Tell us what happens instead of the expected behavior) :
When a file name has a semicolon in it, the Resources Accessed bar chart does not load.

### Steps to Reproduce :
1.  Add MyLA to a course that has at least one file with a semicolon in the file name.
2. Click on Resources Accessed
3. The bar chart will not load.

### Screenshots/Video (If possible, add media to help explain your problem) :
![MyLA_RA_Error_Loading_Chart](https://user-images.githubusercontent.com/39634416/166300488-5b8bad87-16fa-400b-b639-13065e59a9c4.png)

**Comment by jonespm** [comment]
Originally introduced in #72 and #73
