### ISSUE TITLE
Add a database table to store the courses that we currently support

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#138]
I was thinking of just using a database table that could be maintained through the django admin kind of like
https://djangobook.com/adding-models-to-django-admin/

Where we could have like supported_courses.

In that table we could put all of the course ids we want to allow onto the dashboard. Then the cron process would load them all in. Currently this is hardcoded as a CSV CANVAS_COURSE_IDS(but it really only contains one value)

**Comment by jonespm** [comment]
This will improve on #190

**Comment by zqian** [comment]
Is this still necessary based on the current cron workflow, i.e. read the supported course ids from config file, then populate the course table?

**Comment by jonespm** [comment]
It would make it so we don't have to restart to update course id's. Seems
more like a nice to have or phase 2 when the courses we support expands.

**Comment by jonespm** [comment]
From @zqian

It turns out I need to to the following steps:
1. insert course record into course table;
2. inert course record into course_view_option table;
3. add those two course ids into the configuration variable CANVAS_COURSE_IDS in the dev pod;

**Comment by jonespm** [comment]
@jennlove-um This is the current WIP

A UI that allows adding terms/courses and course information on one page.

![image](https://user-images.githubusercontent.com/27447/48737609-79b5d800-ec1c-11e8-8d20-cfbaba8e2936.png)

Then another page where you can modify all information about a course
![image](https://user-images.githubusercontent.com/27447/48737657-a1a53b80-ec1c-11e8-8b0e-653d5474eb45.png)

It *might* be possible to get it all onto one page. This is just a 'first pass'. Any courses in this UI will be picked up by the loader. Any courses without options set will not have any access until set.
