### ISSUE TITLE
Change the way instructor is identified during the LTI launch to avoid a misleading log message

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1381]
During the LTI certification, there were a few tests where they were sending short, unknown, or missing roles. However, the app printed that they "must be admin".

There's nothing that would indicate that they must be admin if they're not in the roles available. We should remove this message and maybe even log it as an ERROR.

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/2008deada70ac494f07b71110b08a51e03b5cacd/dashboard/lti_new.py#L194

The Logic of the instructor check is modified for clarity and this avoids the flagged logged message

--------------------------------------
Test Plan:
1. launch MyLA from a new course that doesn't have an entry in MyLA DB with different roles
   1. Launch the tool as `TA in the course who is also an instructor in one of the course sections`. He should not enable 
    MyLA for the course (start the data extraction )
   4. Launch the tool as `TA only in the course. He should not enable MyLA for the course (start the data extraction )
   5. Launch the tool with an instructor in the course. He is the person who can enable MyLA for the course
   6. Launch the tool with an MyLA Admin, i.e is_staff role enabled in the `auth_user` table. He is the person who can 
       enable MyLA for the course
   8. Launch the tool as Canvas Admin. He should not enable MyLA for the course (start the data extraction )
2. Basically only instructor and MyLA admin (who has Django admin access) should be enabling the MyLA in the course.

This will eliminate the unnecessary log message that certification flagged.

**Comment by jennlove-um** [comment]
This is not something that will happen when users log in to MyLA via Canvas.  This should still be reviewed and fixed as part of LTI certification.

**Comment by jennlove-um** [comment]
Tested in beta: 
1. Launch the tool as TA in the course who is also an instructor in one of the course sections. He should not enable
MyLA for the course (start the data extraction ) - PASSED
2. Launch the tool as `TA only in the course. He should not enable MyLA for the course (start the data extraction ) - PASSED
3. Launch the tool with an instructor in the course. He is the person who can enable MyLA for the course - PASSED
4. Launch the tool with an MyLA Admin, i.e is_staff role enabled in the auth_user table. He is the person who can
enable MyLA for the course - PASSED
5. Launch the tool as Canvas Admin. He should not enable MyLA for the course (start the data extraction ) - PASSED

**Comment by pushyamig** [comment]
I am moving this to done, for some reason this is moved to Review/QA- Dev
