### ISSUE TITLE
Regex returning wrong ID for lecture capture

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1384]
### Expected behavior (A description of what you expected to happen) : 
The ID for lecture capture in the RESOURCE table is expected to be just a short ID but instead contains the full URL

object.id has a format like this:

`https://leccap.engin.umich.edu/leccap/viewer/r/ABCDEFG`

But we're appending the intro part to access this.

### Describe the bug (Tell us what happens instead of the expected behavior) :
It looks like the change from regular to expanded table changed the query that pulls the ID from 
`"CAST(SUBSTR(JSON_EXTRACT_SCALAR(event, '$.object.id'), 48) AS STRING) AS resource_id, ",
`to
`"REGEXP_EXTRACT(object.id, r'.*:(.*)') AS resource_id, ",`

This is resulting in the wrong ID for lecture capture.

It looks like this should be 
`REGEXP_EXTRACT(object.id, r'([^/]+$)')`

Which will extract the ID after the last slash.

### Steps to Reproduce :
1. Go to a course with lecture capture
2. Try to launch a file with a link

**Comment by zqian** [comment]
- Updated the configuration values for cron.hjson file on [this MyLA wiki page](https://github.com/tl-its-umich-edu/my-learning-analytics/wiki/Deploy:-Institution-Architectures).
- Updated the settings for both MyLA test and beta servers
