### ISSUE TITLE
jwks/LTIException usage cleanup 

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1387]
_Originally posted in tl-its-umich-edu/my-learning-analytics#1385…_
_N.B.: The following comments are in a resolved thread.  Click the dates on the comments below to show the resolved thread and go directly to the comment._

@zqian [on Jun 17](https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1385#discussion_r900419103)
> LTIException is used only for generate_jwks() and get_jwks().
> 
> Since https://github.com/tl-its-umich-edu/my-learning-analytics/issues/1223 , MyLA config uses the generic canvas instance urls, and jwks-related instructions have been removed from MyLA wiki, I wonder whether we should remove the above two function and hence the LTIException definition after all.

@jonespm [on Jun 22](https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1385#discussion_r904210814)
> Right, these are only used when using the LTI services (like grading service) which we aren't currently using and may never use for MyLA. So these could be just cleaned up.
> 
> I was also wondering if we could use [LTIServiceException](https://github.com/dmitry-viskov/pylti1.3/blob/7474685aecc35d528b944caf05b28ea66ac6d204/pylti1p3/exception.py#L16) from the library instead of our own exception here. But I wasn't sure the type of the config variable.
> 
> This seems fine now, maybe create another issue to remove those jwks methods.

<a name="scope_review"></a>
@jonespm [on Jun 22](https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1385#discussion_r904215872)
> With that jwks cleanup we should also review the scopes we request. MyLA doesn't need most of those that we are requesting.
> 
> [https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/assets/config/lti_config_template.json](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/assets/config/lti_config_template.json?rgh-link-date=2022-06-22T20%3A51%3A10Z)

**Comment by lsloan** [comment]
@jonespm suggests [above](https://github.com/tl-its-umich-edu/my-learning-analytics/issues/1387#user-content-scope_review) that we could limit the scopes required by MyLA.  Does anyone have an idea which scopes are needed?  The current list:

```json
  "scopes": [
    "https://purl.imsglobal.org/spec/lti-ags/scope/lineitem",
    "https://purl.imsglobal.org/spec/lti-ags/scope/lineitem.readonly",
    "https://purl.imsglobal.org/spec/lti-ags/scope/result.readonly",
    "https://purl.imsglobal.org/spec/lti-ags/scope/score",
    "https://purl.imsglobal.org/spec/lti-nrps/scope/contextmembership.readonly",
    "https://canvas.instructure.com/lti/public_jwk/scope/update",
    "https://canvas.instructure.com/lti/account_lookup/scope/show",
    "https://canvas.instructure.com/lti/data_services/scope/create",
    "https://canvas.instructure.com/lti/feature_flags/scope/show",
    "https://canvas.instructure.com/lti/data_services/scope/list_event_types",
    "https://canvas.instructure.com/lti/data_services/scope/destroy",
    "https://canvas.instructure.com/lti/data_services/scope/list",
    "https://canvas.instructure.com/lti/data_services/scope/update",
    "https://canvas.instructure.com/lti/data_services/scope/show"
  ],
```
