### ISSUE TITLE
Lower level or remove unnecessary logging

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1388]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Describe the bug (Tell us what happens instead of the expected behavior) :
In the logs there are many unnecessary and not useful messages printed to the INFO log level

These include:
```
[2022-06-29 09:59:58 -0400] [INFO] [utils.py:70] course_id from path: #######
[2022-06-29 09:58:40 -0400] [INFO] [views.py:549] user XXXXX in course XXXXXXXX don't have any defaults values set type resource
[2022-06-29 09:58:46 -0400] [INFO] [views.py:289] course_id XXXXX total student=XX
[2022-06-29 10:00:16 -0400] [INFO] [db_util.py:146] User XXXXXXX is enrolled in these courses:
[2022-06-29 10:03:46 -0400] [INFO] [views.py:538] get_user_default_selection
[2022-06-29 10:03:46 -0400] [INFO] [views.py:776] get_course_date_start
[2022-06-29 10:05:05 -0400] [INFO] [db_util.py:116] get_user_courses_info
[2022-06-29 12:18:01 -0400] [INFO] [lti_new.py:103] LTI configuration valid.
[2022-06-29 09:42:31 -0400] [INFO] [views.py:167] update_course_info
```

These all _seem_ like debug messages to me. Add any others to this list. This is somewhat related to cleaning up #1381 and also #228

You can avoid changing cron.py as we are mostly only concerned about the webapp.

**Comment by jxiao21** [comment]
There are multiple functions with a line that appears to print to the INFO level that the function was called like this: 
`def weight_consideration(self):
        # load the assignment weight consider information with in a course. Some assignments don't have weight consideration
        # the result of it return boolean indicating weight is considered in table calculation or not
        status = ""

        logger.info("weight_consideration()")

        # delete all records in assignment_weight_consideration table
        status += self.execute_myla_delete_query("DELETE FROM assignment_weight_consideration")

        # loop through multiple course ids
        status += self.util_function(
            self.queries['assignment_weight'],
            'assignment_weight_consideration',
            bigquery.QueryJobConfig(query_parameters=[
                bigquery.ArrayQueryParameter('course_ids', 'STRING', self.valid_locked_course_ids,),
            ]),
            'weight')

        logger.debug(status + "\n\n")

        return status`

In this case, it's the `logger.info("weight_consideration()")`. Are these lines like this by design, or should these statements be moved to the debug level?

**Comment by jxiao21** [comment]
> There are multiple functions with a line that appears to print to the INFO level that the function was called like this: `def weight_consideration(self): # load the assignment weight consider information with in a course. Some assignments don't have weight consideration # the result of it return boolean indicating weight is considered in table calculation or not status = ""
> 
> ```
>     logger.info("weight_consideration()")
> 
>     # delete all records in assignment_weight_consideration table
>     status += self.execute_myla_delete_query("DELETE FROM assignment_weight_consideration")
> 
>     # loop through multiple course ids
>     status += self.util_function(
>         self.queries['assignment_weight'],
>         'assignment_weight_consideration',
>         bigquery.QueryJobConfig(query_parameters=[
>             bigquery.ArrayQueryParameter('course_ids', 'STRING', self.valid_locked_course_ids,),
>         ]),
>         'weight')
> 
>     logger.debug(status + "\n\n")
> 
>     return status`
> ```
> 
> In this case, it's the `logger.info("weight_consideration()")`. Are these lines like this by design, or should these statements be moved to the debug level?



> There are multiple functions with a line that appears to print to the INFO level that the function was called like this: `def weight_consideration(self): # load the assignment weight consider information with in a course. Some assignments don't have weight consideration # the result of it return boolean indicating weight is considered in table calculation or not status = ""
> 
> ```
>     logger.info("weight_consideration()")
> 
>     # delete all records in assignment_weight_consideration table
>     status += self.execute_myla_delete_query("DELETE FROM assignment_weight_consideration")
> 
>     # loop through multiple course ids
>     status += self.util_function(
>         self.queries['assignment_weight'],
>         'assignment_weight_consideration',
>         bigquery.QueryJobConfig(query_parameters=[
>             bigquery.ArrayQueryParameter('course_ids', 'STRING', self.valid_locked_course_ids,),
>         ]),
>         'weight')
> 
>     logger.debug(status + "\n\n")
> 
>     return status`
> ```
> 
> In this case, it's the `logger.info("weight_consideration()")`. Are these lines like this by design, or should these statements be moved to the debug level?

This is located in the weight_consideration function in cron.py

**Comment by zqian** [comment]
Verified the INFO log messages have been reduced, by comparing MyLA test log with MyLA prod log file.
