### ISSUE TITLE
Update Django Cron to 0.6.0

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1400]
Django Cron finally had a new release after 4 years as 0.6.0 fixing a few bugs that we've had. We should update to support that version. 

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/b0d05c166f1ee394a758d7e52fdcd95e14da2b4f/requirements.txt#L7

**Comment by ssciolla** [comment]
I can QA this Monday.

**Comment by ssciolla** [comment]
I'm not seeing any issues related to this. Moving to Done.
