### ISSUE TITLE
Loophole does not work with Django Admin and returns incorrect URLs in /lti/config

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1402]
### Describe the bug (Tell us what happens instead of the expected behavior) :

If a local developer is using [loophole.site](https://loophole.cloud/) instead of ngrok for LTI testing it doesn't work correctly. This is because loophole sends the header USE_X_FORWARDED_HOST and MyLA currently doesn't use this.

### Steps to Reproduce :
1. Use Loophole in development intead of ngrok

You can launch loophole with a command like 
`loophole http 5001 --hostname myla-test-domain`

After you go through the steps to install it and add it to your path.

2. Go through the steps to setup LTI. You'll notice that the /lti/config URL in the steps has 127.0.0.1. 
3. Also saving anything in Django Admin doesn't work. 

Everything should just work the same was as with NGrok.

It's possible to configure this you may also have to add **loophole.site** to `ALLOWED_HOSTS, DEFAULT_SRC and CSRF_TRUSTED_ORIGINS.`

**Comment by jonespm** [comment]
Test Plan

* This is False by default so the false test plan is a regression test to ensure everything is working. This is the standard default so no change should be noticed.

* If this is set to true, it may improve some things for proxies like Loophole if `loophole.site` is added to `CSRF_TRUSTED_ORIGINS` with this enabled. I can expand that test plan but it's not necessary to test for this release.

**Comment by pushyamig** [comment]
Test passes and is working for me based on setting certain TRUSTED_ORIGINS in my local
