### ISSUE TITLE
Clean up redundant and confusing names in models to improve admin interface

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1420]
Two issues were noticed in the models.py file that could be improved.

1. If the verbose_name matches the name of the field just remove the verbose name as it automatically matches. This follows Django's Less Code and DRY principles.

2. If the verbose name could be improved we should do that.

3. Additionally we don't use [help_text](https://docs.djangoproject.com/en/4.1/ref/models/fields/#help-text) to provide even more additional text on forms. It's possible some of these fields could have useful text. This should be figured out with @jennlove-um what these might be.

This appears under fields on the form like 
![image](https://user-images.githubusercontent.com/27447/188002541-6cda7c77-1949-4b9e-81f2-a9b87a4bce3d.png)

I'm thinking we might want to have text like 

- Name, Start/End Date: "This field will be automatically populated by cron to match Canvas but can be adjusted if desired"
- Data last updated: "This is the last time the cron was run and can be reset on the main courses page with the dropdown"

There's probably others., especially like the course view option area. 

_Originally posted by @jonespm in https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1410#discussion_r961051442_

**Comment by zqian** [comment]
Verified on MyLA Test server for the improved labels in both Academic Term and Course forms.
