### ISSUE TITLE
Chrome shows error message before MyLA cron job is run for course

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1427]
### Describe the bug (Tell us what happens instead of the expected behavior) :
This seems to be a problem for Chrome only: 

After enable MyLA tool in site, and before the cron run, the user sees `Something went wrong; please try again later.`

The user should see the following msg instead: 

`Course {courseId} has not been set up in MyLA. Contact your instructor, who can enable the visualizations by clicking on MyLA in the course navigation.`

### Steps to Reproduce :
1. After enable MyLA tool in site
2. Before the cron run, the user access the MyLA tool
3. User sees `Something went wrong; please try again later.`

**Comment by jennlove-um** [comment]
I am unable to replicate the issue in testing.  I'm closing this issue.
