### ISSUE TITLE
May need to make America/Detroit in cron config configurable

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1432]
Noticed this when I was reviewing the cron updates. I'm not sure if this is the same for other schools that might be hosted but this value that's used in the cron config should _probably_ come from the django.conf `settings.TIME_ZONE` or a probably a new value to indicate the time zone in the database? There's 2 usages of this. 

This looks like it was in the previous UDW config so it may not be an issue, or it might just not be one reported yet. 

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/2fc6c4e804aab4ed56e37f411b32d275561c5c9f/config/cron_udp.hjson#L246

**Comment by cosimps** [comment]
Unizin supports making this configurable.

Currently, the Unizin hosted MyLA instances, both the django app and the cron, run with the `America/Detroit` timezone based on:

- [https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/dockerfiles/Dockerfile#L75-L76](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/dockerfiles/Dockerfile#L75-L76)
- setting of the `TZ` variable in our configs (`ENV_FILE`)

Unizin would prefer being able to set this via a config variable as it runs all of its hosted MyLA instances in the same cloud region that defaults the UTC time, so inheriting the timezone via a default compute method would not be ideal.

It appears as though the timezone setting is [already configurable](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/dashboard/settings.py#L273) via both the `TZ` and `TIME_ZONE` variables.

It would be ideal for Unizin if the queries that MyLA runs respected those variables that are already being imported at runtime. Queries in question:
- https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/config/cron.hjson#L41
- https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/config/cron.hjson#L116
- https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/config/cron_udp.hjson#L110
- https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/config/cron_udp.hjson#L236

Also see https://github.com/tl-its-umich-edu/my-learning-analytics/issues/1484 as it pertains to this being computed correctly.

**Comment by pushyamig** [comment]
I changed the TZ value in `.env` to `"America/Chicago" and ran the cron, I see that assignment and submission tables where local data is present, it populated correct date based on timezone. 

Test Pass
