### ISSUE TITLE
/lti/config/ error report

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1439]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 

Error with /lti/config/ endpoint after recent #1387 change:

{"lti_error": "Error filling in LTI template from \"/code/assets/config/lti_config_template.json\": ('jwks_url_suffix')"}

### Steps to Reproduce :
1. Go to <server_url>/lti/config/
2. Notice the above error returned by server

**Comment by jonespm** [comment]
The fix for this is probably to remove the `public_jwk_url` from https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/assets/config/lti_config_template.json since `jwks_url_suffix` was removed

**Comment by zqian** [comment]
close the issue. Follow with #1387
