### ISSUE TITLE
Some process needs to still retrieve/persist user_id and sis_name as it is used for MiVideo access events

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1443]
### Describe the bug (Tell us what happens instead of the expected behavior) :
In [PR #1392](https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1392/files), the user cron query does not pull in uniqname/sis_name from UDW. This is in preparation for UDP transition and UDP does not have non-roster user info, so that we need to get user login_name from LTI launch #1344 

However, this causes problem for MiVideo resource access events:
Since MiVideo is standalone tool, the Caliper events does not have Canvas user id information, so the user_id field has value of "-1". In [cron.py line 312](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/dashboard/cron.py#L312), MiVideo events are joined with the MyLA user table based on sis_name, so that MiVideo events can be stored inside resource_access table with values in user_id field

With the above change of [PR #1392](https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1392/files), MyLA user table no longer has sis_name field populated after cron run, and instead the sis_name value is set upon individual LTI launch and will be reset to null with next cron job. Hence the merge in [cron.py line 333](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/dashboard/cron.py#L333) will always return empty dataframe for MiVideo access events, hence MiVideo events won't be shown in Resource Access View.

### Steps to Reproduce :
1. Enable MyLA tool for a course with MiVideo tool
2. Run MyLA cron job 
3. Go to MyLA resource access view, notice there is no MiVdeo events shown

**Comment by lsloan** [comment]
To clarify, can an example of the Caliper event from MiVideo be added to the description?

**Comment by zqian** [comment]
@lsloan you can find the MiVideo query inside [this wiki page](https://github.com/tl-its-umich-edu/my-learning-analytics/wiki/Deploy:-Institution-Architectures)

**Comment by jonespm** [comment]
This looks good for the UDW, but this also needs to include a fix to pull what we can for UDP. I'm working on that and will test both of these out.

**Comment by jennlove-um** [comment]
Expected outcomes: 

Kaltura video events will be included in Resources Accessed for users who people who exist in the UDP as students and teachers in the SIS data when they have a StudentEnrollment on a course with MyLA enabled.

Kaltura video events will NOT be available for: 

- Staff user where SIS ID doesn't match Login ID (most users for us) in Canvas. Because UDP doesn't have all staff email and can't map to Kaltura. They shouldn't be a student anyway or a problem for MyLA for now, especially for RO courses.
- Empty SIS ID (because this SIS ID is then null in UDP). These shouldn't be common,  so no fix in place for this.
- Canvas SIS ID that doesn't exactly match or closely match (can swap + for @) the Login ID.  This is our style of friend/social accounts that either are an exact email match or one has a + the other has an @.  Maybe different for other universities.

**Comment by jennlove-um** [comment]
(Per Matt) There's 3 ways to improve this.

1. Unizin adds all users to the person_email or some other table that exist in the Pseudonym table. Figure out if anything came of this work.
2. MyLA pulls this data from some other source, either LTI launch (which would probably be sufficient) or API calls (which could work but not be great) or Canvas Data 2 (which me might utilize?)
3. Kaltura adds the correct ID to their Caliper event, which they seem to be doing but might take forever. And still old events wouldn't have this ID.

**Comment by jennlove-um** [comment]
Testing passes in Beta.

Event data is included for enrolled students.
Event data is included for friend accounts.
Event data is not included for staff with an SIS ID that does not match the Login ID.

**Comment by jonespm** [comment]
The fix we made for this for this release was to replace the mivideo query to do a replacement in the username. This is documented in the wiki

```                  
                  replace(actor.id, 'https://aakaf.mivideo.it.umich.edu/caliper/info/user/' , '') AS user_login_name, 
```

```
                  replace(
                    replace(actor.id, 'https://aakaf.mivideo.it.umich.edu/caliper/info/user/' , ''), '+', '@'
                   ) AS user_login_name, 
```

**Comment by jennlove-um** [comment]
Testing passes in Test.

Event data is included for enrolled students.
Event data is included for friend accounts.
Event data is not included for staff with an SIS ID that does not match the Login ID.
