### ISSUE TITLE
Switch MySQL Python or system library to version that has less security issues

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1454]
### Describe the bug (Tell us what happens instead of the expected behavior) :

It was identified in a security report that the library libmariadb 10.5 packaged in the Debian distribution has a [number of security issues](https://security.snyk.io/package/linux/debian:11/mariadb-10.5) and has [not had an update since March.](https://tracker.debian.org/pkg/mariadb-10.5). There are fixes in the 10.6 version but this isn't due to be in until the next version of Debian next year.

Two alternatives were suggested to work around this.

1) Switch to a different python package that's pure Python and doesn't need this library. This was done in #1448 but there was some concerns about performance of this package still.

2) Switch to a different system library, either the one direct from [MariaDB](https://mariadb.com/docs/connect/clients/mariadb-client/) which is updated more often or the one from Oracle for MySQL.

Testing this will involve doing regular regression testing on MyLA as this database is used in multiple places. Option 2 would likely have less risk and less code change.

**Comment by jonespm** [comment]
There were two noted issues with this so re-opening

* Dockerfile.openshift wasn't updated with this same fix
* git* is being removed for some reason causing an error with the start script

**Comment by jennlove-um** [comment]
Testing passes in beta.  Views are loading and filters are working as expected.
