### ISSUE TITLE
Move the git commit parsing out of the start.sh and into the build 

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1462]
Thank you for contributing to this project!

### Describe your problem or feature you'd like added
Currently, git values are parsed in the `start.sh` script at runtime. This requires `git` be available at runtime. Because of occasional security issues with git and libcurl it would be beneficial to just remove these packages. I believe we could just do it in the build and then remove them after.

### Describe the solution you'd like
Add something like this to the Dockerfile.

```
RUN bash -l -c 'GIT_REPO="$(git config --local remote.origin.url)"; \
                GIT_COMMIT="$(git rev-parse HEAD)"; \ 
                GIT_BRANCH="$(git name-rev "$GIT_COMMIT" --name-only)"; \
                echo export GIT_REPO=$GIT_REPO > /etc/git.version; \
                echo export GIT_COMMIT=$GIT_COMMIT >> /etc/git.version; \
                echo export GIT_BRANCH=$GIT_BRANCH >> /etc/git.version'
```

Remove git and read it in the start script. 

### Describe any possible alternatives you've considered
Some hacky solutions for pasing the .git have been considered like 

```
GIT_COMMIT="$(cat .git/HEAD | cut -c 1-7)
GIT_BRANCH="$(grep $GIT_COMMIT .git/packed-refs | sort | tail -n 1 | cut -d/ -f2- | rev | cut -d/ -f1 | rev)
```

But I don't really like those a lot

### Additional context
It looks like you have to use a file and can't set these directly since every RUN only knows about it's own context.
https://stackoverflow.com/questions/34911622/dockerfile-set-env-to-result-of-command

**Comment by jonespm** [comment]
Test Plan:

1) Verify the footer still shows the Git version when logging in
For instance something like`Git version: 8ef3a65 (commit) 2022.02.01 (branch)`
2) Verify that the security issue around libssl is no longer present.

**Comment by pushyamig** [comment]
test Pass
1. The Footer is showing current Git Version. I tested this from From Canvas test and Local myla instanse
2. I did a `docker scan my-learning-analytics-web` Locally myla build, I did not see the severity on `libssl`,
