### ISSUE TITLE
On resources access view, clicking on the minimized view on the right side generates errors

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1467]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 
You can click and navigate around on the right hand minimized view

### Describe the bug (Tell us what happens instead of the expected behavior) :
If I click on the minimized view in resources accessed in any course when it changes to a + sign (on the area that isn't highlighted. There are a bunch of console errors thrown and the list to the left breaks. The only way I can fix this is to refresh. This doesn't seem to matter which course. Testing to see if this was introduced in  #1367.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/27447/209214165-4bf0d90f-7921-4f14-9692-de5c4d10f85b.png">

<img width="543" alt="image" src="https://user-images.githubusercontent.com/27447/209214384-8bb03ed4-20a4-4617-9b78-09f25d9dfd1e.png">

I tested and this did work in 2022.01.03.

### Steps to Reproduce :
1. Go to the resource access view of any class with resources loaded 
2. Interact with the area on the right side
3.

### Additional context (Add any other context about the problem here) :
We could possibly remove this area if we can't get it working. I'm not entirely sure the value it added. This view may really need to be refreshed.

**Comment by jennlove-um** [comment]
Testing passes in beta.
