### ISSUE TITLE
Add Links in Canvas

### ISSUE THREAD

**Issue by kaaaka1995** [tl-its-umich-edu/my-learning-analytics#147]
Only enable links for students in these courses (It would be nice to have a graphic icon with these links):

1. Added link in the Assignments page to Assignment Planning Tool
2. Added link on the Files page to the What Students Are Reading 
3. Added lnk on the Grades page to Grade Distribution

**Comment by pushyamig** [comment]
I have checked in the code that make it happen, here is the link to it. https://github.com/tl-its-umich-edu/canvas-theme/blob/master/canvas_test/student_dashboard.js. The JS is applied to the Subaccount 51/53 in the test environment where the pilot courses reside

**Comment by pushyamig** [comment]
Test Plan:
1. Apply the Custom JS to the subaccounts 51/53 where the pilot courses reside
2. Since this applied to Canvas Test Env we could apply this for Canvas Beta for testing it out
3. Become a student in the course and see if the links enabled only for students in the course

**Comment by pushyamig** [comment]
This is done!

**Comment by pushyamig** [comment]
The script for

**Comment by pushyamig** [comment]
Currently, the script is uploaded to canvas test env. Please test it out

**Comment by jennlove-um** [comment]
Tested in Canvas Test using the Student View and by masquerading as a student in SI 110.

Verified that the Assignment, Files, and Grades links show up for SI 664 and HMP 654.
Verified that the Assignment and Files (not Grades) links show up for SI 110.
Verified that links did not show up for other courses in the SI and SPH sub-accounts ( I used SI 650 and HMP 600).
