### ISSUE TITLE
Log warning about courses added during cron is falsely reporting all courses

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#1476]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 

The log warning near the end of the run of `cron.py` should warn users only about courses that were added to the system during the cron run.

### Describe the bug (Tell us what happens instead of the expected behavior) :

During cron runs, all of the course IDs are reported by this log message. This seems to be because of a cast of course IDs 
to strings added in this commit: https://github.com/tl-its-umich-edu/my-learning-analytics/commit/141081a04ee92828b0c5029f7b2cb58224919692

**Comment by jennlove-um** [comment]
testing passes in beta
