### ISSUE TITLE
Improvements to narrative text and structure

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#1479]
When the Resources Accessed visualization was reviewed by the accessibility team, they had some recommendations regarding the narrative alternative text for the visualization. Some of these may also apply to the Grade Distribution chart.

- Narrative should identify itself as an alternative to the visualization: This becomes more important with aria-hidden removed from the SVG. Something like "Following paragraphs provide a text description for graphical bar-chart on this page."
- Structure narrative semantically: having the resources in a list instead of together in paragraphs would probably be slightly easier for users to parse.
- Narrative should include if you have accessed a resource in the past: This information is included in the visual graph and folks reading the text description would also likely find it to be useful.

**Comment by gsilver** [comment]
Great work as always!

1. Narratives identify themselves as alternatives to the visualizaton
2. Narratives have inner structure
3. Information on resources access is included

**Comment by jennlove-um** [comment]
This works nicely as a narrative.  It makes sense to group the items by those accessed and those not accessed and then list them from most often to least often accessed by other students in the class.

**Comment by pushyamig** [comment]
The change is also applied to Grade Distributions as well.

**Comment by jennlove-um** [comment]
The narrative on Grade Distribution looks good as well.
