### ISSUE TITLE
Remove additional unused dev dependencies to reduce security impacts

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1482]
### Describe the bug (Tell us what happens instead of the expected behavior) :
There are still some dev dependencies that we haven't removed and one of these `linux-libc-dev-5.10.162-1` came up in a security report. These are only needed to build dependencies and are not needed at runtime.

Remove this dependency but retain ones we do need as many others will be marked for removal.

**Comment by jonespm** [comment]
Yes that's the QA plan. You can also look at Vulnerabilities tab on the **latest** tag on Docker Hub which should provide the same information. 

https://hub.docker.com/r/tlitsumichedu/my-learning-analytics/tags

**Comment by pushyamig** [comment]
Test Passes
