### ISSUE TITLE
resource_id is always 0 in the JSON for resource_access_within_week

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1487]
### Describe the bug (Tell us what happens instead of the expected behavior) :

In the JSON return for resource_access_within_week I noticed that `resource_id` was always 0. 
```
    "r_name": "Lecture recorded on 8/30/2022",
    "resource_type": "videos",
    "resource_id": 0,
```

This seems fine because the value `r_id` is set instead.
https://github.com/tl-its-umich-edu/my-learning-analytics/blob/6e35e721301878e48cfe518c5f57e3ceed411fc4/dashboard/views.py#L370

We should just remove this unnecessary column from the dataframe to avoid confusion and reduce bandwidth. 

Looks like it came in with #1378

### Steps to Reproduce :
1. Load data into a course
2. Go to the resource access view and look at the API
3. Unused value shouldn't be present

**Comment by zqian** [comment]
@jonespm I think I found out a pattern for this:

- Those returned json element with `"resource_id": 0` are not viewed resources for the current user
- For the viewed resource items, the json element has meaningful value set for the `resource_id` attribute.

Could you please verify this, and close this issue if confirmed?

**Comment by jonespm** [comment]
Okay, thanks for looking into it. So I guess it is needed I just was looking at some wrong values. I don't see this being used by the frontend though, but it's fine leaving it in there.
