### ISSUE TITLE
Store dates from cron "as-is", remove time conversion from cron

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1490]
Thank you for contributing to this project!

### Describe your problem or feature you'd like added
It was noted on some recent fixes like #1484 that MyLA is storing values in local time. We had some discussion that this probably isn't needed and the application could do the conversion in the API (either in GraphQL or in the view) to the value in the settings. This might require some minor migration or we can just require dropping the tables and re-running the cron. 

This would probably be made easier if the old assignment view API's were removed #1492 and the cron for the UDW #1493 was also removed.

**Comment by jennlove-um** [comment]
Use the LTI launch timezone value to detect it.  Another option would be to use the browser timezone, but LTI is the best approach since it will match the timezone in Canvas.

**Comment by pushyamig** [comment]
Here is the time zone related change with newest Django 4 upgrade.
https://docs.djangoproject.com/en/4.2/releases/4.0/#zoneinfo-default-timezone-implementation

**Comment by lsloan** [comment]
I recommended this issue to Jaydon.  He can discuss it with me as he makes progress with it.

**Comment by jaydonkrooss** [comment]
From what I've been gathering on the previous issue [#1484](https://github.com/tl-its-umich-edu/my-learning-analytics/issues/1484), it seems that we're not trying to have any more local time conversions when populating the MyLA database, instead putting the conversion client-side. Based on [this commit](https://github.com/tl-its-umich-edu/my-learning-analytics/commit/69a32a61b33fdfeeb23af455136bc71c63dbde61) for that initial timezone fix, I'm thinking the only fields we care about in this case are `local_date` from assignment and `grade_posted_local_date` from submission. It seems that other datetimes are being imported from UDP without conversion; please share if there are other fields I'm not aware of.

Specific changes I'm considering:
1. drop the `local_date` field and use already provided `due_date` on the frontend
2. edit the `grade_posted_local_date` to simply be `grade_posted` without a local time conversion
(I'm not sure if this field is even used on the frontend so I don't anticipate any UI regression we'd have to test)

**Comment by jennlove-um** [comment]
Cron runs fine and no issues detected in beta testing.
