### ISSUE TITLE
DateTime fields should be displayed in the users local time

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1491]
Thank you for contributing to this project!

### Describe your problem or feature you'd like added
It was noted that times displayed are local to a specific time on the server (America/Detroit by default) and it would probably be useful to have the times match what's in Canvas for the user to their local time. This is mostly for the assignment view. 

### Describe the solution you'd like
Either get and use the custom LTI launch variable `Person.address.timezone` or use the browsers time zone to do the time conversions for the user. This would require storing the times in UTC first locally via #1490

**Comment by jennlove-um** [comment]
Research the impact of this

**Comment by jennlove-um** [comment]
There is a library change in the Django upgrade that may affect this.

**Comment by pushyamig** [comment]
Here is the time zone related change with newest Django 4 upgrade. 
 https://docs.djangoproject.com/en/4.2/releases/4.0/#zoneinfo-default-timezone-implementation

**Comment by lsloan** [comment]
Canvas provides the user's time zone in the variable `$Person.address.timezone` when LTIs are launched.  A custom launch parameter can be set with this value.

**Comment by jennlove-um** [comment]
Cron runs fine and no issues detected in beta testing.
