### ISSUE TITLE
Remove original assignment planning view 

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1492]
Thank you for contributing to this project!

### Describe your problem or feature you'd like added
Currently this application has 2 assignment planning views, the original/classic view should be removed as it's not tested as much and isn't going to have any new development. It also is confusing to newer installs that see the two views and have to disable one. This view called `show_assignment_planning_v1` and was replaced by the newer assignment goals view. 

### Describe the solution you'd like
The files for the templates in React as well as the API's used should all be removed.

**Comment by jennlove-um** [comment]
Tested in MyLA beta.

All references to AP1 no longer show up in the UI for MyLA or in the admin view of courses.  I am able to enable/disable the new AP in courses without any problem.
