### ISSUE TITLE
Remove cron.hjson (UDW queries)

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1493]
Thank you for contributing to this project!

### Describe your problem or feature you'd like added
We are no longer supporting the cron for UDW and it's not going to be tested as much going forward. To reduce maintenance burden we should remove this view. Additionally with Canvas Data 2, Canvas has indicated that they plan to also remove the old data dumps so this wouldn't work at all after that anyway. I believe they gave a tentative date of December 2023. 

### Describe the solution you'd like
Remove files and documentation around the cron.hjson and UDW. We'll want to have a new major version and indicate that it only works with the UDP.

**Comment by pushyamig** [comment]
Locally the cron is fetched from cron_udp: `[2023-09-14 12:33:40 -0400] [INFO] [cron.py:30] /code/config/cron_udp.hjson`

Cron is successfully run, MyLA Beta server has correct path (as the PR reflects) and app launches fine

Test Passes
