### ISSUE TITLE
Console warning from `class` prop usage in `SelectCard`

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#1494]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 

There should be no Web console errors or warnings when using the UI.

### Describe the bug (Tell us what happens instead of the expected behavior) :

There is a warning about an invalid prop name of `class` (as opposed to `className`). I introduced this accidentally in PR #1475. The warning is suppressed in production, so there is no visible error there.

### Steps to Reproduce :
1. Launch MyLA from a course, check you're on the view/visualization page.
2. Check the Web console.

**Comment by pushyamig** [comment]
Test Passes. I don't see the error from any views including the home page. I ran the test from latest from my local
