### ISSUE TITLE
Assignment Planning: Display the course goal as null when all assignments are graded and students have not set a goal

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1497]
### Expected behavior (A description of what you expected to happen) : 
The Minimum Goal for the course should be null and not show an error when a student hasn't set a course and assignment goals, even when all assignments are submitted and graded.

### Describe the bug (Tell us what happens instead of the expected behavior) :
Prerequisites: 

- Student has submitted all assignments on the course
- All assignments have been graded
- Student has not set up a Minimum Goal for the course

In these circumstances, MyLA is displaying the message "Scores no longer match goal" in the My Minimum Goal field.  This field should be blank because the student hasn't set a goal.

### Screenshots/Video (If possible, add media to help explain your problem) :
<img width="481" alt="image" src="https://user-images.githubusercontent.com/39634416/225116345-1e68c459-f8c0-4040-8d1a-b496cb93aae6.png">

--------------------
Test Plan:
https://docs.google.com/spreadsheets/d/1fOLY2byRBUZ1JzCFir6WiIPfrMPN2_-7oJKr5zhsiEM/edit#gid=0

**Comment by Tombow1** [comment]
Hi! I'm an UM undergrad new to contributions, can I work on this issue?

**Comment by jennlove-um** [comment]
Hi @Tombow1 - 
Thanks for contacting us about contributing to MyLA. While MyLA is open source, it can be difficult to work on unless you have access to a test instance of Canvas where you can install it as an LTI and run a cron job to access the Canvas data. Students generally don't have that kind of administrative access to that Canvas data.

However, there is another project that we could recommend as an option for your assignment.  The Remote Office Hours Queue is also open source and has several issues that have been tagged as "[good first issues](https://github.com/tl-its-umich-edu/remote-office-hours-queue/labels/good%20first%20issue)."  You can read more about that project here: https://github.com/tl-its-umich-edu/remote-office-hours-queue

You could also take a look at the University of Florida's Open Source projects: https://github.com/ucfopen. They actively maintain most of those projects and have a Slack channel for questions and communication. UDOIT )an accessibility checker for Canvas) and the CanvasAPI might be of interest to you.

**Comment by jennlove-um** [comment]
This error still occurs in testing.

**Comment by jennlove-um** [comment]
Tested in MyLA beta.  One use case failed.

1. Set a course goal.
2. Set assignment goals that do not add up to the course goal.
--> Expected result is that the message "Scores no longer match goal" shows up over the My Minimum Goal field.
--> Failed: The message does not show up over the Minimum Goal field.

I'm reopening this issue for further investigation and fixing.
