### ISSUE TITLE
need to add more detail as comment to the `metadata` query in MyLA cron_udp.json

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1502]
### Describe the bug (Tell us what happens instead of the expected behavior) :

The `metadata` query inside cron_udp.json was used as an indicator for MyLA data freshness:

`select 'canvasdatadate' as pkey, min(dag_run) as pvalue from report.publish_info pi2
`
Need to add some comment there for the meaning of above UDP query. Here is some sample text:

```
// The UDP’s batch-ingest process is organized by a single Directed Acyclic Graph (DAG) named "ingest"
// The dag_run date inside publish_info report would reflect when the data was loaded into the context_store by Unizin batch-ingest ETL process. Note that time wouldn’t reflect when the data was actually dumped from canvas.
```

- https://resources.unizin.org/display/UDP/Batch-ingest+application)

**Comment by pushyamig** [comment]
Test pass:
The changes are correctly updated on MylA beta and in Master branch
