### ISSUE TITLE
Resolve issue for No Term from UDP course query

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1504]
Zhen had a working fix for the UDP query on this other PR, should close this PR and open a new one with the fix

              Hmm, I pulled the list of all the course ids to use from our production to substitute in `%(course_ids)s` there are 537 courses defined there. 

```
SET SESSION group_concat_max_len = 16384;
select CONCAT("'", GROUP_CONCAT(id order by id SEPARATOR "','"), "'") from course where id is not null order by id;
```

The query on the PR 'as-is' _only_ seems to return 51 rows, the query Zhen proposed returns 537 rows, our original query returns 537 rows. 

So I'd probably close this one and @zqian can open one with her change.

_Originally posted by @jonespm in https://github.com/tl-its-umich-edu/my-learning-analytics/issues/1499#issuecomment-1507523240_

**Comment by jonespm** [comment]
The query fix was at https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1499#issuecomment-1502118434

**Comment by jennlove-um** [comment]
Tested in MyLA beta.

Adding a course with No Term worked. The course was added and there were no error messages in the cron log for the course.
