### ISSUE TITLE
Courses are not editable via Django Admin

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#1509]
After my PR #1468, it seems users are blocked from editing courses using the Django admin interface. This is because of a custom cleaning method defined on `CourseForm` that expects for `canvas_id` to always be defined.

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/90ed091b50dd7c536d25618d464ec14b2b248eac/dashboard/admin.py#L53-L58

Possible solution include modifying the cleaning logic to only run on course creation, or removing the form in its entirety.

**Comment by ssciolla** [comment]
There is another bug here that needs to be resolved. The previous solution for this problem seems to change the `readonly_fields` for this form for the remainder of the session. This becomes a problem because when you edit a course, and then try to create a new one, the `canvas_id` field is not editable, but it can't be null. The solution here I think is to override the`get_readonly_fields` method rather than changing the `readonly_fields` attribute.

**Comment by jennlove-um** [comment]
Ready for testing.

**Comment by jennlove-um** [comment]
Tested in beta.  I am able to create, update, and delete courses in the admin page.
