### ISSUE TITLE
Switch build to reference (Debian) bullseye explicity

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1511]
### Expected behavior (A description of what you expected to happen) : 
Build should complete without issue

### Describe the bug (Tell us what happens instead of the expected behavior) :
This week the Python base image was switched over from (Debian) bullseye to bookworm. This is causing the builds to fail. 

The easiest fix would be to switch it to bullseye as we did with another of our apps but we'd have to upgrade this within the next year or so.

I'll investigate this and see what would be the best fix since we're a little away from a release still for MyLA.

**Comment by pushyamig** [comment]
I see the build downloading the bulleyes version and build is successful and the app launches fine

https://github.com/tl-its-umich-edu/my-learning-analytics/actions/runs/6175602251/job/16762814340

Test passes
