### ISSUE TITLE
Upgrade python/node Dockerfile base to use bookworm

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1513]
Thank you for contributing to this project!

### Describe your problem or feature you'd like added
Debian bullseye which was set explicitly in #1511 [ends security support](https://endoflife.date/debian) in July 2024. I couldn't easily switch over to it in #1511 because MariaDB did not yet have packages for it. I'm guessing it will in the next 6 months or so.

### Describe the solution you'd like
Switch the base python/node image over to bookworm.

**Comment by lsloan** [comment]
In doing QA of implementation in #1545, I can verify that it is now running "bookworm"…

```txt
root@272ac7a96dd0:/code# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
