### ISSUE TITLE
Upgrade to Node 18

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#1515]
Node 16 is currently in maintenance mode and will reach end of life in Sept. 2023. It's time to update to 18.

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/90ed091b50dd7c536d25618d464ec14b2b248eac/dockerfiles/Dockerfile#L3

Resources
- https://github.com/nodejs/release#release-schedule

**Comment by jonespm** [comment]
Verified from build logs that Node 18 was used and components were built as expected.
