### ISSUE TITLE
npm build is not considering package-lock.json, some packages are upgraded

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1527]
Thank you for contributing to this project!

### Expected behavior (A description of what you expected to happen) : 
Packages are static between deployments and updated manually. However it looks like they're updated to newer versions.

### Additional context (Add any other context about the problem here) :
It was noticed that package-lock.json is ignored and not included in the builds. This file is needed to ensure the versions are predictable/static.

**Comment by pushyamig** [comment]
Tested a couple packages in Package-lock.json downloaded/used in Myla Beta

1. [Apollo](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/package-lock.json#L63): 
```
:/code/node_modules/@apollo/client$ cat version.js
export var version = '3.5.10';
```
2.[ D3 version](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/package-lock.json#L4809):
```
:/code/node_modules/d3$ cat package.json
{
  "name": "d3",
  "version": "7.6.1",
```

Test passes
