### ISSUE TITLE
For Github actions/registry get the Repo values from environment

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#1533]
From the #1523 one thing that is noticed that github action get trigged even on forked repo. The actions workflow is written to push to tl-its-umich-edu/my-learning-analytics and the build might be successful but the push will fail and giving an alert each time. 

denied: permission_denied: The requested installation does not exist.

This is recorded here https://github.com/pushyamig/my-learning-analytics/actions/runs/5978168974/job/16219869585

**Comment by jonespm** [comment]
Verified Actions runs are skipped on forks. We may want to have some kind of "else" cases in here but it looks like a good pattern and things are working as expected. 

![image](https://github.com/tl-its-umich-edu/my-learning-analytics/assets/27447/d4896969-4599-4fc0-bedb-63154956db97)
