### ISSUE TITLE
change Postgres cron queries to BigQuery quries

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1557]
### Describe your problem or feature you'd like added

MyLA [cron.py](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/dashboard/cron.py) queries UDP context_store for Canvas data and UDP BigQuery for Caliper events. 

### Describe the solution you'd like

The UDP context_store tables can now be queried from UDP BigQuery. We can update MyLA cron.py file, and remove the SQLAlchemy and psycopg libraries.

**Comment by jonespm** [comment]
If/when we go to BIgQuery we could consider switching to access the CD2 (canvas table) directly. This could more directly fix issues like #1559 where the context_store doesn't keep pseudonyms for all users. It would also bring up the question if we should use the context_store or just go to the canvas table directly? Are there advantages for MyLA to use the context_store? 

This would put us back closer to the UDW and I think eliminate some other bugs we had to try to workaround with these UDP queries. 

I think if we don't do a full switch for some tables like the users table we *should* use the data from the Canvas tables where it's possible at least replacing things like `entity.person_email`

**Comment by jonespm** [comment]
@zqian I'm not sure if you started on this but I started working on this today. 

I'm wondering if there's value in leaving the `sqlalchemy` stuff in there anymore since this is all using UDP anyway. I think I can write code so both work, at least for now, and remove that later. But I'm also think we should just remove it entirely. I feel like we're in the "Unizin 100% required" phase for this project now.

**Comment by zqian** [comment]
@jonespm I took my name from the assignee list. Please go ahead update the title and description of this issue, since the current design is to use Canvas Data 2 hosted in BigQuery.

**Comment by zqian** [comment]
@jonespm: Can the "DATA_WAREHOUSE" settings be removed from ConfigMap?
