### ISSUE TITLE
Provide a way to give staff users access to other courses

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1583]
In Django, the staff role allows users access to admin pages and superuser gives the user all permissions.

However there's currently no way to give staff access to view courses that they aren't explicitly in. This is because rules is checking for superuser.

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/d400cce524986a9127ed037ac144009869174527/dashboard/rules.py#L14

There's also some inconsistency about the naming here like in utils it says "is_superuser" is given if the user is staff. This should just be consistent to be "is_staff". Staff and superuser have different meanings.

```
dashboard/common/utils.py
87:    is_superuser = current_user.is_staff
```

I think we'd have to do a fix here to either have it so the staff user is the one with full access to every course and make the naming in the code consistent. Or we'd have to add a new explicit permission that could be checked that would give this user access to all the courses. I feel like doing staff is enough but we might have to talk about it. We could probably include this in the next release. 

---------------------------------------

Test Plan:

Test as instructor, Student all feature should work as expected
Test with Myla staff role: Can create Myla courses and access then as well
Test as Myla full Admin ( is_superuser and is_staff): Full access to whole app

**Comment by zqian** [comment]
According to the prod database, there is no user who is a staff but not a superuser, or vice versa. 

```
select *  
from auth_user au 
where au.is_staff != au.is_superuser 
```
So I think this is an easy problem to solve: just remove the check of is_staff, and always check for is_superuser value. 

WDYT?

**Comment by clalande** [comment]
We would like to have users who are staff, who can see & support classes we are running MyLA in, but not have full super user access.   We don’t want to enroll them in the classes as instructors.

— Chris
________________________________

**Comment by zqian** [comment]
Thanks for the input, Chris!

**Comment by clalande** [comment]
You bet.   I wrote something up originally, I’ll see it I can find it and add it to the issue.

— Chris
________________________________

**Comment by jonespm** [comment]
This is a new feature request,

Generally we've just checked both options and haven't implemented them separately. This issue is to clean that up and make these permissions clear and distinct. 

`is_superuser ` would allow all course access and all admin access, including adding users and changing permissions
`is_staff ` is more limited and would allow all course access and some admin access

So this would be giving support if `is_staff` is checked without `is_superuser`.

**Comment by clalande** [comment]
[Re_MyLA_Error_for_some_Roles.pdf](https://github.com/user-attachments/files/16818808/Re_MyLA_Error_for_some_Roles.pdf)

I found the email thread where we discussed this last spring, and have attached this as a PDF for reference.

**Comment by jennlove-um** [comment]
Testing passes in beta for student, teacher, myla-admin-staff, and myla-admin-superuser.
