### ISSUE TITLE
Goal setting inputs do not seem to have a name

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1590]
On the Assignment Planning view, the goal setting inputs do not seem to have a name. 

MyLA Technical Review 7/24 - row 5

https://docs.google.com/spreadsheets/d/186xZEvxhbh55jLR_mRXT9tMrmFUlcBlUtkN5T7BuT64/edit?gid=886470260#gid=886470260

**Comment by pushyamig** [comment]
I will work on this issue. This has a priority label added.

**Comment by gsilver** [comment]
Went over this with Pushyami - there is no issue. Input all have logical names.
