### ISSUE TITLE
Add names to "Lock Goal" checkboxes

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1591]
Assignment Planning: Checkboxes do not seem to have a name - but the table has good structure, so giving them a name is a best practice

[MyLA Technical Review 7/24 - row 6](https://docs.google.com/spreadsheets/d/186xZEvxhbh55jLR_mRXT9tMrmFUlcBlUtkN5T7BuT64/edit?gid=886470260#gid=886470260)

-------------------
Test Plan:
1. From Chrome Dev Tool --> axe DevTools -- > Full Scan
2. `Replicating the issue`: Without the change it will show 'Form elements must have Label'. but after the change it row will disappear
3. A more precise way of `testing` this Chrome Dev Tool --> right click on checkbox element --> inspect --> Right side of window ---> click accessibilty Tab in `input` element ---> Look for `Name' in the accordian style design --> Aria-Label should say "Lock Goal"

![Image](https://github.com/user-attachments/assets/1c34a075-e5e6-43d1-9fec-51d5bc2ecff5)

**Comment by zqian** [comment]
@gsilver will you be able to review this issue on Canvas test?

**Comment by jaydonkrooss** [comment]
I've released the change onto Canvas test

**Comment by jennlove-um** [comment]
this passes in testing on MyLA beta
