### ISSUE TITLE
Add names to Filter by Status and Filter by Type fields on Assignment Planning

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1594]
Filter by status field and Filter by type do not have names

Acceptable techniques: 

aria-label="the name"
aria-labelledby="id of a container with a good name"

MyLA Technical Review 7/24 - Row 9

**Comment by jaydonkrooss** [comment]
@gsilver This change is also available on Canvas Test for testing

**Comment by jennlove-um** [comment]
testing passes on myla-beta: the filter by status and filter by name fields now have names
