### ISSUE TITLE
"Clear minimum goal" probably a better name for ambiguous  "clear" button

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1595]
"Clear minimum goal" probably a better name for ambiguous  "clear" button on the Assigment Planning view

[MyLA Technical Review 7/24 - Row 10](https://docs.google.com/spreadsheets/d/186xZEvxhbh55jLR_mRXT9tMrmFUlcBlUtkN5T7BuT64/edit?gid=886470260#gid=886470260)

**Comment by zqian** [comment]
@gsilver will you be able to review this issue on Canvas test?

**Comment by jennlove-um** [comment]
Testing passes in beta.
