### ISSUE TITLE
Files changes based on feedback 2018/10/04

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#195]
Weeks are wrapping on the bar - fix this
Bring in margins so that weeks don’t get cut off
Change page title to Files Accessed
Drop down language needs to change to All grades, remove NO GRADE

**Comment by jennlove-um** [comment]
Week wrapping - Partially passes in testing.  The Week 15 marker still wraps around for me.  It's okay when I first open the screen, but if I resize the screen smaller, Week 15 (and only Week 15) wraps around.  When I enlarge the screen again, Week 15 stays wrapped around.

Margins brought in - passed in testing
Title of page changed to Files Accessed - passed in testing
Drop down change - passed in testing

**Comment by jonespm** [comment]
I'll create the week wrapping as a new issue.
