### ISSUE TITLE
track user usage pattern with student dashboard tool

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#20]
Things to track:

- login, logout
- linked clicked
- filters used
- personalized option settings, e.g. notification email frequencies, etc
- comments and feedbacks

**Comment by jonespm** [comment]
Do any of our apps currently implement caliper? That's what you were thinking about for events right? 

We'd either have to do this one the client (using caliper js) or server (caliper python). Many of these events are not triggered on the server so I'm guessing it's better to just do it all on the client. The downside of that is if the caliper end point is unavailable the events would be lost (unless we had a backup to send them to)

Pretty cool feature though!

**Comment by zqian** [comment]
Implement Caliper might be a bit stretch for now. My goal is to do a simple relational table first.

**Comment by pushyamig** [comment]
Minor comment: Last time I used caliper-python at Unizin hackathon, we had so much trouble using that library. Not well-documented cases of using the library. also, the python sensor was not on PyPI that lead to a lot of installation problem.

**Comment by jonespm** [comment]
This might be partially related to #310

**Comment by zqian** [comment]
Close it for now. Will track it elsewhere.
