### ISSUE TITLE
Add email notification function 

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#21]
Student Dashboard tool will send various notifications to student, and student should be able to set notification options (individual email vs daily/weekly digest emails).

Here is a list of notification examples:

- Assignment is due in X days, and user has not submitted yet
- Among the top 5 files read by students in the class recently, there are X files has not been read by the current user
-  start, mid-term, end-term notification for inputting feedback of using the dashboard tool (?)

**Comment by jonespm** [comment]
Is this really a requirement for the pilot? This sounds somewhat like separate functionality from the UI.

**Comment by jennlove-um** [comment]
I took the pilot label off of this one.  This requirement has not been fully developed or agreed upon.  It's something to consider for future versions.

**Comment by jonespm** [comment]
Yeah, this is going to take some time to work out. I think the requirements of what will be notified and the entire system behind this will be a little involved. I'm attaching the label "Phase 2" to these projects. (This label can be renamed)

**Comment by zqian** [comment]
PIs do not like the email nudging option. Close it for now.
