### ISSUE TITLE
Homepage link should keep the course info when a student clicks it from one of the visualizations

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#222]
When I try to go from the Files Accessed page back to the home page, the dashboard forgets which course I'm in and gives the message "My Learning Analytics: This site must be launched from Canvas."

Here's the workflow: 
1. Go to the Files Accessed page for a course
2. Click on the My Learning Analytics link in the upper left 
3. Dashboard home page displays with no course selected
--> Expected result: User sees the home page for the course they are in

Is this something that is happening because I'm an admin and not officially enrolled in any course?  I also tested using the "login as" option, but saw the same results.

**Comment by jonespm** [comment]
Yeah, that sounds like a good idea. I'm partially working on this as part of #186 but I think the ID should carry back to the URL link on the upper left.
