### ISSUE TITLE
Disabling views option based on user not based on course

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#255]
This might be crazy idea, what if some user data has a problem and we want to disable the view just for that user. We should have user-view table mapping. so that we could turn on/off for just that user.

**Comment by jonespm** [comment]
This sounds like it really increases testing complexity. I think it would need to be real requirement before this were implemented. 

I can *maybe* see having a different view based on role, but right now we aren't really paying attention to roles.

**Comment by jennlove-um** [comment]
At this point, this seems unnecessary.  We can reopen the issue if we identify a use case where this is needed.
