### ISSUE TITLE
Files accessed view week wraps when resizing display (or on small displays)

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#285]
The Week  marker still wraps around for me. It's okay when I first open the screen, but if I resize the screen smaller, Week 15 (and only Week 15) wraps around. When I enlarge the screen again, Week 15 stays wrapped around. Not sure what best way to make this responsive

![image](https://user-images.githubusercontent.com/27447/47880419-9d45e980-ddf9-11e8-9f16-206384eefb0b.png)

**Comment by jennlove-um** [comment]
The workaround right now seems to be to reload the page.  This is still happening with the code change made to include week 16 (#329).  Now it's week 16 that wraps and stays that way when the screen is resized.

**Comment by jonespm** [comment]
Yeah, it still is an issue, moving the slider looks like it fixes it to.

It looks like it might be related to https://github.com/slawomir-zaziablo/range-slider/pull/1 but that didn't fix it. We'd *possibly* have to use a different slider to fix this or get a fix committed for this slider.

**Comment by jennlove-um** [comment]
This issue no longer occurs in the current release.
