### ISSUE TITLE
Add more version/build information to django admin

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#287]
It was suggested on #284 to add more information. I believe we could add this to the Django Admin as a module.

`OPENSHIFT_BUILD_NAMESPACE: ccm OPENSHIFT_BUILD_NAME: canvascoursemanager-12 GIT_SOURCE: https://github.com/tl-its-umich-edu/canvas_course_manager.git GIT_BRANCH: 4.0.1 GIT_COMMIT: fb68ce8d56741338f6c1fa414201be5c19b91023`

**Comment by pushyamig** [comment]
Done
