### ISSUE TITLE
Assignment Planning - Alignment in Assignments Due by Date is off in Safari

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#290]
On a Mac using Safari, the alignments in the list of assignments are not lining up correctly.  The Due date is shifted to the left instead of being aligned with the column header.  In one week, all columns are shifted left and are out of alignment with the other columns.

I saw this only in Safari.  Testing was done with SI 664.

**Comment by jennlove-um** [comment]
<img width="755" alt="screen shot 2018-11-02 at 3 40 02 pm" src="https://user-images.githubusercontent.com/39634416/47937105-19056c00-deb6-11e8-8cb2-fd3a741459f1.png">

**Comment by pushyamig** [comment]
It load up fine on this version of safari 
<img width="1328" alt="screen shot 2018-11-02 at 6 58 32 pm" src="https://user-images.githubusercontent.com/8579775/47944369-70fd9c00-ded1-11e8-8a60-45f859a581e3.png">
@jennlove-um which version of safari you are using?
from the analytics report these are most used safari browsers
![screen shot 2018-11-05 at 8 15 12 am](https://user-images.githubusercontent.com/8579775/48000463-893d0900-e0d3-11e8-8ba7-a9f9c2293004.png)

**Comment by jennlove-um** [comment]
macOS High Sierra 10.13.6
Safari 11.1.2 (13605.3.8)

It's the loaner Mac I use for testing.  I can try upgrading Sierra to to 12 to see if the problem still shows up.

**Comment by pushyamig** [comment]
I have same exact version of safari and OS and I don't see the problem. There is something we are doing different

**Comment by jennlove-um** [comment]
This issue does not show up in current testing.  I'm closing this for now.  We can reopen if the issue shows up again.
