### ISSUE TITLE
disable MyLA for SI 110

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#298]
The changes are updated to the test env

**Comment by jennlove-um** [comment]
Testing: 
Links are removed from SI 110.
Links still display in HMP 654 and SI 664.

Should we use this issue to also track disabling the dashboard for SI 110 in the database in case they have it bookmarked?

**Comment by pushyamig** [comment]
ok,Good idea. I will disable the DB option now.

**Comment by pushyamig** [comment]
OK, I have set the option in the DB to disable the tool for SI 110. Test it out

**Comment by jennlove-um** [comment]
Testing passes - all of four of the pages (home, files, assignments, and grades) are hidden for SI 110.
