### ISSUE TITLE
Implement PEP 3107 for function annotations

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#301]
We should improve the code quality and implement function annotations for return types and parameter types to MyLA. 

This is described here as reference

https://www.python.org/dev/peps/pep-3107/
https://python-future.org/func_annotations.html

**Comment by jacobmal** [comment]
Hi, my EECS 481 partner (luctiger98) were looking at adding this enhancement too. We were added to the google sheet for tracking the 481 student assignments. Should I add a row to the sheet with this issue and my uniqname?

**Comment by jonespm** [comment]
Yeah, sure go ahead and keep the sheet updated so we can better track who's working on what. We plan to assign people have committed to issues to the issues by the end of the week.

**Comment by jonespm** [comment]
It might be too much work to do every python class for this. If you want to break it up into a subtask and only get to views, models or some other class that would still be a nice improvement for us. 

Something like this might be of assistance: https://stackoverflow.com/questions/44057003/how-to-annotate-django-views-methods

**Comment by jonespm** [comment]
We had a contribution to do this but decided it would be better to implement this as needed rather than all at once. Might revisit this.
