### ISSUE TITLE
Investigate using a python based graphing library instead of D3

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#304]
D3 isn't the best for doing graphing, and it would be better if we could generate more of the graphs with less work in the backend.

A good charting library that connects with D3 is C3 (https://c3js.org/)

This has a project that is entirely in Python called C3PyO. It's possible we might be able to look into this to migrate some of our graphs over, and change others to be more Python based rather than fully D3. 

https://github.com/benalexkeen/C3PyO

This will just require some research. I think it might make the project less code and more maintainable if it works out.

**Comment by justin0022** [comment]
What are your pain points for using D3? I wonder if adding in a JavaScript development and build pipeline might reduce the pain of developing in D3. 

I've tried out Python-based visualization libraries in the past and have found that for developing web dashboards, especially interactive dashboards, D3 or other JavaScript-based libraries are preferable.

**Comment by jonespm** [comment]
Back when I first created this, we were using nvd3 (which only supported d3-v3), d3-v3 AND d3-v4 in this code. I feel like most of the code is now all on at least d3-v4 and probably can go to d3-v5. 

I personally didn't have any pain as @pushyamig and @zqian did the majority of the frontend, I just had pain with all of the libraries being used. ;) Though I suppose there is some pain in trying to figure out how we'd make this work on mobile. Though currently (according to Google Analytics) we're about 98% desktop.

I wanted to see if there was a library more specific to charting (like the c3) that could maybe be wrapped by python to make that straightforward. I know in the end we might have to go to d3 direct but we don't really have any reusable charting components.
