### ISSUE TITLE
Assignment Planning: Add the average grade on an assignment to the mouse-over text

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#320]
In the assignment details, add the average grade in the mouse-over.  This should show in the progress bar mouse-over.

Business Rules: 
Canvas allows instructors to hide the grade distribution by assignment in a course.  If they have hidden this data in the course, we should not show it in the visualization.

Canvas only shows the grade distribution if 5 other students have submitted the assignment.  Our visualization should follow the same logic.

**Comment by jennlove-um** [comment]
[https://community.canvaslms.com/docs/DOC-9540-4212724430](url)

**Comment by pushyamig** [comment]
A sample set of queries to validate this issue
1. select s.*,a.name from submission s join assignment a on s.assignment_id=a.id and s.course_id='17700000000245664';

**Comment by pushyamig** [comment]
@jennlove-um fixed the minor formatting issue

**Comment by jennlove-um** [comment]
Update the online help to include the average assignment grade information.  

I'll add this before closing this issue.

**Comment by jennlove-um** [comment]
Online help has been updated.
