### ISSUE TITLE
Files visualization needs to account for full number of weeks in term

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#329]
The Files Accessed default is not working correctly in finals week.  Now that we're in week 16 (finals week), the default is showing up as Wk2 to Wk 2 since there is no week 16 in the visualization.

The default needs to work all the way through the end of finals week for each term.

**Comment by jonespm** [comment]
I think it'll also have to calculate the actual number of weeks in a course based on the start/end date of the term the course is in. There are spring/summer half term courses that don't even run the full 16 weeks. These *might* be ones we look to trying to support soon and at least eventually with the wider rollout we will be getting to these eventually.

**Comment by jonespm** [comment]
I worked on this a little, here's a graph for week 5 of a 12 week course
![image](https://user-images.githubusercontent.com/27447/50614012-7ebda680-0ead-11e9-82ac-f8ca97207100.png)

This is week 1 of a 8 week course
![image](https://user-images.githubusercontent.com/27447/50614508-0f48b680-0eaf-11e9-8515-1d6f954b63b3.png)

This is when the 16 week course is past the date
![image](https://user-images.githubusercontent.com/27447/50614673-a7df3680-0eaf-11e9-9180-cc3851a82fb4.png)

**Comment by jennlove-um** [comment]
16 weeks display correctly for courses in the Files Accessed slider.
