### ISSUE TITLE
Provide a JSON feed that would give the courses supported and the features supported

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#332]
If we had a JSON feed then we could have Canvas load this to avoid having to configure Canvas every term.

This is an example of how we could add this to the Canvas theme script
https://github.com/robert-carroll/ccsd-canvas/blob/master/admintray-subaccmenu/admintray-subaccmenu.inc.js

I'm thinking JSON like this should work?

```
{
  "241011": {
    "files": "true",
    "assigment": "true",
    "grade": "true"
  },
  "029921": {
    "files": "true",
    "assigment": "true",
    "grade": "false"
  }
}
```

**Comment by pushyamig** [comment]
This is great idea, this will eliminate the manual process and we could still have all the link in course pages. 
We could write a service that will expose the API publically and we could read the feed from custom JS. This will indefinitely be used even we made the tool as LTI

**Comment by jonespm** [comment]
In the case of timeout (assuming we were hosing the json on our site) we could just return no data and then no links would be displayed. But that's fine as the links wouldn't work anyway even if a user clicked on them. This json would be cached in the browser and we'd only expire it if the courses changed.

https://stackoverflow.com/a/14238914/3708872

We could host the JSON somewhere else but I don't think it would be very high traffic.

**Comment by jonespm** [comment]
I looked at generating this JSON and we'll either have to do it manually or start using this 'djangorestframework' module which would probably be better for the long run.

https://www.django-rest-framework.org/tutorial/quickstart/

**Comment by jonespm** [comment]
Here's some example of the output and how you'd parse this string in JS. Though we'd retrieve this from some URL rather than have it hardcoded this is just an example. 

In the future when/if we support a lot of courses we may want to filter by term.

```
var str = '{"123456": {"cn": "SMPL 101 SU 2018", "fa": 1, "ap": 1, "gd": 0}, "654321": {"cn": "SMPL 102 FA 2018", "fa": 1, "ap": 1, "gd": 1}, "111111": {"cn": "SMPL 103 FA 2018", "fa": 1, "ap": 1, "gd": 1}}';

var json = JSON.parse(str);
console.log(json["123456"])
```

Note to save space incase we have a lot of courses, I'm using shortened keys and 0/1 so javascript will have to handle that.

**Comment by jonespm** [comment]
To test this go to /api/v1/courses_enabled

This passes
