### ISSUE TITLE
Files Accessed Weeks > 16 doesn't display well and slider doesn't work on mobile at all (overlap)

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#336]
This may never be an issue but if we go beyond 16 weeks it doesn't look good
![image](https://user-images.githubusercontent.com/27447/50658882-bc333a00-0f68-11e9-908e-bde613f5cffe.png)

Also on mobile the slide is unusable
![image](https://user-images.githubusercontent.com/27447/50658899-cce3b000-0f68-11e9-8d45-90d3d67f2d81.png)

We might want to change up the slider somehow to only have a the digit for which week we're on rather than the full text. Or have a different user interface item.

**Comment by jonespm** [comment]
This is a quick change
Regular desktop
![image](https://user-images.githubusercontent.com/27447/50659199-da4d6a00-0f69-11e9-86b0-42d2020083f7.png)

Mobile (XS) view
![image](https://user-images.githubusercontent.com/27447/50659177-c9045d80-0f69-11e9-87fe-cc4975b3a27c.png)

**Comment by jonespm** [comment]
@zqian @jennlove-um Do you have any opinions on this? Do we need to run this by the project team Monday? I have this work basically done if we want to switch over.

**Comment by jennlove-um** [comment]
I created a course term called "Winter 2019 Long" for testing.  Once the data is picked up in the UDP, I'll test using this term in MyLA on Monday.

**Comment by jonespm** [comment]
@jennlove-um Did you check this out again with the longer term?

**Comment by jennlove-um** [comment]
@jonespm I tried to test it with a longer term called Winter 2019 Long, which should be 21 weeks, but the Files Accessed page still shows a 16 week term.
