### ISSUE TITLE
Allow admins to set manual start and end dates for the term.

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#343]
Add an option that allows admins to manually set term dates instead of selecting an existing Canvas term.

**Comment by jennlove-um** [comment]
There are also 2 terms in Canvas that don't have start end dates: Default Term and No Term.  If a user picked either of these terms from the list of available terms when adding a course to MyLA, they should also have to enter in term start/end dates.

**Comment by jennlove-um** [comment]
![image](https://user-images.githubusercontent.com/39634416/50911053-10249f80-13fd-11e9-92df-615a62149a41.png)

The 7-week ALA course has override dates in the course itself.  Should we consider pulling course-level override dates into MyLA?  Right now we're relying on term start and end dates, but if instructors override those on a course level, it would be more appropriate to use those override dates in MyLA.

**Comment by jonespm** [comment]
Yeah that last idea seems good. I'd like to rely on Canvas as a source. I see the start_at and conclude_at in the data feed. Currently this table is not being pulled down from Canvas, so we'd have to add some code to the cron to fill in this data (if it exists and isn't populated in MyLA) I think it might be too late to add it for the next release but would be nice for the following one.

I like the temporary idea of putting this course in another separate term, then just deleting that after 7 weeks. This all sounds good, thanks for the extra information.

**Comment by jonespm** [comment]
I created a spring project in github and moved this over to there.

**Comment by DanielDugan** [comment]
Demonstrated to Jennifer Love the UI improvements.
Working through models.py to pass the changed dates successfully.
Going to be tight on the deadline.
Will work to document code well so that review is simple

**Comment by DanielDugan** [comment]
<img width="793" alt="screen shot 2019-01-25 at 11 34 38 am" src="https://user-images.githubusercontent.com/7157421/51759117-7c5a0100-2095-11e9-806b-b0da237282a6.png">

**Comment by DanielDugan** [comment]
<img width="768" alt="screen shot 2019-01-25 at 11 34 23 am" src="https://user-images.githubusercontent.com/7157421/51759128-854ad280-2095-11e9-89e7-68e2e52871ff.png">

**Comment by DanielDugan** [comment]
Please let me know if any changes are requested

**Comment by pushyamig** [comment]
I removed Daniel as assignee and I suppose this is still not done

**Comment by jennlove-um** [comment]
This is not done yet, and we should spend some time figuring out how to address this.  I think we should still look at pulling in the override term dates from Canvas courses.  Then we use those dates if they are there and use the regular term dates if there is no override.

**Comment by jonespm** [comment]
I'll assign @ssciolla to this for now. I can talk about this next week. I agree that we should pull the terms (if not set) and overrides from Canvas and use those.

**Comment by jennlove-um** [comment]
Testing passes - Term dates are used if there are no overrides for start or end in the Canvas course.  If there are overrides in the Canvas course, those are pulled in instead.  If dates are manually set in MyLA, those dates are used instead of term dates or course dates from Canvas.
