### ISSUE TITLE
Text changes to assignment and files view 

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#359]
Change “Reset as my default” to “Remember my setting”
Change “Current Default” to “My current setting”
Change text to “Files accessed from week 1 to 16 by students with these grades:”  
Change “All Grades” to “All”

**Comment by pushyamig** [comment]
This is ready for testing

**Comment by jennlove-um** [comment]
Testing passes.  Text has been updated on Files Accessed and Assignment Planning pages.
