### ISSUE TITLE
Static content of JS must be coming from single file 

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#361]
A lot of the text in the Javascript file must be coming from separate JS file loaded first before individual view JS file this will help i18n future consideration.

**Comment by jonespm** [comment]
This is related to #353. There will probably be a larger issue with back and frontend considerations.

**Comment by justin0022** [comment]
I think it would be good to add [Webpack](https://webpack.js.org/) to handle the JavaScript bundling/minifcation/transpilation. 

Webpack can be set up to handle multiple entry points, so each webpage (i.e. '/assignments', '/grades') will pull in its respective bundled JS. 

Adding Webpack will provide the following benefits:
* ability to organize JS code into modules
* support for older browsers by transpiling new JS language syntax into older syntax using [Babel](https://babeljs.io/)
* faster performance of application, as tree-shacking, bundling, and minifaction reduces the total JS size
* ability to test unit-test JS code by importing modules.

**Comment by justin0022** [comment]
Also, adding a JavaScript linter would help enforce a style convention and reduce a whole class of trivial & annoying bugs. I personally prefer [Standard](https://standardjs.com/) but open to using others.
