### ISSUE TITLE
Provide a way to anonymize data display for demo and training

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#362]
Create an admin option to anonymize the display of course data in visualizations.  The student names and course names are the most important data to anonymize.

This will allow us to demo and train on MyLA screens without compromising student data.

**Comment by jonespm** [comment]
We were brainstorming and the quickest way to do this would probably to provide a checkbox in the course admin page that would make this anonymous. 

I don't think we need it fully anonymous, it can be pseudo-anonymous. As long as there's no way of mapping it back it's good but it should be consistent. (For example the user "Bob Smith" should be 

Then we could possibly run this through faker to generate fake names. Or we could just have something like User X. (Where X is a fixed value but may not be ordered)

https://github.com/joke2k/faker

If we used hash in the input we could get predicable output
`fake.seed_instance(ctypes.c_size_t(hash('Bob Smith')).value)`
== Jay Garcia

We'd probably want to salt this for extra protection, but that's not a big deal. 

For things like courses we'd probably just use a fixed value. 
For assignments and files (if we wanted to anonymize that) we'd probably have to write a custom method but maybe it just had "Assignment X" where X can be any number it would be fine. Maybe this could be just another constrained salted hash.

Sounds like a good idea. I was thinking of applying this into the cron.

**Comment by jonespm** [comment]
We're working on this in a separate project for now, will merge over here later.

https://github.com/tl-its-umich-edu/myla-anonymizer

**Comment by jonespm** [comment]
This is a separate project so closing.
