### ISSUE TITLE
move away from AngularJS in Assignment view  

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#363]
AngularJS is an old framework, entered into [long term](https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c) support and we should move away from it for assignment view.

2 option for the re-design For "Assignment Due By Date"
1. generate the tabular view of assignment using D3, the challenge here is D3 don't have table element as D3 element`Rect` for creating Bar graph.  so we need to use HTML table element in combination with D3 elements. we get into tricky alignment issues when you need to join HTML table with D3 Rect element 
2. Rewrite the entire table and bars(actually CSS fill) in the plain JS instead of AngularJS

"Progress Towards Final Grade" view will still remain in D3.

**Comment by justin0022** [comment]
Could a combination of the two options be used? 

Currently D3's used for generating the bars, and so to remove Angular, so the "Progress Towards Final Grade" component can be left as is. The "Assignments Due By Date" can be rewritten in pure JS. 

If you want some help on this, I can take this on.

**Comment by pushyamig** [comment]
@justin0022 D3 is used for generating the bars for the "Progress Toward Final grade" pieces and the design for that will continue like that. The tabular view below is where it is heavily depended on angularJS that's where the design change is needed. Writing it in PlainJS is feasible to do but writing the tabular piece using D3 is a bit tricky.
