### ISSUE TITLE
Extract into API?

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#371]
https://github.com/tl-its-umich-edu/my-learning-analytics/blob/e222505f56532c86cbd0bf2bbfcfc6ac86351aef/dashboard/templates/base.html#L70-L74

Can the dashboard global variable be extracted into its own API layer?

**Comment by jonespm** [comment]
What do you mean by API layer? 

This was mostly to be able to pass data from the backend and have it available in the frontend (which is used in api calls).
 
Do you mean that this should be an api call rather than defining a variable in the template? How would it know what course_id to return?

**Comment by justin0022** [comment]
Ya, I was thinking an API call. Wouldn't `window.location.href` contain the `course_id`? An endpoint can just return `settings.UDW_ID_PREFIX` + `course_id` to the frontend.

Having a global `dashboard` variable is a bit dangerous, since there can be namespace clashes (imagine importing a 'dashboard' library via CDN that exposes `dashboard` as a global) and since any JS on that page can mutate this variable.

**Comment by jonespm** [comment]
Yeah it should contain the course id, we'd have to parse it out though. This should at least be renamed if it remains. We wanted to change all references of dashboard but must have missed this one. 

I believe UDW_ID_PREFIX is also renamed in another PR that hasn't yet been merged. We're currently waiting until a little later this week to release for the term here then plan to just merge everything outstanding.

**Comment by justin0022** [comment]
Good to know, sounds good to me.
