### ISSUE TITLE
All API urls should have client side caching enabled

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#374]
We've noticed that many of the URL's take awhile to load and only really change once every 24 hours. We should implement client side caching to both give the user a better experience as well as the server an easier time. This would also greatly benefit the new courses enabled api.

Some screenshots

Before (Almost a second to generate this last URL)
![image](https://user-images.githubusercontent.com/27447/51636446-4434b000-1f27-11e9-98d3-85cb3c2f53f9.png)

(Since it hasn't changed and browser is caching it it's instant)
![image](https://user-images.githubusercontent.com/27447/51636466-50b90880-1f27-11e9-834b-a1955e0b55d6.png)

The best solution might be to calculate when the next run of the cron will be and use that value, but a set value should be good for now.

**Comment by jonespm** [comment]
To test this you'd have to have your Developer Tools open to the network page and notice that it comes from the memory or disk cache (in Chrome) after the first request. This should cache each URL as you navigate (for instance if you change the view options. 

In addition all of the views should have the same result as before without the caching. I don't expect to see any regressions from that but some basic testing that the tool works as expected should be tested.

**Comment by jonespm** [comment]
Many browsers (like Chrome) will force a refresh if you go to the URL directly, it will only cache these if they are included in another page. I verified that including the courses_enabled URL via ajax (like in Canvas) also tests this but that is the big area it should be verified. I can work with Pushyami if needed to verify that is working.

**Comment by pushyamig** [comment]
adding the env variable CLIENT_CACHE_TIME: 24 hours (86400 sec)
