### ISSUE TITLE
Calls to set_user_default_selection should be POST or PUT

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#376]
The calls to set_user_default_selection are via GET. 

A GET request should be able to be cached and have a predictable result.
https://softwareengineering.stackexchange.com/a/188861/169485

In HTTP the correct very is PUT to update, or POST to create (or often also update).

**Comment by jennlove-um** [comment]
I am able to set and reset the defaults on both the Files Accessed and Assignment Planning pages.  The correct default displays for the student.
