### ISSUE TITLE
browser caching is not helping with default setting option when changed by user

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#384]
All the GET calls are cached now that also means the GET call to get the defaults call too. When a user changes there a default setting in file/assignment view and refreshes or pop out from the views momentarily in the site and come back again since the get_default call is cache it serves the content from the cached value. The easy solution would remove the get_default call from the cached configuration. But looking for a solution that let to wipe the cache on demand during the setting of the default.

**Comment by pushyamig** [comment]
Test Plan: from the chrome dev tool Network tab
1. `get_user_default_selection?default_type=` is removed from cached option so this URL will make a DB call to get the data.
2. All the other call that gets the data like `grade_distribution`, `file_access_within_week`, `assignments`, `info', `courses_enabled` will be coming from the cache if available during the 24 hour period.

**Comment by jennlove-um** [comment]
The selected default displays correctly when changed within the 24 hour period.  It is not coming from the cached data.
