### ISSUE TITLE
Improve the courses admin view to display more details in the columns

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#387]
The courses admin view currently only displays the course name. It would be more helpful at a glance to display more details.

A mockup is below

![image](https://user-images.githubusercontent.com/27447/52240754-c4500380-289f-11e9-80d7-e3b62a052685.png)

**Comment by jennlove-um** [comment]
Tested - The admin course view now shows the course id, name, term, show grade counts, and course view options for each course.
