### ISSUE TITLE
Ed App Id should be configured in settings

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#391]
The Ed App Id here is hardcoded this should at least come from settings. 

Maybe this is part of a larger refactor to support additional apps?

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/ccd1fa2569951dff45f6dfa0e4efe221e5348abf/dashboard/cron.py#L237

**Comment by andrew-gardener** [comment]
Looks like this was done in #520
