### ISSUE TITLE
AttributeError in CourseViewOption json if course does not exist

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#392]
If the course id lookup fails and course does not exist there is an exception thrown. This should be caught and logged rather than causing an issue.

`dashboard.models.DoesNotExist: Course matching query does not exist.`

**Comment by jonespm** [comment]
To test this, you'll have to insert a row in course_view_option as deleting a course via the UI cleans this table up. So it will probably need a dev to verify.

**Comment by pushyamig** [comment]
I think there is a foreign key constraint is enabled if I Try to insert a non-existing course it is erroring saying 
```[23000][1452] Cannot add or update a child row: a foreign key constraint fails (`myla_test`.`course_view_option`, CONSTRAINT `course_view_option_course_id_2efc2b59_fk_course_id` FOREIGN KEY (`course_id`) REFERENCES `course` (`id`))```

I don't think we can test this unless you relax the constraint and test it via sql. I don't feel that is necessary. I will mark this as Done. I see that whenever the course is deleted from the admin UI both the tables clear up
