### ISSUE TITLE
Remove private urls from cache

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#394]
Having the home page in cache makes it so when you login it doesn't reflect the new status of the main page, this should be removed from the cache.

Relates to #374

**Comment by pushyamig** [comment]
@jennlove-um do we need this fix for current production?

**Comment by jennlove-um** [comment]
It depends on how it impacts users.  Do they see the correct home page when they login via the link from Canvas?

**Comment by pushyamig** [comment]
links and LTI configuration always have course/22222. So users might now notice it unless they bookmarked the home.

**Comment by jonespm** [comment]
I "believe" the only use for the homepage is for admins to get quick access to admin (after logging in). Currently students going to this page and logging in won't see anything useful.

**Comment by jonespm** [comment]
I'm re-opening this, I believe we should remove all private urls from the cache for now. I'm seeing some things that aren't working as I expect. I believe Django is caching these server side and leading to regressions like when using the "view as user". I believe it's safer to revert this rather than roll this out for now and revisit later.
