### ISSUE TITLE
Don't pull inactive student information into user table

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#401]
students who withdrawal from a course are put into inactive status, Those students will not be able to access the course. 
Here is a Canvas doc outlining the limitations imposed by inactive status: https://s3.amazonaws.com/tr-learncanvas/docs/CanvasEnrollmentStatusComparison.pdf

**Comment by andrew-gardener** [comment]
I think this was already taken care of unless there was something else you had in mind?
https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/dashboard/cron.py#L135
https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/dashboard/cron.py#L328

**Comment by pushyamig** [comment]
The user table doesn't seem to pull the inactive student information, I don't know if it was a problem and solved in between. I am closing this issue as resolved
