### ISSUE TITLE
Updates to the "files" data to support other caliper events

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#402]
Currently update_with_bq_access is only pulling down views for the files. Here's some changes that I'd like to implement to support more tools

- Also support ViewEvent/Viewed
  - This is the more appropriate event for what we're visualizing. However it looks like Canvas is currently only sending NavigationEvent/NavigatedTo for the files at least, both of these should be supported pretty similarly with the same query
- Change the "Files" view around to be more generic

We'll need to find a course that has some of these "Viewed" events from the textbook like VitalSource or Runestone first to implement this.

**Comment by pushyamig** [comment]
For **Leccap data** the query to use is. Leccap data provides only short canvas course/user id
```
select 
CAST(SUBSTR(JSON_EXTRACT_SCALAR(event, '$.object.id'), 48) AS STRING) AS resource_id,
JSON_EXTRACT_SCALAR(event, '$.federatedSession.messageParameters.custom_canvas_user_id') AS user_id,
JSON_EXTRACT_SCALAR(event, "$.federatedSession.messageParameters.custom_canvas_course_id") As course_id,
datetime(EVENT_TIME) as access_time
FROM event_store.events
where JSON_EXTRACT_SCALAR(event, '$.edApp') = 'https://leccap.engin.umich.edu/#applicationName=Lecture+Capture'
and type = 'MediaEvent'
and JSON_EXTRACT_SCALAR(event, '$.action') = 'Started'
and JSON_EXTRACT_SCALAR(event, '$.federatedSession.messageParameters.custom_canvas_course_id') is not null
and JSON_EXTRACT_SCALAR(event, "$.federatedSession.messageParameters.custom_canvas_course_id") like '%298053%';
```
Leccap Additional insights: ed_app is used for Session#loggedIn events

```select type, action  From event_store.events where ed_app ='https://leccap-beta.engin.umich.edu/#applicationName=Lecture+Capture';```
looking at different leccap ed_app
`select distinct ed_app from event_store.events where ed_app like '%leccap%';`

For **Files canvas** data, only those 2 ed_app generates file looked event as a form of navigation events. You may also find a bunch of cluster machines generated event which can be ignores as these are duplicates of user action. `http://a1770-9792514.cluster32.canvas-user-content.com/ `


```
select event, CAST(SUBSTR(JSON_EXTRACT_SCALAR(event, '$.object.id'), 35) AS STRING) AS file_id,
                    SUBSTR(JSON_EXTRACT_SCALAR(event, '$.membership.member.id'), 29) AS user_id,
                    datetime(EVENT_TIME) as access_time
                    FROM event_store.events
                    where JSON_EXTRACT_SCALAR(event, '$.edApp.id') IN UNNEST(['http://m.canvas.umich.edu/', 'http://umich.instructure.com/'])
                    and type = 'NavigationEvent'
                    and SUBSTR(JSON_EXTRACT_SCALAR(event, '$.object.id'),24,10) = 'attachment'
                    and JSON_EXTRACT_SCALAR(event, '$.action') = 'NavigatedTo'
                    and JSON_EXTRACT_SCALAR(event, '$.membership.member.id') is not null
                    and SUBSTR(JSON_EXTRACT_SCALAR(event, "$.group.id"),31) IN UNNEST(['17700000000245664']);
```

**Comment by pushyamig** [comment]
one thing to notice is files navigation events doesn't have the file name in the caliper event and we are using UDW to pull that info. Leccap video started events do have the name of the video as part of the leccap. we might need to think about how to load data to `file` and `file_access`tables w.r.t to file/video related data.

Another fact that is going to change may be in a couple of weeks is Instructure will be populating the canvas file name along with file id in caliper event as told by @johnpj. In that case we need to think through the need for the `file` table

**Comment by johnpj** [comment]
...

> Another fact that is going to change may be in a couple of weeks is
> Instructure will be populating the canvas file name along with file id in
> caliper event as told by @johnpj <https://github.com/johnpj>. In that
> case we need to think through the need for the file table
>
When we talked to Oxana a few weeks ago, she said the actual file names
would be in a mid July release.

**Comment by pushyamig** [comment]
When pulling the data from BQ whether it is files/ videos I think the DB table should have 2 columns  `resource_type:[files, video]` and resource_name: [canvas, leccap, kaltura]
file => canvas
video => leccap/kaltura
This way we can differentiate the data from the DB

From the UI perceptive (from the last meeting), it is agreed to show generalize categories like `Files` and `Videos`.

**Comment by jonespm** [comment]
> When pulling the data from BQ whether it is files/ videos I think the DB table should have 2 columns `resource_type:[files, video]` and resource_name: [canvas, leccap, kaltura]
> file => canvas
> video => leccap/kaltura
> This way we can differentiate the data from the DB

I think having resource name in the database is enough. The types can be something that's configured in the json settings for those resources. We wouldn't really need this extra column in the database. If we want it in the database (for ease of external queries outside of the app) I'd probably put this in a separate table. 

table: resource_types
columns: id, type, resource_name

**Comment by jonespm** [comment]
I'll look at adding those queries. Looking at them I wonder if we can get the "magic numbers" out of the data and/or if those would ever cause any problems? 

For instance the 48 in
`CAST(SUBSTR(JSON_EXTRACT_SCALAR(event, '$.object.id'), 48) AS STRING) AS resource_id,`

Probably could just be
`CAST(REGEXP_EXTRACT((JSON_EXTRACT_SCALAR(event, '$.object.id')), '.*/(.*)') AS STRING) AS resource_id`

If we *always* want whatever is at the end of the URL.

**Comment by pushyamig** [comment]
I feel having in DB is better than Json

**Comment by pushyamig** [comment]
>If we always want whatever is at the end of the URL. Though if we're just going to leave the id as strings, we probably don't even have to do this at all and can just leave it "as-is"
I see one problem using the id as-is since file data don't provide that info so we are using the concatenation/env variable to combine the url + id. If we load the leccap is as is then in the file login in `views.py` this needs to be cognizant of 
``` 
if leccap 
     url == id
if file
   url == prefix+id
```

It's tricky we different types of data don't follow the same pattern. 
I think canvas caliper event can provide a direct link to the file in the events if requested  in long term Thoughts?? @johnpj

**Comment by jennlove-um** [comment]
Testing passes: Resources view is correctly showing Lecture Capture and Files resources for courses that have multiple types of resources.
