### ISSUE TITLE
Error on localhost with static files after merging #346

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#405]
I merged this and tested it locally but it's not starting up when connecting to the port. I don't have time to debug this today and may it needs a PR after this one? It does start up on our dev server in Openshift.

Are you able to get it started up locally? It looks like in the local container the /code/static directory doesn't exist.

```
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'bootstrap/dist/css/bootstrap.css'
```

If this other exception is added this works however I guess that would prevent static files from being "reloaded". Though that seems okay.

```
diff --git a/docker-compose.yml b/docker-compose.yml
index 8d255fa..55dcd81 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -35,6 +35,7 @@ services:
       - .:/code
       # use the container's node_modules folder (don't override)
       - /code/node_modules/
+      - /code/static/
     ports:
       - "5001:5000"
       - "3000:3000"
```

_Originally posted by @jonespm in https://github.com/tl-its-umich-edu/my-learning-analytics/pull/346#issuecomment-466575465_

**Comment by jonespm** [comment]
Did you intend to run the collect static outside the dockerfile? Or have it do some different process for these files that maybe wasn't documented?

**Comment by andrew-gardener** [comment]
my bad, I only ever ran it in with `DJANGO_DEBUG=True` which doesn't require the static files

adding the `- /code/static/` doe sfix it (will make a PR)

**Comment by jonespm** [comment]
Ah I see, I had it false on localhost for DEBUG, mostly because the debug toolbar was connected to this property and I wanted to turn that off. I was thinking of switching that to a different env variable.

However, If we have DJANGO_DEBUG=False do that mean that it will pick up the static files from the local too? Maybe we could just document that or else [set up compose overrides](https://docs.docker.com/compose/extends/#example-use-case)? 

I kind of want to document the best recommendation for localhost development. This *sounds* like it would be 

- DJANGO_DEBUG=False
- Have a separate env for django debug toolbar 
- Document that if you set DJANGO_DEBUG=True locally you need to mount the static volume

I'm also fine to just mount the static volume as I *feel* like changing those dependencies might require rebuilding the image anyway. Just merging this would solve this if none of those 3 things matter. ;)

**Comment by jonespm** [comment]
I'm merging and #406. If this isn't working for out for us (mounting the static) and we come up with a better way of doing it locally to improve development workflow we can revisit this.
