### ISSUE TITLE
Files view for certain courses show bars greater than 100%

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#412]
For some courses, File view bars length is showing greater than 100 % which is odd. What that means is as an example, with a bar length of 115% means that 115% of students accessed the file which doesn't make sense. We need to rethink the logic that generating this number

**Comment by zqian** [comment]
I had a fix to this -- added one more check to the select query to match course id in the user table.

**Comment by jennlove-um** [comment]
Testing passes in dev.  None of the pilot courses are showing more than 100% file views.
