### ISSUE TITLE
add initial React+Webpack+Django plumbing

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#420]
This issue handles how React and Django communicate with each other. The `Web pack` is doing the heavy lifting and building the react components and `django-webpack-loader` is helping in finding the react static assets to django.

**Comment by pushyamig** [comment]
@andrew-gardener I see that in the `settings.py`  `WEBPACK_LOADER` variable is referenced twice, I supposed it is by mistake?

**Comment by pushyamig** [comment]
The docker build is much slower now is there a way to make this faster and I also see a lot of warning during the docker build some are related to babel.

**Comment by justin0022** [comment]
I'll look into this tomorrow - I suspect swapping out Yarn for NPM and running the command via `npm ci` might speed up the dependency installation.

**Comment by andrew-gardener** [comment]
I'll consider this done for now (will reopen if another issue comes up)
