### ISSUE TITLE
switch over assignment planning dashboard

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#422]
This has 2 views to it and both need to be served up from the same page 

1. Assignment planning tabular view 
2. Assignment progress view

We show 2 different types of view based on the logged in the user.

Aggregation view where it is generic to anyone who has access to the visual
Student view where we overlay what is the student current grade in the grade distribution.
The view needs to know logged in user role and show respective content in the view.

**Comment by pushyamig** [comment]
@justin0022 I am also assigning this to me in case if you want to split the work as this is a big chunk

**Comment by pushyamig** [comment]
In assignment view and files view both has a 1. dropdown box 2. checkbox to select the default option. This could be separated as a generic component that populates the dropdown and based on the view and would have an action event that does the PUT call for storing the user selected default.

**Comment by justin0022** [comment]
Merged: https://github.com/tl-its-umich-edu/my-learning-analytics/pull/447
