### ISSUE TITLE
clean up the React code that has lot of visuals not related to MyLA project

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#428]
Currently, I see a lot of visuals in the code like `donut chart` `Sankey chart ` not related to the project. These things needs to be removed to keep things simple and clear

**Comment by justin0022** [comment]
Those visuals are components that can be used for future visualizations. I'll remove them, since the components exist [here](https://github.com/justin0022/dashboard).
