### ISSUE TITLE
switch over course index page

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#429]
Might just keep the existing styling as currently done. 
![Screen Shot 2019-03-12 at 7 44 07 AM](https://user-images.githubusercontent.com/8579775/54197687-fbb36080-449a-11e9-8c8f-a663ca089649.png)

**Comment by justin0022** [comment]
Should we close this issue, or do we close once the review is complete?

**Comment by pushyamig** [comment]
I think we should close this issue as work has been done, code reviewed and merged to React branch.
