### ISSUE TITLE
Filter for grade group on Files Accessed is not calculating correctly

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#443]
On the Files Accessed page, the filter selection should show the percent of only the students in the selected group who viewed a file.

For example, if there are 100 students in the class, the All filter shows what percent of all 100 students viewed the file: X/100 students viewed the file.

For the other filters, the denominator becomes the number of students in the selected group.  So if 20 students have 90-100%, then the 90-100% filter shows what percent of those 20 students viewed the file: X/20 students viewed the file.

This came up because in one course, I could see that 99% of all students viewed the file.  But when I filtered to the 90-100% students, it only showed 42% viewing the file.  If almost all students in the whole class viewed the file, it didn't make sense that less than half of A students viewed the file.

**Comment by jonespm** [comment]
Yeah, that is confusing when using the filter. Some groups that don't have low grades, going to 70-79% looks like. It's not that 1% of the students have viewed, but really only 1 student has that grade. . . 

![image](https://user-images.githubusercontent.com/27447/54447989-1a2a8d80-4721-11e9-80aa-f8377def8c77.png)

and 80-89% looks like 
![image](https://user-images.githubusercontent.com/27447/54448011-26aee600-4721-11e9-9669-3cf0368d1ed0.png)

So it should be 100% for everyone in this 70-79% case, and 100% and 50% for the second case (rather than 4 and 2%) and may or may not be colored if it was viewed.

**Comment by zqian** [comment]
The merge of Pull Request somehow closed the issue automatically. Re-open it to indicate that the testing is needed.

**Comment by jonespm** [comment]
@zqian This is the documented workflow
https://github.com/tl-its-umich-edu/my-learning-analytics/wiki/MyLA-Workflow

If we leave tasks open waiting for QA then it's confusing if the task is actually ready to QA or not. It seems clearer for QA to just re-open a closed task if it fails.

**Comment by jonespm** [comment]
The only alternative to this workflow I can think of is to put BOTH the issue and pull requests on the project board. The pull request when they are merged would go to a separate swimlane and the issue would remain open without any automation. We'd have to get a lot more disciplined on

- Having better references from the pull requests to the issues in the pull requests
- Having better naming standards for the pull requests
- Adding the current project board (and possibly milestones) to both the pull requests and issues

I haven't seen any good examples out there of project boards that manage pull requests and issues in separate (or combined) swimlanes without it being overly confusing . . .

**Comment by jennlove-um** [comment]
@jonespm From the QA perspective, I'm okay with having tickets closed to indicate that all development work is done.  Since the issue shows up in the Review/QA column, that's a clear enough indication that it is ready for testing.

**Comment by jennlove-um** [comment]
Testing seems good in that the numbers are sensible when I apply the filters.

However, @zqian, if you have a minute to help me figure out how to verify them against what's in the database, that would be a helpful confirmation.  I'm having a lot of trouble coming up with SQL queries that give me reasonable data to verify against.
