### ISSUE TITLE
empty assignment groups with weights resulting in incomplete progress bar

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#450]
When assignments groups are created with weights with no assignments the percent toward final grade calculation is screwed and the progress bar is not 100 %. The Assignment views design need to include this case as well.
<img width="1587" alt="Screen Shot 2019-03-16 at 10 28 12 AM" src="https://user-images.githubusercontent.com/8579775/54476713-e6aa3a80-47d6-11e9-89a9-7f466afbbbf1.png">

The proposed solution to handle this case is to fill in that gap with Place holder assignments with respective assignment groups name prepended.

**Comment by pushyamig** [comment]
Test Plan: 
1. Test the case with Assignment with weight assignments are hidden or unavailable
2. Test the case Assignment with weight without assignment hidden
3. Test the case when there Assignments no groups ( defaults to one group)
4. Test all the above cases as admin and student user.
5. I would go through all the course that we are winter pilots so we don't effect our current production courses

**Comment by zqian** [comment]
Mistakenly re-opened. Close it now.
