### ISSUE TITLE
Saving a new course with all options selected doesn't save any options

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#452]
As noted by @pushyamig , it looks like if you create a course with all of the options selected (default), it doesn't create a record in the course_view_option table. This results in no options being shown in the table (in current master) and potentially other issues.

If you uncheck any of the options it creates a course_view_option row and works as expected.

**Comment by jennlove-um** [comment]
Testing passes

1. Created a new course with all default options checked.  The course was correctly created in the database.

2. Created a new course with none of the options checked.  The course was correctly created in the database.
