### ISSUE TITLE
If course is on wrong term, there is a ValueError in assignment view

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#455]
If you have the course on the wrong term (for instance if you have a course that was given Winter 2019 in the Fall 2019 term) MyLA throws this exception.

```
  File "/code/dashboard/views.py", line 430, in <lambda>
    assignments_in_course['week']=assignments_in_course['calender_week'].apply(lambda x: 0 if x == 0 else week_list.index(x)+1)
ValueError: 5 is not in list
```

It looks like the code here is getting the minimum week from the term dates associated with the course and returning the "week". So for Fall it returns something like 36
`min_week=find_min_week(course_id)`

Then this code runs getting the max value of calendar_week from the DataFrame. which in this case is 13.
`max_week=assignments_in_course['calender_week'].max()`

There is an error because min_week (36) is greater than max_week (13)

I feel like either these should be consistent, either both using the DataFrame or both using the term. I'm not sure why it is mixed up here.

On a course where the term is correct this min_week "seems" to be correct. I'm not sure which way works best yet.

**Comment by jonespm** [comment]
I don't know if this is a high priority issue, just assigning it @pushyamig and @zqian  I haven't made any commits to this method. Hopefully this data is correct but seems like there might be a problem I'm overlooking here.

**Comment by jonespm** [comment]
Ok, I see the logic behind this now. It has to get the week the semester starts in order to determine how many weeks before it's due. I thought we'd said at one time we wanted to the the actual term's course info from course_dim (either the term there or the start_at_conclude_at overrides).

I don't see that one open though I felt like I'd filed it (maybe just talked about it).

I'll create that issue instead.

**Comment by jennlove-um** [comment]
@jonespm Is there something to test for this one?

**Comment by jonespm** [comment]
Yeah I think the test was to manually put a course in the wrong term. Like put a course that is in Fall 2019 into Fall 2015. Then try to view it in the assignments page.

Since the term and dates are being pulled via cron from the UDW this shouldn't happen anymore but still worth checking to see if it's an issue.

**Comment by jennlove-um** [comment]
Testing passes - I'm unable to reproduce the error.
