### ISSUE TITLE
When adding a course in the course admin adding a non-numeric id results in 500 error

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#459]
If you're in the admin interface and add a course using a non-numeric id (like using text, "test") it says

**Server Error (500)**

This error should be handled better rather than throwing this error

**Comment by jennlove-um** [comment]
Testing passes.  When I enter a non-numeric id, it does not save and an error message indicates that the course ID must be an integer value.

One curious note: The field prevented me from entering any non-numeric characters except e, . (period), - (minus), and +.
