### ISSUE TITLE
[React] Customize styling and theme

### ISSUE THREAD

**Issue by Adonais0** [tl-its-umich-edu/my-learning-analytics#462]
Not a high priority issue, but better to spend some time think of. 

Currently, we are using the default material styling. In the future, we'll want to add customized themes to our design to better fit [UofM color branding guidlines](http://vpcomm.umich.edu/brand/style-guide/design-principles/colors) and provide better visual accessibility.

Reference: https://material-ui.com/customization/themes/

**Comment by pushyamig** [comment]
This is for later as well, just important for this react branch getting merged master

**Comment by ssciolla** [comment]
We have a newer issue about this, but I want to establish the link so we close both. It's issue #673.
