### ISSUE TITLE
Adding new items to index page causes formatting issues

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#465]
![Screen Shot 2019-03-27 at 3 47 31 PM](https://user-images.githubusercontent.com/8836578/55117330-b2246180-50a7-11e9-877f-8a5ca46074f7.png)

I think it may be because here:
https://github.com/tl-its-umich-edu/my-learning-analytics/blob/517e1baae1f569ce4cf4f40f0437dd0bedf696f3/assets/src/containers/IndexPage.js#L30-L35
The `SelectCard` component should be wrapped in a `Grid` component with an explicitly set width.

**Comment by jonespm** [comment]
I think the idea was it would probably go 3-4 over and then start up another row. If we ever got to more than 9 that might start to get a little confusing and need a larger redesign. ;)

**Comment by justin0022** [comment]
Getting to 9 would be quite the milestone!
