### ISSUE TITLE
data loading problems with certain browser version FF and Safari

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#466]
For certain version of Safari(11.1.2) and FF version(60.5.2 64-bit) the FetchAPI is not able to load data Json content in FF throws `JSON.parse: unexpected character`
 and Safari `Unhandled Promise Rejection`

![Screen Shot 2019-03-28 at 11 22 59 AM](https://user-images.githubusercontent.com/8579775/55181644-6f738f80-5162-11e9-9e50-917c7b2dfac6.png)

<img width="961" alt="Screen Shot 2019-03-28 at 11 24 11 AM" src="https://user-images.githubusercontent.com/8579775/55181647-73071680-5162-11e9-97e7-0514bf96e568.png">

**Comment by justin0022** [comment]
Resolved here: https://github.com/tl-its-umich-edu/my-learning-analytics/pull/468
