### ISSUE TITLE
Support Google analytics with React

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#470]
The current implementation uses Google analytics for tracking purpose, we still want to support that as apart of that effort

https://medium.com/alturasoluciones/how-to-set-up-and-use-google-analytics-in-react-apps-fb057d195d13

**Comment by jonespm** [comment]
I made a small fix on #463 that should be incorporated here. I feel like getting the GA ID into the react will be the biggest effort. React has some way of reading environment variables right?

**Comment by pushyamig** [comment]
https://medium.com/@trekinbami/using-environment-variables-in-react-6b0a99d83cf5. This article says it should be. I played around it a little bit but couldn't make it work. But seems to be possible

**Comment by pushyamig** [comment]
I think with the implementation of [this](https://github.com/tl-its-umich-edu/my-learning-analytics/pull/525) we have the GA id coming from the BE as a JS variable we don't need path find your way for reading Environmental variables. 

Implementing this with React components leads to tracking 
https://medium.com/alturasoluciones/how-to-set-up-and-use-google-analytics-in-react-apps-fb057d195d13

**Comment by pushyamig** [comment]
don't need to be done as part of the react branch can be done after the merge
