### ISSUE TITLE
Have relative url's for fetching data from Backend

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#482]
Currently, all the [URL's](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/react/assets/src/service/api.js) for grabbing data seems to have ` localhost` this needs to be changed so that could also work for test/prod env

**Comment by jonespm** [comment]
I don't think you can assume the back and frontends will be on the same server. Backend domain name will probably need to come from an environment variable.

**Comment by jonespm** [comment]
Also you'll have to probably look at CorsMiddleware to get this to work in the backend in a non-localhost scenario.

**Comment by justin0022** [comment]
> I don't think you can assume the back and frontends will be on the same server. Backend domain name will probably need to come from an environment variable.

Okay, so we can't assume that the baseURLs of the API endpoints and MyLA are the same? Perhaps the API baseURL can be added to `myla_globals` variable.

**Comment by pushyamig** [comment]
To me currently the way this is setup Both BE and FE are running on the same server. We can safely assume that both URL's are the same. We could add BaseURL ( like `localhost:5001` and `dev.myla`) to `myla_globals`  but could also fetch using `window. location` for API call for fetching data. @jonespm thoughts??

**Comment by jonespm** [comment]
Seems like it's just fine to use relative urls rathe than having any URL at all if these are going to be run on the same server. I put in a patch for this and it's working on both localhost and on the test server.
