### ISSUE TITLE
Switch API's to djangorestframework

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#486]
Something I've wanted to do for awhile is switch all of the api's over to using [djangorestframework](https://www.django-rest-framework.org/). This can be done alongside the React work. This should make adding api's in the future easier and more consistent. The backend is mostly used more for providing REST endpoints now with React taking over the views.

**Comment by justin0022** [comment]
Will switching over to the django rest framework change the way that users log in/authenticate? If it does, I may hold off on implementing the login page (https://github.com/tl-its-umich-edu/my-learning-analytics/issues/424) until the APIs get switched.

**Comment by jonespm** [comment]
Going to close this as I think we'll just do graphql for all of this instead.
