### ISSUE TITLE
Switch MyLA to pull data from UDP instead of UDW

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#489]
The pilot versions of MyLA used data from the UDW.  With the UDP available, we need to switch to pulling the data from UDP instead.

**Comment by zqian** [comment]
FYI: here updated link of UDP Documentation: 

https://docs.udp.unizin.org/ucdm/canvas-to-ucdm.html

**Comment by ssciolla** [comment]
Okay, I have put in some initial work that hopefully get us organized, or at least start thinking about this more. I've identified in the following queries from `cron.py` that will need to be re-written to use data from the UDP. 

- [] A term query from `update_term`
- [] A course query from `verify_course_ids`
- [] A user query from `update_user`
- [] An assignment group query from `update_groups`
- [] An assignment query from `update_assignment`
- [] A submission query from `update_submission`
- [] A weight consideration query from `weight_consideration`
- [] A resource query from `update_canvas_resource`.

To help with this effort, I have started work in my [issue-489-set-up-cron-queries-refactor](https://github.com/tl-its-umich-edu/my-learning-analytics/compare/master...ssciolla:issue-489-set-up-cron-queries-refactor). In that branch, I've included reformatted versions of these eight queries, along with the skeleton of a JSON file called `cron_queries.json`. This is mostly still the brainstorming stage (nothing is hooked up yet to the project), so if you like or don't like or have ideas about this approach, let me know.

**Comment by ssciolla** [comment]
In speaking with @jonespm, I'm now thinking that this may be the right (if not the ideal) time to talk about our current MySQL data model. I will create an EER diagram for us to look at in our next meeting.

**Comment by rpfernandezjr** [comment]
I see that this is in progress, and is labeled as `priority`, but is there an ETA on when this will get released?

**Comment by jennlove-um** [comment]
Still waiting for the metadata table from Unizin.  The June 2022 release was delayed.

**Comment by jennlove-um** [comment]
Research whether we need the first name and last name from the UDP.  Can we trust the LTI launch data instead and use that data for the profile?
