### ISSUE TITLE
Move MyLA to AWS OpenShift

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#490]
MyLA development, test, and production environments need to be moved to OpenShift on AWS.

**Comment by pushyamig** [comment]
This is pretty much close to being done, Test/Dev instances are setup. The only thing remaining is the Prod instance, DB instance is created and should be estimated to be done end of this week or next week

**Comment by pushyamig** [comment]
We have migrated all the prod and non-prod instance.
