### ISSUE TITLE
Penetration testing for MyLA

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#491]
Schedule and perform penetration testing for MyLA.

**Comment by jennlove-um** [comment]
I talked to Ross Geerlings about this and requested testing in June.  He agreed that seemed feasible and will reach out in the first week of June to schedule testing.

**Comment by pushyamig** [comment]
This is scheduled to start from Aug 14 and testing will continue for a couple of weeks
