### ISSUE TITLE
Files viz issues with responsive/styling

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#505]
Files view is functional but seems to have responsive/styling issues as noted [here](https://github.com/tl-its-umich-edu/my-learning-analytics/pull/464#issuecomment-485961487)

**Comment by johnpj** [comment]
You may want to look in /assets/src/components/d3/createResourceAccessChart.js 

line 75:

> Const [mainWidth, miniHeight] = adjustViewport(width, height, mainMargin)

and line 96:

> .attr('width', mainWidth + mainMargin.left + mainMargin.right + miniWidth + miniMargin.left + miniMargin.right)

**Comment by ssciolla** [comment]
Today we discussed that truncating the resource label names based on the available horizontal space is in scope for this issue. This work follows up on work on issues #837 and #854.

**Comment by jonespm** [comment]
I don't see any PR's specific to this one, was it just incorporated by another fix?

**Comment by ssciolla** [comment]
This was or should have been resolved by PR #910.

**Comment by jennlove-um** [comment]
Testing passes. The Resources Accessed view displays without the responsiveness issues when resized.
