### ISSUE TITLE
Refactor course_view_options from /info endpoint

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#512]
Currently the `course_view_options` contains: 
```
"course_view_options": {
    "fa": 0,
    "ap": 1,
    "gd": 1
  }
```

1. fields should be renamed to `files`, `assignment`, and `grades`, to correspond to the route names on the front end.
2. The values should be converted from numbers to booleans (true/false). 

This will help simplify disabling the corresponding routes.

**Comment by jonespm** [comment]
The reason they're short is to reduce the payload data size. This json is accessed by over 10000 people a day from Canvas for us so the data costs were a high consideration. I'd actually prefer to compress this down further than expand it.

**Comment by justin0022** [comment]
I'm all for small payloads, but the difference here is really miniscule. 

<img width="749" alt="Screen Shot 2019-05-02 at 2 40 00 PM" src="https://user-images.githubusercontent.com/8836578/57108689-61c4a300-6ce8-11e9-885f-f69ed7355b70.png">
<img width="753" alt="Screen Shot 2019-05-02 at 2 38 28 PM" src="https://user-images.githubusercontent.com/8836578/57108690-61c4a300-6ce8-11e9-840a-453775b9f258.png">

Before compression, the difference is 26 bytes, and even at 100,000 hits/day, we're talking less than ~3 MBs.

**Comment by jonespm** [comment]
In this file it is, but originally it was used in a file that has 100s and (hopefully) eventually 1000s of courses defined. We could be different here or be consistent with the json from that API. Seemed like there was little point in having it expanded since it was just being consumed by code. If it saves frontend dev time we could change these.

**Comment by jonespm** [comment]
Maybe we can have these expanded but look at something like msgpack https://msgpack.org for the large payload apis.

We're actually serving these up front Cloudfront which has a bandwidth charge but is more reliable. This is really why these names were like this. All of our canvas users hit retrieve a json multiple times a day that's over a 100 times larger.

**Comment by jennlove-um** [comment]
@jonespm @justin0022 Can we close this issue based on the discussion in the notes?   Or is this something we still need to talk about?

**Comment by jonespm** [comment]
I don't think this _needs_ to be done but I'm fine with it either way if someone wanted to make these more verbose. This is working as is but fixing could make it easier to debug if changed. I think I'd just close this for now and someone can re-open if they wanted to work on it.
