### ISSUE TITLE
Adding the Copyright info to the footer of each page

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#523]
Since the project will be used by other than umich, we need to come up with a way to add copyright info. currently, the code has Copyright © 2018 The Regents of the University of Michigan

**Comment by justin0022** [comment]
Added in this PR: https://github.com/tl-its-umich-edu/my-learning-analytics/pull/529

**Comment by justin0022** [comment]
Currently the copyright notice is hardcoded, but it is added to the footer of every page.

**Comment by pushyamig** [comment]
We can work on this after the react branch merged to master. The effort is small so later could be worked on
