### ISSUE TITLE
Provide a way in the UI so the admin user can switch back and forth between user

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#524]
currently, Admin can become another user so the React UI should provide a way link so that admin and switch back him like below. https://hackernoon.com/reconciling-djangos-mvc-templates-with-react-components-3aa986cf510a
![Screen Shot 2019-05-23 at 1 29 30 PM](https://user-images.githubusercontent.com/8579775/58273530-e68e6400-7d5e-11e9-833b-372ff0abc26b.png)

**Comment by jonespm** [comment]
I think if we extended from base and put some "static" areas in the footer and also kept the /login and /admin separate and out of Django that we can incorporate this without any extra work.

I created this branch here
https://github.com/jonespm/student-dashboard-django/tree/react-django-mix

Basically the React components were already in a Django template. It's mostly SPA for the views, but if you need to login or go to the admin page it will have to switch to a different page, when it comes back the views will be updated. 

The part we're going to have to rewrite is what's in the base.html <header> though I believe we can probably just set some javascript variables there and use those directly by react. This would probably even simplify the login process on #515.

**Comment by jonespm** [comment]
This will be fixed by #525
