### ISSUE TITLE
Remove code and templates for unused Django views

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#527]
In the new react the views and templates for assignments,  courses, grades, view_file_access_with_week are not needed. All of this old code should be removed.

**Comment by justin0022** [comment]
Sorry I didn't see that you assigned yourself to this issue until just now. I think I addressed most of the outstanding problems in this draft PR: https://github.com/tl-its-umich-edu/my-learning-analytics/pull/529

**Comment by justin0022** [comment]
Also this issue is related: https://github.com/tl-its-umich-edu/my-learning-analytics/issues/427

**Comment by justin0022** [comment]
Implemented here: https://github.com/tl-its-umich-edu/my-learning-analytics/pull/529
