### ISSUE TITLE
Implement features in previous header in new react header

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#528]
In the previous header there were these features

If the user is not logged in:
- Provide a login link to `settings.LOGIN_URL`

If the user is logged in
- Provide a logout link to settings.LOGOUT_URL
- Indicate the currently logged in username
- Indicate the current course id (if you're in a course

If the user is an admin
- Show the admin link to /admin

The values of whether a use is logged in and if they're an admin or not can just be provided via javascript. There's no security risk for exposing the /admin URL as it's protected from someone not admin going to it.

**Comment by jonespm** [comment]
We'll also need to add a link to "Help"

Previously this was hardcoded so this will also need a new setting, probably passed to the frontend.

The old logic added a view specific URL to the help link. This looks like it's being cleaned up in #529

**Comment by justin0022** [comment]
> * Indicate the current course id (if you're in a course

Should the course ID be displayed, or the course name? In the `React` branch the course name is currently being displayed.

**Comment by pushyamig** [comment]
Displaying Course name and not ID as it is done currently

**Comment by justin0022** [comment]
Implemented here: https://github.com/tl-its-umich-edu/my-learning-analytics/pull/529
