### ISSUE TITLE
Add API baseURL to myla_globals

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#530]
Related to: https://github.com/tl-its-umich-edu/my-learning-analytics/issues/482

I thought the baseURL of the API endpoints should be added to the `myla_globals`. Does this make the most sense?

**Comment by pushyamig** [comment]
I have posted some comments [here](https://github.com/tl-its-umich-edu/my-learning-analytics/issues/482#issuecomment-497692506)

**Comment by justin0022** [comment]
Since the API endpoints are fetched using relative URLs, I think this can be closed.

**Comment by jonespm** [comment]
Yeah, I think the only reason this would be needed is if we had a the frontend running separate from the back, but that really doesn't seem necessary in this application and would just be more complicated anyway.
