### ISSUE TITLE
add more "Resource Access" data into File Access view

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#532]
The File Access view currently only show Canvas File Access pattern. 

There are several Caliper data types inside UDP, which include video view data from lecture capture and Kaltura, eTextbook access data from VitalSource and Runestone Interactive. 

It would be beneficial to include those caliper data into the File Access view, too, and provide filter to let student view all or one specific source stream.

**This issue will focus on adding the Lecture Capture view data.** 

Here is the task list to start with, please feel free to modify:

- [x] create sample/de-identified video access events. 
- [x] make sure the above events can be loaded successfully into MyLA db. Both "file" and "file_access" table will be updated
- [x] make sure the data shows correctly in the File Access view
- [x] add filter so that student can see all events combined, or "Access Canvas Files" or "View Lecture Capture videos", respectively.

**Comment by jennlove-um** [comment]
Testing passes: Resources view is correctly showing Lecture Capture and Files resources for courses that have multiple types of resources.
