### ISSUE TITLE
Files accessed view keeps showing loading spinner

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#533]
In the files accessed view, even when `/file_access_within_week` returns no data, the spinner keeps displaying.

**Comment by pushyamig** [comment]
I don't see this issue with React branch. It correctly displays "no data message"

![Screen Shot 2019-06-04 at 10 31 31 AM](https://user-images.githubusercontent.com/8579775/58887640-fccbe680-86b3-11e9-8c73-ba826ddf9ead.png)

**Comment by justin0022** [comment]
You're right, I was looking at the react-unused-cleanup branch, not the main React branch. I'll close this.

**Comment by jonespm** [comment]
Is this fixed? I'm seeing this in the master now when the resource_access table is empty. I'm going to put in a PR that should fix this.
