### ISSUE TITLE
Grade Distribution - Give students the option to view or not view their grade line on the visualization.

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#541]
Default to not showing the grade line
Give them something to click to view their grade

**Comment by justin0022** [comment]
I'll take this on after https://github.com/tl-its-umich-edu/my-learning-analytics/pull/600 is merged.

**Comment by pushyamig** [comment]
@jennlove-um does this setting needs to be persisted in the DB? as files and assignment view has their setting

**Comment by jonespm** [comment]
I'd think it should be. We may need to start to think about a separate preferences page to have all user adjustable settings visible in one place.

**Comment by jennlove-um** [comment]
I agree.  It should work like other student preference settings.  They should be able to turn it on or off and have it persist for the course.  Thinking ahead, this one we may want to allow students to set globally for all their courses so that they can set it once for all courses or set it differently for individual courses.

**Comment by jonespm** [comment]
Yeah sounds good. This is why I think we might have to move toward a preference page. There you could set global defaults and also see site specific overrides. Could mock that up for Winter. But for now I think persisting at the site level would be fine.

**Comment by pushyamig** [comment]
I think For now I agree for course level default having a preference page by click on the Avator model they could set the assignment/files/grades. 
I think this default info can be added to the  course info `/info` endpoint or have a separate endpoint which we have already but currently getting based on the file/assignment type `get_user_default_selection` 
we can generalize this look like this 
{"files":"90-80","assignments":"5","grades":1}

**Comment by jennlove-um** [comment]
Testing passes: 

When a student checks or unchecks the Show My Grade option, the selection persists until they manually change it again.
