### ISSUE TITLE
Fix the warning messages in the Chrome Browser

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#547]
There are warnings regarding with fonts as you start navigating to the site. The number of warnings increases as you start navigating. The warning happens when the user using the browser to navigate to a view like /courses/1233/grades and not with UI flow eg, from the index page (which has grades/assignments/files) click on the grades page then warning doesn't happen.

![Screen Shot 2019-06-19 at 9 20 54 AM](https://user-images.githubusercontent.com/8579775/59858056-3d7c5e80-9348-11e9-9e81-0940ed4b903e.png)

 The warning w.r.t to fonts is happening only in chrome and not in FF and Safari. Tried a few things like setting mimeType, removed the [hash], etc did not seems to work

```{
        test:/\.(woff2|woff)$/,
        loader: 'url-loader',
        options: {
          mimetype: 'application/font-woff',
          name: 'static/[name].[ext]',
          limit: 10000
        },
      }
```
The version of Chrome browser used for test is Version 75.0.3770.80 (Official Build) (64-bit). 
don't know if this is true for other chrome version browsers.

**Comment by justin0022** [comment]
Fixed here: https://github.com/tl-its-umich-edu/my-learning-analytics/pull/535/commits/f5318bb7588a45cf06aa5f1d05d414506b8b5e82
