### ISSUE TITLE
Test React branch before merging to master

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#548]
I am not anticipating this is going to be exhaustive testing just so that understand the flow, open up issues if not in parity. This is done so that expectation is set before and after merge

**Comment by pushyamig** [comment]
@jennlove-um I will let you know once this is ready for testing on our test instance

**Comment by pushyamig** [comment]
we are in a process of setting up the `myla-test` instance on AWS Openshift instance once that is done Myla react branch will be ready for testing once internally at umich has a peak of what that looks like we will merge react to master. 
The issue that arises from the testing and needs to be fixed before the Fall term (Sept) should be tagged to project `MyLA-Fall-2019.02.01`

**Comment by pushyamig** [comment]
@jennlove-um , it is ready for testing in myla test. https://test-myla.tl.it.umich.edu/. I have added 2 courses data, let me know if you want more. I will run the cron for you.

**Comment by jennlove-um** [comment]
Testing error with Assignment Planning.
Data is not showing correctly for graded assignments in the assignments view.

Course: 295532
User: adamshke

1. Not all graded assignments in database are showing up as graded in the visualization.
2. Grades are showing up wrong for individual assignments

**Comment by jennlove-um** [comment]
Testing passes in terms of feature parity and basic functionality.
