### ISSUE TITLE
File bar chart view is not loading in Fire Fox only

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#549]
I am not sure if the Bar chart ever loaded in the FireFox one point of time but it is not now. I would consider this issue needs to be fixed before merging the react branch to master.
The Request/Response  description in FF:

<img width="881" alt="Screen Shot 2019-06-21 at 9 27 16 AM" src="https://user-images.githubusercontent.com/8579775/59925766-cf4aa100-9406-11e9-9573-a12bbec04a82.png">

The version of FF tested is FF Quantum (60.7.0esr (64-bit))
-------------------------------------------------------------------------

Request/Response object in Chrome:

![Screen Shot 2019-06-21 at 9 31 15 AM](https://user-images.githubusercontent.com/8579775/59926050-6dd70200-9407-11e9-86ca-7076ca365426.png)

**Comment by justin0022** [comment]
This issue can be closed now?
