### ISSUE TITLE
Allow users to change course in avatar modal

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#552]
There should be a way for users to change courses in the dropdown avatar modal. It can simply link to `/courses/`.

**Comment by pushyamig** [comment]
I will remove this from the react project as this can also be worked upon after react branch is merged to master. I will label it to react.

**Comment by pushyamig** [comment]
Testing: inserting multiple users flow
Just select a user of your choice like `select * From user where sis_name='dssss';`
Have an insert command
`insert into user values(null,17700000000111111, 'Test user', 01111311, 'dssss, 1770000000011333, 89.8,90,'StudentEnrollment'`

Delete the row afterword by the id of the rows `delete from user where id = 1223`

**Comment by jennlove-um** [comment]
@pushyamig I get an SQL syntax error when I try to do the insert to test this

**Comment by jennlove-um** [comment]
This works for students in multiple courses.  From within a course visualization, click on the profile gray circle, on the drop-down, click switch courses, then select another course to go to.
