### ISSUE TITLE
Canvas live events query need to consider other edapp for pulling the files access info

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#554]
The current query for pull files access information only includes ed_app = `http://umich.instructure.com/ `. But canvas live event has other ed_app which contains this information. Analysis needs to be done  again where the data resides and bring into MyLA DB

**Comment by jonespm** [comment]
This is currently an environment variable

BIG_QUERY_ED_APP

If this is true we'd have to either have multiple (IN query) or just drop this criteria from the query.

**Comment by jonespm** [comment]
This is being resolved in the files-develop branch

**Comment by jennlove-um** [comment]
Testing passes: Resources view is correctly showing Lecture Capture and Files resources for courses that have multiple types of resources.
