### ISSUE TITLE
Cron loader isn't working after changes to env or models

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#561]
After recent changes cron isn't running to completion. We need a few more updates. Might be related to config or model change.

**Comment by pushyamig** [comment]
When I verified the Model changes #557 #540 I ran the Cron locally to ensure data is loading properly and tested the views loading as well. As far as I can say cron was working with those commits

**Comment by jonespm** [comment]
One of these was also on the admin site adding a course.

Everything runs fine now.

**Comment by jonespm** [comment]
I did PR #562 last night. Not sure why it wasn't created.
