### ISSUE TITLE
404 Error in File Access View

### ISSUE THREAD

**Issue by vjcao** [tl-its-umich-edu/my-learning-analytics#566]
In the main react branch, after running `docker-compose build` and `docker-compose up` for the first time, I get a 404 error status in the console with `favicon.ico` as the issue. It goes away after refreshing though. 

NOTE: I am running MyLA locally on my machine

<img width="1436" alt="Screen Shot 2019-07-08 at 12 28 15 PM" src="https://user-images.githubusercontent.com/33735083/60828781-4f039a00-a181-11e9-866a-45f462030d4f.png">

**Comment by justin0022** [comment]
Could you check again with the latest code from the master branch? I'm unable to reproduce on my end.

**Comment by vjcao** [comment]
I think master might've fixed it. I am unable to reproduce the bug now. I will close this issue.

**Comment by jennlove-um** [comment]
No testing needed since the bug could not be reproduced.  Also, Resources Accessed view is behaving as expected in general testing.
