### ISSUE TITLE
403 forbidden in thrown in react branch for non-admin user accessing course from browser 

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#568]
This error got introduced after django-rules [changes](https://github.com/tl-its-umich-edu/my-learning-analytics/commit/804b6075be147d85edc273ccd4113d48583c61b2) merged to react branch. This is not an issue with the master branch.

Steps to reproduce:
1. Log in as a non-admin user and try the url ` /courses/12233 ` ( pick a user is actually part of the course) from the browser window it will throw 403 forbidden.  

I call this a blocker for merging the react changes to master.

**Comment by andrew-gardener** [comment]
`rules.add_perm('dashboard.get_home_courses_template', is_admin_or_enrolled_in_course)` needs to be added to `rules.py`

**Comment by andrew-gardener** [comment]
or rather `rules.add_perm('dashboard.get_course_template', is_admin_or_enrolled_in_course)` need to be renamed to `rules.add_perm('dashboard.get_home_courses_template', is_admin_or_enrolled_in_course)` 

(seems there was a rename of the function without a rename in the rules)

**Comment by pushyamig** [comment]
ok, I introduced `get_home_courses_template` and not sure why I used that instead of `get_course_template`
