### ISSUE TITLE
Lingering tool tips in Files and Assignments

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#576]
The first tool tip the user mouses over sometimes lingers in both the Assignment and Files pages.

**Comment by justin0022** [comment]
I haven't been able to reproduce this on my end. If you have the chance to share a GIF with me I'd appreciate it!

**Comment by justin0022** [comment]
@pushyamig were you able to recreate this issue at all?

**Comment by pushyamig** [comment]
I was not able to recreate it when I tested it today. 
@jennlove-um can you test it again to confirm the issues is still there?

**Comment by jennlove-um** [comment]
I am not able to replicate it today.  I'll close this issue.
