### ISSUE TITLE
Multiple page reloads when changing the Files filters

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#577]
The Files Viewed page list of files loads and reloads and reloads with different data each time until it finally settles.  This is distracting and confusing for the user.  When the user changes a filter, the page should reload once with the filtered data.

**Comment by justin0022** [comment]
Hi @jennlove-um, I'm unable to reproduce this issue. If you could share a screen recording of the problem, I'd be happy to look into it further!

**Comment by jennlove-um** [comment]
![MyLA_577_GIF](https://user-images.githubusercontent.com/39634416/61301786-a07bdc80-a7b2-11e9-86ee-22a75e9749d1.gif)

**Comment by jennlove-um** [comment]
@justin0022   I uploaded a GIF that shows the flickering.  It's most reproducible when I use the week sliders.  In this case, I change the start week from 1 to 7.  The results flicker and reload several times.

**Comment by justin0022** [comment]
Thanks Jenn! I'll look into it.

**Comment by justin0022** [comment]
I'm going to hold off on this issue until https://github.com/tl-its-umich-edu/my-learning-analytics/pull/565 gets merged, since there'll be lots of merge conflicts.

**Comment by jennlove-um** [comment]
This still occurs for me in testing.  I'm using Chrome.  It happens when I change the sliders.  I'm moving this from the fall release as not high enough priority to hold back the release.  But we should still find out why the screen flickers through several versions of the visualization before settling.

**Comment by jennlove-um** [comment]
I'm closing this issue for now.  The flickering resolves quickly and doesn't seem to be an impediment for students.
