### ISSUE TITLE
Files Accessed bug when window slider on right is fully collapsed

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#592]
<img width="1913" alt="Screen Shot 2019-07-16 at 9 57 00 AM" src="https://user-images.githubusercontent.com/8836578/61313879-37936500-a7b0-11e9-98b9-dadcc3e88288.png">

**Comment by justin0022** [comment]
I'm going to hold off on this issue until https://github.com/tl-its-umich-edu/my-learning-analytics/pull/565 gets merged, since there'll be lots of merge conflicts.

**Comment by jennlove-um** [comment]
@justin0022 Hi Justin - what's the expected behavior that I should be testing for on this one?

**Comment by justin0022** [comment]
The window slider on the right, when fully collapsed, shouldn't bug out. You can see that in the left-middle section of the screenshot there's some black squiggly lines caused by the window slider being fully collapsed.

**Comment by jennlove-um** [comment]
Thanks!  It's working for me in testing, now.
