### ISSUE TITLE
resource_type is marked as primary key but doesn't need to be

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#619]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 
The field resource_type is marked as a primary key in the model. I don't see why this is a primary key

## Steps to Reproduce :
1. No user visible bug, just a conversion

**Comment by jonespm** [comment]
`describe table resource`

**Comment by jennlove-um** [comment]
Confirmed resource_type is not a primary key in the table
