### ISSUE TITLE
[Discussion View] Design front-end view based on feedback from UM 

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#625]
There was some very useful feedback from our meeting (UBC and UM) on 2019-07-15. Namely:

* Review colour coding 
  - It’s not clear if shades of blue refer to frequency of using the keyword or coherence
  - The lighter colours indicate the keywords that require most attention, whereas the darker colours indicate the keywords that require the least attention. Should this be reversed?
* Review overall visualization
  - Information that requires most attention should be made salient in the visualization. Currently it seems to be the other way (refer to “review colour coding”)

The front-end design will require further iterations after user testing.

**Comment by jonespm** [comment]
I believe that this has all been implemented, so closing.
