### ISSUE TITLE
Turn on production mode for front-end when deploying and add to README

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#639]
Just a note that when deploying to production, the front-end should be built using production mode. Looking inside `package.json`, under `scripts`, there's the `prod` field. 

`npm run prod` should output [React in production mode](https://reactjs.org/docs/optimizing-performance.html), which is important for performance and much smaller JavaScript bundle size since Webpack tree-shakes/minifies the JS.

Please feel free to close this issue - I'll add a note about this to the README file.

**Comment by pushyamig** [comment]
The way it is set up right now in the `DockerFile` it is running as default `npm run prod`, for local run `docker-compose.yml` is used and under the `webpack_watcher` attribute it says `npm run watch` it transforms to run in development mode. For production, when using `docker-compose-prod.yml` or not using it ( in our case we are not using any docker-compose in prod) it is defaulting to set up in the DockerFile. 
Adding this in README is a very good idea

**Comment by justin0022** [comment]
Perfect, good to know things are already running in prod. I'll add a note about this in the readme.

**Comment by jennlove-um** [comment]
Based on comments in the ticket and related pull request, this looks done.  I'm closing the issue.
