### ISSUE TITLE
Create sourcemaps for front-end development

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#648]
Currently webpack isn't generating [sourcemaps](https://webpack.js.org/configuration/devtool/) so when in Chrome Devtools, it's difficult to debug since the code is transpiled.

**Comment by pushyamig** [comment]
In `webpack.config.js` if I do this `devtool: 'inline-source-map'` it creates the resource map but the trick is we need to know if this the build is in dev or prod mode. As it is suggested not to do it for prod mode

**Comment by justin0022** [comment]
https://webpack.js.org/configuration/devtool/#production I think there's an option to disable in prod. I'll play around with the options and try to increase build speed.

**Comment by jennlove-um** [comment]
MyLA is currently using sourcemaps, so I'm closing this issue.
