### ISSUE TITLE
Update the help documentation to reflect the recent tool design changes

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#658]
There have been a couple of recent changes to the MyLA visualization interface. 

For example, the "File Access"will be changed into "Resource Access" to include more resource types; the vertical My Grade bar will not shown, etc. 

The MyLA documentation needs to be updated to reflect those changes with the release.

**Comment by jennlove-um** [comment]
Online help has been updated.
