### ISSUE TITLE
Reorganize docs and configs into a docs folder

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#661]
Most large python projects seem to organize their documentation into a docs folder. This would probably make sense to do.

Like: https://github.com/django/django

We could move the config/env_sample.json, our existing docs and create something nice like 
https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html

Then as we documented the code better it would also generate better documentation. #

_Originally posted by @jonespm in https://github.com/tl-its-umich-edu/my-learning-analytics/pull/657#issuecomment-521266024_

**Comment by justin0022** [comment]
Great @huynhdom let us know if you need a hand

**Comment by jennlove-um** [comment]
The separate pages of the README.md look good.  I verified and updated a couple of links and added navigation links at the bottom of pages to let users move from one section to the next without going back to the README page if they want.
