### ISSUE TITLE
Build problem with invalid symlink

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#662]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Describe the bug (Tell us what happens instead of the expected behavior) :
There's a build error that says
```
--> COPY --from=node-prod-deps /usr/src/app/node_modules /code/node_modules
error: build error: API error (500): {"message":"Error processing tar file(exit status 1): invalid symlink \"/code/node_modules/.bin/csv2json\" -> \"../d3-dsv/bin/dsv2json\""}
```

I think if necessary we can just delete the node_modules/.bin directory as it's not used in running the application.

**Comment by jonespm** [comment]
A possible fix for this would be to just remove all symlinks from node_modules (or remove node_modules/.bin), we don't need those.

```
RUN npm prune --production && \
    # This is needed to clean up the examples files as these cause collectstatic to fail (and take up extra space)
    find /usr/src/app/node_modules -type d -name "examples" -print0 | xargs -0 rm -rf && find /usr/src/app/node_modules -type l -print0 | xargs -0 rm
```

**Comment by pushyamig** [comment]
This problem seems to be occurring with Myla running on Openshift (Michigan infrastructure). This problem seems to resolve now.
