### ISSUE TITLE
In cron, access denied to big query should be an error

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#667]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 
If you cannot connect to big query it prints up a message

`[2019-08-16 16:14:20 -0400] [1] [INFO] 403 POST https://www.googleapis.com/bigquery/v2/projects/xxx-xxx-xxx/jobs: Access Denied: Project xxx-xxx-xxx: The user xxx-xxx-xxx@xxx-xxx-xxx.iam.gserviceaccount.com does not have bigquery.jobs.create permission in project xxx-xxx-xxx.`

## Describe the bug (Tell us what happens instead of the expected behavior) :
Instead of an [INFO] This really should probably be an [ERROR] message which would fail the job

**Comment by jonespm** [comment]
This also prints an issue if the big query query is incorrect #746

**Comment by jennlove-um** [comment]
@jonespm Can we close this issue?

**Comment by jonespm** [comment]
This is still not fixed. There's unfortunately no exception thrown by the library and it just prints an INFO so we have to do some more checks in the cron for this. I'll bump this to the next release.

**Comment by jonespm** [comment]
Devs would need to test this. I tested by having a badly formatted query in the JSON file. I'm not entirely sure how to test the access denied error, but I feel like it should also be caught by this exception now.

**Comment by pushyamig** [comment]
Test passes

I manually raised error locally and `data_last_updated` is functioning as expected. As agreed in the meeting we cannot raise the rate limit reached exception so way test is accepted.
