### ISSUE TITLE
Use a better avatar icon for LTI launch (and maybe just in general)

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#672]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added
If LTI launched from Canvas use the user image from the LTI launch in the avatar link.

`user_image: http://url.to.image`

## Describe the solution you'd like
Basically add support for image instead of text. We could also support a user image in the app but LTI launch provides it. Seems better than having the initials or whatever we have in this box. The default launch just supplies the user id as a number so having a number there really isn't great.

Alternatively we could change this link to just be a [generic icon avatar](https://material-ui.com/components/avatars/#icon-avatars) of some kind, like the [fa-user](https://fontawesome.com/icons/user?style=solid).

**Comment by jonespm** [comment]
The LTI launch just has a number like this
![image](https://user-images.githubusercontent.com/27447/63517652-5bd41700-c4bd-11e9-9912-a94ae2ce0f4f.png)

**Comment by jennlove-um** [comment]
I'm closing this issue.  The request is addressed in #979 with more detail provided in the discussion.

**Comment by jennlove-um** [comment]
This has been fixed for some time with the LTI.  It's working in production, so there is nothing new for this release.
