### ISSUE TITLE
Slightly re-org Dockerfile to improve layer caching

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#674]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Describe the bug (Tell us what happens instead of the expected behavior) :
I noticed in the docker file it does some of the copying of node deps after it copies the project. We should be able to to do that library copy first to save a few seconds on each build.

Also the TZ in never changes and that can just go to the top.

**Comment by jennlove-um** [comment]
@jonespm Is this still needed?
