### ISSUE TITLE
Change the BigQuery Queries to consider the Event_times

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#680]
comments from  Unizin ....
The Event store in your production environments is now partitioned. More specifically, it is partitioned on the `event_time` column of the events table. Note that `event_time`  corresponds to the same property in the Caliper event (i.e., the timestamp when a behavior/event happened).
 
You need not query the Event store any differently than you do today to take advantage of the partitioning. You will still only interact with the `event_store` dataset and the `events` table. The partitioning is managed behind the scenes. We strongly encourage you to include an event_time parameter in your queries. You will realize significant performance boosts (and cost benefits).

What that means to the cron process is to query based on term start for all the queries related to BiqQuery

**Comment by zqian** [comment]
The suggestions is to loop through all courses and find the earliest date for those courses.

**Comment by ssciolla** [comment]
@zqian, the changes in [this branch](https://github.com/tl-its-umich-edu/my-learning-analytics/compare/master...ssciolla:issue-680-consider-time-in-bq-queries) was what I was suggesting earlier during the meeting.

**Comment by zqian** [comment]
Thanks, @ssciolla 

Can we use the aggregate() function in Django to find out the min date value?
https://docs.djangoproject.com/en/dev/topics/db/aggregation/

**Comment by ssciolla** [comment]
Maybe, I though about using some filtering, but because we're leveraging a custom method, I wasn't sure how that would work.

**Comment by ssciolla** [comment]
I'll look into your suggestion.

**Comment by zqian** [comment]
I am thinking of use Course.objects.aggregate(Min(date_start)). See if that works.

**Comment by ssciolla** [comment]
> I am thinking of use Course.objects.aggregate(Min(date_start)). See if that works.

I don't think we can can do that because not all `Course` objects have a value for `date_start`; that's why we have to use `get_course_date_range` (which also considers `Term` dates). There might be a way to make the method a property and then use something like what you suggested.

**Comment by zqian** [comment]
Got it. Then the current solution is good. 

The next step is how to pass the value into the cron job.

**Comment by zqian** [comment]
I think we can add another param into the queries inside RESOURCE_ACCESS_CONFIG configuration in [env_sample.json](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/config/env_sample.json), and pass in the time value in the update_with_bq_access() function of [cron.py](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/dashboard/cron.py)

**Comment by zqian** [comment]
@ssciolla please see the recent checkins in [my branch](https://github.com/tl-its-umich-edu/my-learning-analytics/compare/master...zqian:issue_680?expand=1). That should work. Please take a look, and it everything looks all right, you can go ahead and checkin from your branch.

**Comment by ssciolla** [comment]
@zqian, great, I will try this out today. You could submit this as a PR if you wanted?

**Comment by jonespm** [comment]
I believe this was fixed on #848

**Comment by jonespm** [comment]
I see this working in the query but in the logs it says
`[2020-02-05 07:58:02 -0500] [INFO] [utils.py:20] Earliest start datetime for all courses: 2017-08-01T04:00:00+00:00`

Which looks like the date from the demo course 84541. We probably shouldn't have courses that with a start date that old that are active.

**Comment by jonespm** [comment]
I updated the date for that one course to 2020-01-01 but looks like there's still some course with an early start date in there. I think it would have been useful if this log message displayed the course with this date.

`[2020-02-05 08:22:29 -0500] [INFO] [utils.py:20] Earliest start datetime for all courses: 2019-01-06T18:26:00+00:00
`

@jennlove-um Do we need to have courses like this in there with such old dates? Maybe we'd have to have some way of marking them to not consider their dates for the resources view? This can be further improved and I'll create an issue about it.

**Comment by jennlove-um** [comment]
I don't see any reason that we would need dates that old.  I did a quick review of all the courses in test and prod to verify that.  I agree that this can be improved.  We don't need to get events for courses after they have ended, but we don't want to wipe out those legacy events either.
