### ISSUE TITLE
DashboardAppBar links don't work in Firefox

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#681]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 

When clicking on the two links in the `DashboardAppBar`, the user should be redirected to the course list (`courses/`) or the course home page (`courses/{course number}`), regardless of what browser is in use.

## Describe the bug (Tell us what happens instead of the expected behavior) :

Both of the above links do not work when using Firefox. No error is thrown, and nothing appears in the log on a local instance. The button acts appropriately visually when clicked, but nothing happens. The links do appear to be working as expected in Chrome and Safari.

## Steps to Reproduce :
1. Open app instance in Mozilla Firefox browser.
2. Navigate to a course or view page.
3. Click on either link in the `DashboardAppBar`.

**Comment by justin0022** [comment]
Strange! I'll investigate.

**Comment by justin0022** [comment]
I'm unable to reproduce on my Mac, running Firefox Quantum 68.0.2 (64-bit)

**Comment by ssciolla** [comment]
Huh. I'm using Firefox Quantum 60.8.0esr (64-bit) on my Mac. I believe @pushyamig was able to reproduce this.

**Comment by justin0022** [comment]
Strange. I just tried on Safari and it's also working as expected.

**Comment by pushyamig** [comment]
Yes, I was able to reproduce the issue same version as @Samuel Sciolla
<ssciolla@umich.edu>
Regards,
Pushyami

**Comment by jonespm** [comment]
Firefox 68 ESR was released July 9th, 2019 and Firefox 60 ESR is no longer going to be supported at all after October 23rd. There were a lot of odd bugs that only affected Firefox 60. I know currently our (ITS) image has 60 ESR but that could get updated any day. 

In the last 6 months of running MyLA in production we had 1.9% of users on Firefox. And of that 1.9% only 15% were on 60.0. So that's 0.2% of all users. 

I'd just close this as unsupported browser.

**Comment by ssciolla** [comment]
@jonespm, makes sense. I'm closing this for now, and I'll test it again when the Firefox version gets updated. Thanks for checking it out, @justin0022!
