### ISSUE TITLE
Demo mentioned in README no longer works

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#683]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 
When running the "Populate initial demo terms and courses" something should still work with this process.

`docker exec -it student_dashboard /bin/bash ./demo_init.sh`

## Describe the bug (Tell us what happens instead of the expected behavior) :
In the current version running this it gives a lot of errors, probably because of the AcademicTerm changes. We may want to just change this demo process to load up the sample SQL instead but if we do this and remove this old demo then that process should be documented instead.

**Comment by jonespm** [comment]
I think it would still be nice to have some mock "demo" data. I'm not sure of the best way to do it. 

I was thinking we could just re-generate de-personalized data whenever we made large changes to the data model but that requires keeping up with that process. 

We could create [fixtures](https://docs.djangoproject.com/en/2.2/howto/initial-data/) instead of the SQL file (based on the SQL file). I think I was looking at one time at [dumpdata](https://docs.djangoproject.com/en/dev/ref/django-admin/#dumpdata) (to dump the personalized data) and just keeping the fixtures updated from that point forward.

**Comment by jennlove-um** [comment]
@jonespm  Any advice on testing this one?

**Comment by jonespm** [comment]
Ok I tested it, I'm going to create a new issue to add demo_init.sh to the git ignore otherwise it comes up as an untracked file.
