### ISSUE TITLE
Add link to course to Courses admin page

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#684]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added
I feel like we've talked about this but I don't see the issue for this one. It would be nice to have a link that goes to the course somewhere in the admin UI. Currently we have to change this around. I remember having to change around the courses URL to retrieve this a while ago. The URL can be retrieved with

`url = reverse('courses', kwargs={ 'course_id': canvas_course_id })`

## Describe the solution you'd like
Maybe [something like this answer](https://stackoverflow.com/a/2156277) to add a custom URL to the Admin table for Courses? A button next to "History" after clicking on a Course would also be good, I'm not entirely sure how to add that.

**Comment by jonespm** [comment]
@ssciolla Did you do any work on this one? I'd thought it was implemented for some reason? :)

**Comment by ssciolla** [comment]
We talked about this, yeah, but I was sidetracked by some other things. The ideal solution is to use `get_absolute_url`, since I believe it will automatically create a button similar to the one we have now for "Login As" when logging in as a user. I remember encountering some difficulty that made me start thinking about the Django version upgrade, but I will return to this.

**Comment by ssciolla** [comment]
So adding the following code to the `Course` model works (i.e. adds a "VIEW ON SITE" button to the Course's edit page in the Admin). 

```
    def get_absolute_url(self):
        return reverse('courses', kwargs={'course_id': self.canvas_id})
```

However, you have to change the one `Site` record (referred to in `settings.py` by index in the `SITE_ID` variable) so its domain is `localhost:5001`, or the appropriate domain for a different environment. Does this "solve" the issue, or should we try to find some way to dynamically set the domain? It seems like there might be a way to do it, but I haven't found too much online (which makes me think I'm searching with the wrong terms).
