### ISSUE TITLE
Add some way to see what users are in what courses

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#685]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added
I feel like it would save time if there was a way to see what users are in which courses in the Django Admin interface. Right now we either have to go to the database or to Canvas.

## Describe the solution you'd like
Maybe a [custom action that goes to another page](https://docs.djangoproject.com/en/2.2/ref/contrib/admin/actions/#actions-that-provide-intermediate-pages)? Then on the courses page someone would just click the course and like "Show users in selected courses" and it would show it on a new page? I think that would be enough.

As an additional feature If the users in the course were users in the system this page *could* take them to the `/adminauth/user/<userid>/change/` page or something like that too. 

I think all we *really* need is sis_name and maybe sis_id, maybe enrollment_type. This *could* be a separate read-only view linked from the top level, I don't know which would take more effort.

**Comment by ssciolla** [comment]
This issue relates to a current problem I see with the data model, which is that really the relationship between `user` and `course` is many-to-many. Some of the columns in `user` could be part of an `enrollment` junction table (e.g. `current_grade`, `final_grade`, and `enrollment_type`). With a formal many-to-many relationship set up, it should be straightforward to  add a `users` field to the admin interface. Just a thought. 

If there is not an appetite for introducing this drastic of a change to the data model, we could also make the `course_id` field in the `User` model a `ForeignKey` field and add a `get_users` method to the `Course` model that uses the ORM to pull all users across the one-to-many relationship.

**Comment by emilychee** [comment]
Hi! My partner @apalmer16 and I are currently students enrolled in EECS 481. We recently saw a presentation regarding MyLA in class and wanted to contribute to fixing an open source issue. We just wanted to let you know that we will be attempting to tackle this bug!

**Comment by justin0022** [comment]
Thanks @emilychee, we're happy to help if you run into any difficulties.

**Comment by jennlove-um** [comment]
Requirements need to be defined for this issue.

**Comment by jonespm** [comment]
I feel like the biggest reason we'd want this is because of the "Act As User" but there's another issue to remove that #1348. Then we'd just use the Canvas people tool. I'm not sure how important this is to implement anymore and haven't heard of this request. I feel like this is safe to close.
