### ISSUE TITLE
make the `course_enabled` api as configurable option for making it public/protected API

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#687]
At Umich we have made `course_enabled API (list courses view options enabled/disabled) as Public. The purpose of the API was to enable the Myla visuals Links( likes /assignments) in canvas. This approach might not be True with other universities, so making this a configuration Defaulting to False via `env.json` and removing it from Django-rules set.

**Comment by jennlove-um** [comment]
@pushyamig How can I test this one?

**Comment by jennlove-um** [comment]
Testing passes with configuration turned on and off.
