### ISSUE TITLE
Resource Accessed responsive bug

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#694]
## Expected behavior (A clear and concise description of what you expected to happen) : 
The slider on the right overflows and exits the display when the browser window is resized. 

## Screenshots/Video (If possible, add media to help explain your problem) :
![Screen Shot 2019-09-11 at 4 27 20 PM](https://user-images.githubusercontent.com/8836578/64742520-5f9dfc80-d4b1-11e9-8192-e91a97f3e518.png)

**Comment by naeunk** [comment]
Hello, I am currently a student enrolled in EECS 481. My partner and I were wondering if it is possible to contribute to fixing this issue. Thanks.

**Comment by vjcao** [comment]
Thank you @naeunk , let us know if you run into any difficulty.

**Comment by ssciolla** [comment]
I have been working on this issue after studying and getting at-least-a-little clued in to `d3`. Right now I have two solutions which have somewhat different behavior. 

### Solution 1: Calculate chart and margin sizes using percents, don't adjust font sizes

Code: [issue-694-fix-responsiveness-bug-with-percents](https://github.com/ssciolla/my-learning-analytics/tree/issue-694-fix-responsiveness-bug-with-percents)

Pro(s):
* Text sizes stay the same, making content more readable on smaller windows.

Con(s):
* Content gets jumbled and some cut off on the smallest window sizes.

### Solution 2: Use an SVG `viewbox` attribute on the component's wrapper

* [issue-694-fix-responsiveness-bug-with-svg-viewbox](https://github.com/ssciolla/my-learning-analytics/tree/issue-694-fix-responsiveness-bug-with-svg-viewbox)

Pro(s):
* Everything scales well and looks neat.

Con(s):
* Text become very difficult to read on smaller window sizes.

**Comment by ssciolla** [comment]
Seems like the researchers prefer having the font sizes of text stay fixed or at least at a more legible size, i.e. Solution 1. I'll proceed under that assumption.

**Comment by jonespm** [comment]
@ssciolla Is this fixed with #910?

**Comment by ssciolla** [comment]
Yes, I'll close, but should still be in QA column for project.

**Comment by jennlove-um** [comment]
Testing passes.  Tested in Firefox and Chrome.  When the window is resized, the slider displays correctly and the font sizes don't change.
