### ISSUE TITLE
Have the Git revision and branch info in the footer of the Myla

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#698]
These are ideas to do it and possibly this is just for the admin user only 
1. https://github.com/tl-its-umich-edu/my-learning-analytics/commit/400a14cce16629efa0ef8f0cf95d07afe05bfb43
2. https://www.npmjs.com/package/git-revision-webpack-plugin
3. https://goodcode.io/articles/django-source-revision/

**Comment by jennlove-um** [comment]
Git version and branch display for admin user and do not display for non-admin user.  Testing passes.
