### ISSUE TITLE
Snackbar in grade distribution is triggered when sidebar is opened

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#705]
## Expected behavior: 
Snackbar should only display when `Show my grade` is clicked. 

## Describe the bug (Tell us what happens instead of the expected behavior) :
Snackbar is triggered when sidebar is opened/closed if the `Show my grade` is changed _before_ the sidebar is opened. 

## Steps to Reproduce :
1. Navigate to grade distribution.
2. Click `Show my grade`
3. Click sidebar (top left button)
4. Snackbar will open (but state will not change of the `Show my grade`).

**Comment by jennlove-um** [comment]
Retest this with the correct release branch.
