### ISSUE TITLE
Update README for latest version of data (9-11)

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#719]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 
It was noted on the call that myla_test_data_2019_09_11 file is not correct with the current README. We need to update the README for the data in this file. 

I'd like to figure out a process for the depersonalizer that will keep some id's static so we don't have to make so many documentation updates.

**Comment by ssciolla** [comment]
We had an EECS student try to update the README to better reflect the changing course id values. In thinking about those changes (which I had them remove), I had the following idea:

I feel like with the changes introduced in PR #761, we probably shouldn't be listing any hardcoded course values and just instruct people to use the admin interface. So instead, under `Logging in as an administrator`, we'd have the following:

1. As you are now logged in as `root`, there are no courses listed. To view the Django admin interface, navigate to http://localhost:5001/admin
1. Click on "Courses" under "Dashboard" to view a list of sample courses.
1. Click on the link in the "Course Link" column for the sample course you wish to view.

@jonespm, thoughts?

**Comment by ssciolla** [comment]
Wups, I guess some of this has already been addressed by PR #811. I still think relying on the Django admin might be a good idea.

**Comment by ssciolla** [comment]
@lsloan, we talked about updating 5. under "Logging in as administrator" so that it doesn't reference specific course ids but just gives instructions on finding and viewing the course via the Admin. This is to eliminate the need to repeatedly update time-related information.

**Comment by jennlove-um** [comment]
@ssciolla Is this addressed in #661 ?  Can we close this issue?

**Comment by ssciolla** [comment]
Looks like this has been handled by my PR or another earlier on. The `README.md` doesn't reference a specific file, just the Google Drive directory. I'll close it.
