### ISSUE TITLE
Document the Canvas integration process

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#721]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added
We should have a page in the Wiki documenting how we integrate this into Canvas.

This would include

~~- [ ] Enabling the courses URL COURSES_ENABLED=true~~
~~- [ ] Showing the javascript for how to use this URL in Canvas~~
~~- [ ] Using Cloudfront as a proxy to this data (We aren't using Cloudfront anymore)~~
~~- [ ] How the cron job works wrt course start dates #1083~~

**Comment by jonespm** [comment]
This may change now that LTI is going to be used instead. We'll have a different process.

**Comment by pushyamig** [comment]
I have updated the part for having myla links in canvas

**Comment by pushyamig** [comment]
Here is the link to the Wiki page for that https://github.com/tl-its-umich-edu/my-learning-analytics/wiki/Dev:-MyLA-tool-url-in-canvas-pages

**Comment by jennlove-um** [comment]
@pushyamig Could you take a quick look at the wiki page? I reviewed and made some minor edits for readability, but I want to make sure I didn't get anything factually wrong in doing that.

**Comment by pushyamig** [comment]
@jennlove-um  Looks Good!
