### ISSUE TITLE
Change text on mouse-over for video content

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#724]
On the Resources Accessed page, the mouse-over text for files that the student has accessed currently reads "You have read the resource X times.  The last time you accessed this recourse was ..."

Since we are including types of resources that are not read, e.g., video, we need to change this to more generic language.

Suggested change: "You have accessed this content X times.  The last time you accessed it was...."

**Comment by vjcao** [comment]
For this issue is it ok to word it like, "You have accessed this resource X times. The last time you accessed it was....?"

**Comment by jennlove-um** [comment]
Yes, that should be fine.

**Comment by ssciolla** [comment]
I'm reopening this since there was a small typographical error in the merged PR.
