### ISSUE TITLE
Resources Accessed: Message displays saying no data is available when the user changes their setting

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#725]
# Expected behavior (A clear and concise description of what you expected to happen) : 
User can select a new setting from the filter drop-down and the filtered results and week timeline continue to display correctly when the setting is saved.

## Describe the bug (Tell us what happens instead of the expected behavior) :
After clicking Save My Setting, 2 unexpected results are happening: 
1. The timeline disappears from the top of the page  
2. The filtered list of results disappears and a message displays "Resource data for your selections is not available.  (even though results are available)

Workaround: Refresh the page.

## Steps to Reproduce :
1.  User goes to Resources page
2. User selects a filter on the Resources page (make sure resources still show in the filtered list)
3. User clicks Save My Setting

**Comment by jennlove-um** [comment]
@justin0022  I assigned this to @zqian, but if you want to look at it, let me know.  Thanks!

**Comment by jennlove-um** [comment]
![MyLA_RA_SettingError](https://user-images.githubusercontent.com/39634416/65805057-2d97c600-e152-11e9-8e16-e250b238309f.gif)

**Comment by justin0022** [comment]
> @justin0022 I assigned this to @zqian, but if you want to look at it, let me know. Thanks!

I can take a look but it may take me a while - the `AssignmentPlanning` redesign is taking up a large chunk of my time! If you want me to prioritize this just let me know.

**Comment by jennlove-um** [comment]
Thanks, @justin0022  - no need to look at it.  Zhen is taking this one one.

**Comment by pushyamig** [comment]
Test Plan:
I have refactored the login to the resource, so test it as a whole functionality of the view not just the bug.

**Comment by jennlove-um** [comment]
Resources Accessed functionality passes all tests in test plan.
