### ISSUE TITLE
Assignment Planning view is showing grades for assignments that should be hidden

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#728]
## Expected behavior (A clear and concise description of what you expected to happen) : 
Student goes to Assignment Planning view and assignments that have been released in Canvas have grades showing in MyLA.  Assignments that have not had grades released in Canvas do not show up in MyLA. 

## Describe the bug (Tell us what happens instead of the expected behavior) :
Grades for assignments that have not been released to the student in Canvas are showing up as graded in MyLA.  

Grades for assignments that have been released to the student in Canvas are showing up as ungraded in MyLA.

## Steps to Reproduce :
1.  Select a course that has assignments that have been released to all students and assignments that have not had grades posted for all students.
2. Login to MyLA and go to the Assignment Planning page
3. Review graded and ungraded assignments.  No grades for assignments should display for the student if that student can't see the grade in Canvas.

**Comment by pushyamig** [comment]
fixed by using `posted_by` #727 .

**Comment by jennlove-um** [comment]
Testing passes.  Students are correctly seeing grades on assignments that they can see as graded in Canvas.

Testing was done for at least one student in all courses scheduled for fall 2019 in addition to test courses.

**Comment by jennlove-um** [comment]
since testing passes and this issue was resolved by #727, I'm closing this one as well
