### ISSUE TITLE
Update Django Debug Toolbar and update MIDDLEWARE for Django 1.11

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#733]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added

Django Debug Toolbar 2.0 was released that has a few new features and bugfixes. It removes support for the old MIDDLEWARE_CLASSES which MyLA is still using. This should be updated at the same time.

**Comment by jonespm** [comment]
The test will be to login as admin and see that the toolbar still works. If this doesn't work you won't be able to login at all.

**Comment by pushyamig** [comment]
@jonespm do you want to has this change merged to `2019.02.x` branch? as this seems to be slated for the Project `MyLA-Fall-2019.02.02`. If yes, can you merge this change to  `2019.02.x`. Since we are still in a process of testing for Fall we can include it, WDYT?

**Comment by jennlove-um** [comment]
Testing passes - I can log in as admin and use MyLA.
