### ISSUE TITLE
Upgrade material-ui to V4 from V3

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#736]
Looks like a major upgrade with better theming support: https://medium.com/material-ui/material-ui-v4-is-out-4b7587d1e701

I'm going to test and see if there are any major breaking changes. If there are no major breaking changes I'll send in a PR.

**Comment by justin0022** [comment]
@ssciolla do you have thoughts on how this will impact your work on https://github.com/tl-its-umich-edu/my-learning-analytics/issues/673?

**Comment by ssciolla** [comment]
Thanks for asking, @justin0022. So far, I am only adding new imports for `createMuiTheme` and the `MuiThemeProvider` component. Looking at the Material UI 4 documentation, the former works the same and the latter is now called `ThemeProvider` but seems to work the same. I don't we should have a problem upgrading, at least on the theme front.

**Comment by justin0022** [comment]
Perfect, thanks for the heads up. Going to upgrade and test now.

**Comment by jennlove-um** [comment]
Testing passes: No obvious issues with any screen elements or alignment was detected.
