### ISSUE TITLE
Change "Due At" in assignment tooltip to be just "Due"

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#737]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

"Due at" sounds awkward, should be changed. In Canvas it just says "Due" and on the table it also says Due

![image](https://user-images.githubusercontent.com/27447/66132620-56411500-e5c3-11e9-8e25-d5cef38ec4ac.png)

**Comment by jennlove-um** [comment]
Testing passes
