### ISSUE TITLE
Login and Logout redirect URL's are documented incorrectly

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#739]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 
LOGIN_REDIRECT_URL and LOGOUT_REDIRECT_URL are actually DJANGO_LOGIN_REDIRECT_URL and DJANGO_LOGOUT_REDIRECT_URL in the code. Need to update the documentation to match.

**Comment by jennlove-um** [comment]
Testing passes for both admin and non admin users.  Logout correctly prompts the user to confirm then completes the log out.
