### ISSUE TITLE
Define the SAML config as a JSON block

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#741]
Now that we have JSON for config I was thinking we could group all the SAML stuff together. Anyone using SAML would need to change their config over to this one though.

```
  "SAML": {
    "URL_BASE": "/accounts",
    "DEFAULT_IDP": "",
    "FILES_BASE": "/saml/",
    "METADATA_FILE": "/file/path/metadata.xml",
    "PEM_FILE": "/file/path/file.pem",
    "ACS_DEFAULT_REDIRECT": "/",
    "LOGIN_REDIRECT_URL": "/",
    "LOGOUT_REDIRECT_URL": "/",
    "ATTRIBUTE_MAPPING": {
      "uid": [
        "username"
      ],
      "mail": [
        "email"
      ],
      "givenName": [
        "first_name"
      ],
      "sn": [
        "last_name"
      ]
    }
  }
```

_Originally posted by @jonespm in https://github.com/tl-its-umich-edu/my-learning-analytics/pull/740#issuecomment-538104336_

**Comment by pushyamig** [comment]
@jonespm what is property, I don't see this being used now. is this relevant? if yes give some example values
```"ATTRIBUTE_MAPPING": {
      "uid": [
        "username"
      ],
      "mail": [
        "email"
      ],
      "givenName": [
        "first_name"
      ],
      "sn": [
        "last_name"
      ]
    }
  }
```

**Comment by jonespm** [comment]
It might be better to create this as a live settings package instead 
https://djangopackages.org/grids/g/live-setting/

**Comment by jonespm** [comment]
SAML is going to be removed in #1212 so closing
