### ISSUE TITLE
Rewrite bigquery to only pull data from last run

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#747]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added
The BigQuery piece of the cron pulls all of the data out of the entire event store. I believe that this data is partitioned by date now, so pulling data with a date filter should result in much better performance on this query. We should change this so it only appends new data by default rather than updating the entire table. 

We should some way we could force force a full refresh. Either if the table is empty or some parameter we could pass to the job. This may require #664 to be implemented first.

**Comment by zqian** [comment]
I believe this is identical to issue #680

**Comment by jonespm** [comment]
Oops, should have searched better for duplicate.
