### ISSUE TITLE
Implement some alternate text for graphs to improve accessibility

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#749]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added

For someone who is blind or poor sight they might have a problem seeing the graphs. There also may be people who have trouble understanding the graphs. 

Tableau has a cool extension developed by Narrative Science and I think this is what we'd want to use as inspiration for our data descriptions. 

We'd have to have someone come up with the basic description of all of the graphs with blank areas that could be substituted for data.

For instance on the graph for files it could be something like
"This graph displays the most viewed files, here is the information contained for the top 10 most viewed files. <Filename> has been viewed <Number of View Times>. You <have/have not> viewed this file. . ." Maybe it would be useful to split them into files I haven't read, and files I've read? We'd want to look at some other examples of how this works.

**Comment by jonespm** [comment]
Assigning to @jennlove-um to see if she's seen this in use in Tableau or anywhere else in commercial visualization applications before.

**Comment by pushyamig** [comment]
More are less this is what needs to be done


```
<div class="container">
      <h2>A viz</h2>
      <div aria-live="polite" id="id-of-narrative-text-blocK" class="screenreader-only" id="viz-narrative">
        Text describing init state on load, changes with filtering actions
      </div>

      <svg aria-describedby="id-of-narrative-text-blocK" role="img" aria-labelledby="id-of-title2">
        <title id="id-of-title2">Title text</title>
        ...svg goober here
      </svg>
</div>
```

Reading through the [document](https://bolt.mph.ufl.edu/6050-6052/unit-1/one-quantitative-variable-introduction/describing-distributions/#features) provided by Matt K, it looks to me coming up with a description of the graph. 

For example, Grades view is histogram and generally description of it can be describing shape of graph by modality, skewed ness. we might need to have some statistical formula to tell graph is modal/bimodal, left/right skewed. I don't know if that adds any value.

This is an additional resource [shared](http://web.mit.edu/crystall/www/files/VIS2019_Access_Accessible.pdf)

**Comment by gsilver** [comment]
@pushyamig @jennlove-um  - mark as done.  I would open 2 new tickets:

1. Correct punctuation of message.  There are extraneous commas through out. 
2. Investigate a message that more accurately reflects the insight conveyed by the viz and takes into account what a user would want and benefit from (where does my grade fall in the continuum, what percentile am I in, etc.)

**Comment by jennlove-um** [comment]
Testing passes for the current iteration of the alternate text.
