### ISSUE TITLE
Assignments are showing up with no name in Assignment Planning 

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#751]
## Expected behavior: 
All assignments that have been published to students display in the Assignment Planning tool with a name and percent impact on grade.

## Describe the bug (Tell us what happens instead of the expected behavior) :
On one course, there are 3 assignments that show up in Week 3 with 0% impact and no assignment name.

**Comment by justin0022** [comment]
I suspect this is fixed on the Assignment Planning redesign - but since the redesign will not be launched for a while this should be fixed regardless.

**Comment by jennlove-um** [comment]
Needs retesting and more detail about the conditions under which this happens.

**Comment by jennlove-um** [comment]
I am not able to duplicate this.  I'm closing this issue. If it recurs, I'll reopen the issue.
