### ISSUE TITLE
Bring in all terms from Canvas to MyLA

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#758]
#164  Expected behavior : 
All course terms, including those with no start and end dates, get added to MyLA to support Canvas courses using MyLA.  Courses with any term in Canvas should be allowed to be added to MyLA.

## Describe the issue :
The current cron query for terms errors when trying to get terms for Canvas courses using "No Term" or "Default Term."  Both of these terms have no start or end date.  

The query currently looks for terms after 2016-11-15.  It should bring in all terms, instead.

**Comment by jonespm** [comment]
The issue was here
https://github.com/tl-its-umich-edu/my-learning-analytics/blob/0837829e955e83fce99de87f7f34f8c25d83497b/dashboard/cron.py#L434

I think we can remove this EARLIEST_TERM_DATE setting now as we are pulling the term and syncing it up now. We used to have a dropdown people were forced to select from.

**Comment by ssciolla** [comment]
I've started work on this issue, which you can see on [this commit from the issue-758-fetch-all-terms branch](https://github.com/ssciolla/my-learning-analytics/commit/be86c875adf3e036860cd834730840f9b5c32f16#diff-64b16f0fa7d7ac8585eaf90c3df4346cR435) of my fork.

@jonespm, so as you said, we can just modify the term query to pull in all the terms by removing the `WHERE` clause. If we do this, we should also probably modify the `get_course_date_range` method of the `Course` model to use the fallback dates (now, two weeks from now) if `date_start` and `date_end` are null. I also did this in the above linked commit, as well as added `logger.warning` messages to alert users that the fallback dates are in use.

What I am less sure about is how this will affect the rest of the application. It seems the main use case for this is to handle courses that go beyond a single term, but then the `MAX_DEFAULT_WEEKS` setting used in `views.py` may need to be changed or removed:

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/11dd6f55333b40e6c863f7ccef077b068dcc070a/dashboard/views.py#L120-L123

Thoughts? I was testing with a course id @jennlove-um gave me, which was useful for testing the term and date changes but seemed to have not have substantial resource access, assignment, or grade data to work with.

**Comment by jonespm** [comment]
@ssciolla Aside from the print I think your WIP looks good, can you create that as a PR? Also remove the EARLIEST_TERM_DATE setting from the settings and the sample config.
