### ISSUE TITLE
Improve docker-compose file system performance

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#767]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added
I've noticed that since we've switched to mounting the local filesystem via docker-compose that we have to restart less but the application just *feels* slower than it used to. It sounds like this is a known problem with Docker on OSX and Windows

![image](https://user-images.githubusercontent.com/27447/67207870-67bb5700-f3e2-11e9-82ca-519a39f18acd.png) [1]

Do you use OSX or Windows at UBC @andrew-gardener @justin0022 ? I've been trying docker-sync with another app and it seems to be faster. It looks like there isn't much change in the files to set it up, but it does require a little setup on the local machine (installing a gem on OSX).

[1] https://medium.com/@kovah/cut-your-docker-for-mac-response-times-in-half-with-docker-sync-c362e41847ae

**Comment by jonespm** [comment]
Going to look at some of the stuff here too
https://docs.docker.com/docker-for-mac/osxfs-caching/

Maybe using either delegated or cached option instead would be good enough?

**Comment by jonespm** [comment]
I've been [reading more about this](https://engageinteractive.co.uk/blog/making-docker-faster-on-mac) and using :delegated seems like it will work fine. OSX is significantly slower than Linux and we don't need changes in the container to be immediately reflected on the host for the MySQL instance, and we'll have to test for the rebuilds if :cached or :delegated is the better option.

**Comment by justin0022** [comment]
> o you use OSX or Windows at UBC @andrew-gardener @justin0022 ? I've been trying docker-sync with another app and it seems to be faster. It looks like there isn't much change in the files to set it up, but it does require a little setup on the local machine (installing a gem on OSX).

We're both on OSX @jonespm
