### ISSUE TITLE
Frontend doesn't load when user is affiliated with a course with an apostrophe in the name

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#779]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 

The application should be able to support courses with any name, including if the name has an apostrophe (e.g. "Sam's Course on Silliness").

## Describe the bug (Tell us what happens instead of the expected behavior) :

@jennlove added a couple of courses to the test instance of MyLA that she was enrolled in and discovered that she could only see the footer information when she visited those course pages. After some investigation, we discovered that an apostrophe included in one of the courses was causing a JavaScript syntax error when the `myla_globals` object was being created. We'll need to look at the `base.html` file in the backend and the `App.js` file in the frontend to ensure single quotes are properly escaped or handled.

## Steps to Reproduce :
1. Add a new course with an apostrophe in the name and run the cron (or edit an existing course)
2. Log in as a user with some affiliation to the course (teacher or student)
3. Try to navigate to any page in the frontend.

**Comment by jonespm** [comment]
I would fix this by refactoring the block in base.html that generates myla_globals into the backend.

If you created that as a map, run `json.dumps` on that and put it in the context, it will be properly formatted in the template. This looks like a cool solution too. https://stackoverflow.com/a/4699069/3708872

You might also just be able to target this specific field in the template with the [escapejs](https://docs.djangoproject.com/en/1.7/ref/templates/builtins/#escapejs) filter and avoid a large change right now.

**Comment by ssciolla** [comment]
I think I have a fix for this; see my [issue-779-rework-myla-globals branch](https://github.com/ssciolla/my-learning-analytics/tree/issue-779-rework-myla-globals). It does what @jonespm suggested, as well as refactors a bit how the `CourseList` component appears to users with no affiliated courses. I'm going to do a bit more testing and then submit a PR.

**Comment by jennlove-um** [comment]
Testing passes in myla-test.  I was able to add a course with an apostrophe in the title and the visualizations displayed correctly.
