### ISSUE TITLE
Error with fresh install of MyLA on localhost for webpack-stats.json

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#780]
## Describe the bug (Tell us what happens instead of the expected behavior) :

Fresh install of MyLA gaves this error `at localhost:5001: Error reading /code/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?`

This was related to a recent change in symlinks on #763. We're going to need to uncompress these when starting up the container locally.

**Comment by pushyamig** [comment]
The webpack-watcher starts up correctly and the watcher is also working fine

Test passes
