### ISSUE TITLE
CourseList component doesn't give useful feedback to admins, unenrolled users 

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#785]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 

Whenever a user successfully authenticates to MyLA, they should be greeted with some notification of what content they are able to view, even if they aren't enrolled or affiliated with any courses.

## Describe the bug (Tell us what happens instead of the expected behavior) :

When a superuser not enrolled with any courses visits the landing page, they see the following, which is confusing given that there is nothing to select.

![Screen Shot 2019-11-08 at 10 41 17 AM](https://user-images.githubusercontent.com/35741256/68489261-c3744580-0214-11ea-8a29-f971abf5764b.png)

When a regular user not enrolled in any courses visits the landing page, they see only the footer. 

![Screen Shot 2019-11-08 at 10 40 13 AM](https://user-images.githubusercontent.com/35741256/68489291-d1c26180-0214-11ea-975f-21c6195cfddc.png)

These behaviors are controlled by logic in the `CourseList` container component.

## Steps to Reproduce :
(see above)

**Comment by ssciolla** [comment]
I've been working on a solution that refactors the `CourseLIst` so that both cases listed above receive the same feedback: an `AlertBanner` indicating that they are not enrolled in any courses with MyLA enabled. Once issue #779 is addressed, I'll submit a PR.

**Comment by jennlove-um** [comment]
Testing passes for admin and non-admin users.  In both cases, if the user is not enrolled in a MyLA course, they get the message that they are not enrolled in any courses.
