### ISSUE TITLE
Can't Logout when logged in using SAML2

### ISSUE THREAD

**Issue by rpfernandezjr** [tl-its-umich-edu/my-learning-analytics#786]
## Expected behavior
Users session to be terminated and logged out when the logout button is pressed. Forcing them to have to re-authenticate to log back into the MyLA application.

## Describe the bug 
We are logged in using SAML2 (Using Shibboleth), Once logged in, when a user selects `Logout` from the upper right corner, they are logged out and automatically logged back in.

## Steps to Reproduce :
`DJANGO_LOGOUT_REDIRECT_URL`  is currently set to match the same value as `DJANGO_LOGIN_REDIRECT_URL`, similar to the [sample config.](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/config/env_sample.json#L107-L110)

I have also tried setting `DJANGO_LOGOUT_REDIRECT_URL` to the following:
* /accounts/ls/post
* /accounts/ls/

which are the SingleLogoutService entries defined in `/account/metadata/`

```
<ns0:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://<hostname>/accounts/ls/"/>
<ns0:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://<hostname>/accounts/ls/post"/>
```

In both cases when I tried to Logout, I was thrown a 404.

What is the expected value for `DJANGO_LOGIN_REDIRECT_URL` so that users can successfully log off?

**Comment by jonespm** [comment]
For us we've got
DJANGO_LOGOUT_REDIRECT_URL=https://shibboleth.umich.edu/cgi-bin/logout

So it goes to the actual link that will log you out. This will be different for other schools.
