### ISSUE TITLE
Update the Node version to 12

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#790]
Currently, Docker steps for building the react module we are using Node11.10 version and his version is unsupported and update to Node 12 is the right way to go. More on the Node releases are [here](https://nodejs.org/en/about/releases/). 

Node team seems to support the Even number version as long term support and odd versions an experimental.  More info on this [here](https://medium.com/swlh/understanding-how-node-releases-work-in-2018-6fd356816db4#6f6f)

**Comment by ssciolla** [comment]
I confirmed that the version in the `webpack_watcher` container is `v12.16.3`. I'm moving from Review/QA - Dev to Done.
