### ISSUE TITLE
Grade Distribution Showing Where Outliers Are

### ISSUE THREAD

**Issue by vjcao** [tl-its-umich-edu/my-learning-analytics#794]
## Expected behavior (A clear and concise description of what you expected to happen) :
 
Grade distribution should anonymize outliers so that students are not discouraged by seeing where they are in respect to the rest of the class.

## Describe the bug (Tell us what happens instead of the expected behavior) :
The current histogram groups outliers together but shows where they are in respect to the rest of the class.

Here's an example:
![Screen Shot 2019-11-15 at 4 06 29 PM](https://user-images.githubusercontent.com/33735083/68976111-0c06a280-07c3-11ea-9847-330c55ed4008.png)

The grades data for the screenshot above is:
`"grades": [ 13.0, 13.0, 13.0, 13.0, 13.0, 13.0, 54.0, 67.0, 68.0, ... ]`

Here's another example:
![Screen Shot 2019-11-15 at 4 17 08 PM](https://user-images.githubusercontent.com/33735083/68976257-6b64b280-07c3-11ea-89fb-e3ae0dccc2f2.png)

The grades data for this screenshot is:
`"grades": [ 53.0, 53.0, 53.0, 53.0, 53.0, 56.0, 57.0, 57.0, 57.0, ... ]`

Is this expected behavior?

**Comment by kwanhlee** [comment]
Hi, I am a student taking eecs481 and my team needs to make a contribution to an open source project. I got interested in this project as they have presented my-LA in our class. Would it be okay if my team tackles this bug and update you in our development process?

**Comment by vjcao** [comment]
@kwanhlee thank you for your interest in this issue but I already assigned myself and began working on this issue.

**Comment by jennlove-um** [comment]
I will connect with Pushyami about this to review the original logic and determine if this is the best way to fix the visual.

**Comment by jennlove-um** [comment]
@pushyamig Can we connect to talk about this one?

**Comment by pushyamig** [comment]
ok

**Comment by jennlove-um** [comment]
Testing passes in Canvas test.  Testing was done with multiple courses with varying grade distributions from both prior terms and the current term.
