### ISSUE TITLE
need to switch the hyperlink & modify the word for the "File Accessed" in readme

### ISSUE THREAD

**Issue by jpyan** [tl-its-umich-edu/my-learning-analytics#795]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added
When click on the link for "Files Accessed" part in proj intro, it leads me to link https://sites.google.com/umich.edu/my-learning-analytics-help/home/files-accessed and it shows 404 not found.
<img width="904" alt="Screen Shot 2019-11-17 at 7 16 51 PM" src="https://user-images.githubusercontent.com/35250601/69016698-d8687b80-096e-11ea-810b-b03b160232bb.png">

<img width="1001" alt="Screen Shot 2019-11-17 at 7 15 31 PM" src="https://user-images.githubusercontent.com/35250601/69016679-a35c2900-096e-11ea-8a5a-c22f51a12ad9.png">

## Describe the solution you'd like
When click on it, lead me to a page that actually works.

## Describe any possible alternatives you've considered
Modify the wording "Files Accessed" to "Resources Accessed"
switch the link for "Files Accessed" part in proj intro on the top of readme to the https://sites.google.com/umich.edu/my-learning-analytics-help/home/resources-accessed?authuser=0
## Additional context
I think it's just something forgotten to be updated. It would improve the user experience when they try to understand this project.

**Comment by justin0022** [comment]
Good catch, thanks!
