### ISSUE TITLE
unaccessible urls in read.me

### ISSUE THREAD

**Issue by jpyan** [tl-its-umich-edu/my-learning-analytics#810]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 
(With data myla_test_data_2019_10_16.sql loaded into the database) When logged in as admin and click on  http://localhost:5001/courses/231768 or http://localhost:5001/courses/430174, it should navigate to a functional web page.

## Describe the bug (Tell us what happens instead of the expected behavior) :
Now when logged in as admin and  click on  http://localhost:5001/courses/231768 or http://localhost:5001/courses/430174, it will show "Something went wrong; please try again later."

## Steps to Reproduce :
1. Load myla_test_data_2019_10_16.sql (from drive) to the database
2.Build and log in as admin
3.Click on http://localhost:5001/courses/231768 or http://localhost:5001/courses/430174

## Screenshots/Video (If possible, add media to help explain your problem) :
<img width="841" alt="Screen Shot 2019-11-26 at 7 24 13 PM" src="https://user-images.githubusercontent.com/35250601/69684115-4efb2c80-1085-11ea-8a2e-31faf7c6a350.png">
<img width="1052" alt="Screen Shot 2019-11-26 at 7 45 47 PM" src="https://user-images.githubusercontent.com/35250601/69684126-59b5c180-1085-11ea-81f9-0495a08de23b.png">

## Additional context (Add any other context about the problem here) :
I assume this is caused by switching to the newer dataset. And with the newest dataset, I found with course id 235420 and 362855 will successfully show the course page. (http://localhost:5001/courses/235420 or http://localhost:5001/courses/362855)

<img width="1271" alt="Screen Shot 2019-11-26 at 7 47 51 PM" src="https://user-images.githubusercontent.com/35250601/69684199-a39ea780-1085-11ea-9c74-77d7ec4bbc76.png">

**Comment by justin0022** [comment]
Thanks for catching this. @jonespm are the course IDs randomly generated every time the deidentifier is rerun? If so maybe we should remove hard-coded URLs to specific courses in the README.

**Comment by jonespm** [comment]
Yeah, if we generate the new courses from different original courses the ids change. We were thinking of ways to keep ID's like this more static but haven't figured it out yet. We could also just be more consistent about generating courses from the same source course too.

**Comment by justin0022** [comment]
Okay perhaps for now we can remove links in the README to specific courses. @jpyan do you mind taking this on?

**Comment by jpyan** [comment]
Sure, I can work on that.
