### ISSUE TITLE
Update readme with steps to run Myla on Windows machine

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#814]
Currently Windows 10 Home users are having issues running locally in the docker container We've only tested here on Mac and Linux. One option is To run [Docker with Vitualbox on windows](https://medium.com/@peorth/using-docker-with-virtualbox-and-windows-10-b351e7a34adc).

**Comment by jonespm** [comment]
I might wait until WSL2 is released in which is expected in [20H1 in Spring 2020.](https://www.howtogeek.com/438830/whats-new-in-windows-10s-20h1-update-arriving-spring-2020/) 

This hopefully will make the build better.

**Comment by marciamoraes** [comment]
Here is a list of prerequisites to install MyLA on Windows (using VirtualBox).
https://github.com/tl-its-umich-edu/my-learning-analytics/wiki/Prerequisites-for-Installing-MyLA-on-Windows

**Comment by chrisrrowland** [comment]
Running this on WSL2 currently.  I basically followed the normal instructions.That said I initally tried re-purposing repo that was on windows space from when I was using docker for windows and  had issues.  Be sure to checkout into wsl space.  

At the moment I'm unable to get Cypress installed but will update if I can figure that out.

**Comment by jennlove-um** [comment]
@chrisrrowland Based on your experience getting MyLA up and running on Windows, is all the necessary information now in the README?  If not, could you help update it?  If it is, we can close this issue.

**Comment by chrisrrowland** [comment]
> @chrisrrowland Based on your experience getting MyLA up and running on Windows, is all the necessary information now in the README? If not, could you help update it? If it is, we can close this issue.

Without reinstalling to confirm, I think they look good.  The one hangup I had that stands out in my mind was really user error.  Step 3 of the install explicitly says to create mylasecrets in your user directory but I was trying to use one that already existed from a previous installation on docker for windows vs my current linux docker setup.  I don't think that would be likely to be an issue for people doing a fresh install.  I'll be sure to update if I have to do a clean setup again.
