### ISSUE TITLE
Make primary UI color configurable

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#821]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added

Different institutions should be able to modify the `primary` structural color, which is currently a UM blue (#40658F).

## Describe the solution you'd like

To keep this simple for now, I think I will make this color configurable through `env.json` (`env.json` -> `settings.py` -> `views.py` (`myla_globals`) -> `base.html` -> `App.js`.

## Describe any possible alternatives you've considered

I have also looked into modifying the data model and having the primary color be a field in an institution table, so that the color can be changed via the Django admin interface. Some of our discussions indicated that this would be unnecessary currently and bloat the project with extra code, given that such a value would only be changed a couple times at most in one deployed instance.

I also looked into using a hook and creating an API endpoint to pass data to the frontend. However, it makes sense to leverage `myla_globals` for this application-wide setting.

**Comment by ssciolla** [comment]
I have a fix for this in my issue-821-make-primary-color-configurable branch, which I've based on top of my PR #842. You can see the changes from the issue-specific commits [here](https://github.com/ssciolla/my-learning-analytics/compare/issue-485-django-update-final...ssciolla:issue-821-make-primary-color-configurable).

**Comment by ssciolla** [comment]
PR #842 has been merged, so I've update the issue branch. You can see the comparison to master [here](https://github.com/tl-its-umich-edu/my-learning-analytics/compare/master...ssciolla:issue-821-make-primary-color-configurable)

**Comment by pushyamig** [comment]
When the primary color changes I can see UI pick up the color. We are not configuring color in Myla Test instance just using the default.
