### ISSUE TITLE
Make the entityid value within the SAML_CONFIG dict configurable

### ISSUE THREAD

**Issue by rpfernandezjr** [tl-its-umich-edu/my-learning-analytics#824]
## Describe your problem or feature you'd like added

In order to make MyLA multi tenant, We run MyLA behind a proxy. I'd like to be able to set 

```
SAML_CONFIG['enityid']
```

to a value that I provide via the environment/configs. Right now it's hard coded to 

```
 '%smetadata/' % SAML2_URL_BASE
```

## Describe the solution you'd like

Making that value configurable from the ENV.

```
-        'entityid': '%smetadata/' % SAML2_URL_BASE,
+        'entityid': ENV.get('SAML_CONFIG_ENTITYID', '%smetadata/' % SAML2_URL_BASE),
```

## Describe any possible alternatives you've considered
There currently aren't any, if we run an instance of MyLA for an institution, the url will be:

https://<institution\>/accounts/metadata/

By making this configurable, I can have  SAML2 send users to the metadata for my SP which has the proper ACS for all the institutions that we provide  MyLA service for.

## Additional context
I was trying to create a branch to submit a PR, but I got a permission denied :disappointed: 
Any chance I can get added to the team, to be able to create branches and/or submit PRs?

If not, here's a patch file for what I was going to submit:
```
--- dashboard/settings.py	2019-12-09 21:25:38.664061262 -0600
+++ /tmp/settings.py	2019-12-09 21:25:25.952163403 -0600
@@ -305,7 +305,7 @@
 
     SAML_CONFIG = {
         'xmlsec_binary': '/usr/bin/xmlsec1',
-        'entityid': '%smetadata/' % SAML2_URL_BASE,
+        'entityid': ENV.get('SAML_CONFIG_ENTITYID', '%smetadata/' % SAML2_URL_BASE),
 
         # directory with attribute mapping
         # 'attribute_map_dir': path.join(BASEDIR, 'attribute-maps'),
```

**Comment by jonespm** [comment]
Sam did make that configurable for another of our projects basically the same way in https://github.com/tl-its-umich-edu/student_explorer/pull/188 but I'd wanted to rewrite this entire SAML block so it was all configurable via JSON on #741 and haven't done that yet. This might be the quick fix if you wanted to fix it similar to that. We didn't end up needing that fix though and just used the default but I can see where it's useful.

As far as the branch, you should fork this, create a branch in your fork and doing a PR from there. See more info in the [Contributing->Making a Pull Request](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/CONTRIBUTING.md#making-a-pull-request). If you were interested in reviewing PR's, issues and participating more with the working group (via bi-weekly phone calls) we could add you to the team, though we want to avoid branches in this repo.

**Comment by rpfernandezjr** [comment]
Ah ok thanks, I'll start forking for any contributions moving forward. I can hold out for https://github.com/tl-its-umich-edu/my-learning-analytics/issues/741 or for https://github.com/tl-its-umich-edu/student_explorer/pull/188 to make it into master.

**Comment by jonespm** [comment]
SAML is going to be removed in #1212 so closing this issue
