### ISSUE TITLE
Show MiVideo (Kaltura) media in Resources Accessed view

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#826]
MiVideo (Kaltura) files should be included in the Resources Accessed.  They should be considered video files (like Lecture Capture).

**Comment by jennlove-um** [comment]
I couldn't find another issue that was specific to Kaltura, so I created this issue for tracking the status of this development and testing.

**Comment by johnpj** [comment]
Sample query for extracting MiVideo data:

SELECT
JSON_EXTRACT_SCALAR(event, "$.object.extensions.kaf:course_id") as course_id, 
JSON_EXTRACT_SCALAR(event, "$.object.name") as media_title,
JSON_EXTRACT_SCALAR(event, "$.actor.name") as actor_name,
JSON_EXTRACT_SCALAR(event, "$.actor.id") as actors_id,
*
FROM 
`udp-umich-prod.event_store.events` 
WHERE 
ed_app LIKE '%mivideo%'
AND
JSON_EXTRACT_SCALAR(event, "$.object.extensions.kaf:course_id") = '261179'

**Comment by lsloan** [comment]
Hi, @jennlove-um & @johnpj.

Zhen suggested this would be a good first issue for me.  I've not run MyLA locally yet, so I will need to get that up and running first.

**Comment by jennlove-um** [comment]
It would be great if you could help get this working.  Thanks!!

**Comment by jonespm** [comment]
Was this still in progress, did you need any help on this? It should just a config change and getting the query in there correctly. Would go right after the [lecture capture config.](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/6c5399a42799dca6bc04f7e5765aaa36339e7fbb/config/env_sample.json#L206)

**Comment by jennlove-um** [comment]
I am able to see Kaltura videos and their events in the Resources Accessed view.  testing passes
