### ISSUE TITLE
New Styling on Hyperlinks Does not Appear on Browsers Other than Firefox

### ISSUE THREAD

**Issue by vjcao** [tl-its-umich-edu/my-learning-analytics#830]
## Expected Behavior: 
PR #775 tried to make MyLA's styling consistent and accessible to users. This PR changed the way hyperlinks looked by allowing them to have two colors: one color for visited (#551A8B) and one for normal links (#0000EE). 

Firefox:
![Screen Shot 2019-12-17 at 4 40 38 PM](https://user-images.githubusercontent.com/33735083/71036800-5cd42880-20ec-11ea-88c4-9d0115ce9f33.png)

## Describe the bug:
This change, however, only works when the user is using Firefox to run MyLA. Other browsers I used (Chrome, Safari, and Opera) do not reflect this change. The links just appear as grey text instead of the intended blue colors.

## Steps to Reproduce:
1. Build MyLA
2. Run localhost on any browser that's not Firefox
3. View the Resources Accessed view and see grey hyperlinks on file names

## Screenshots:
Chrome:
![Screen Shot 2019-12-17 at 4 33 08 PM](https://user-images.githubusercontent.com/33735083/71036896-9442d500-20ec-11ea-88a8-ab000f01b745.png)

Safari:
<img width="1436" alt="Screen Shot 2019-12-17 at 4 33 39 PM" src="https://user-images.githubusercontent.com/33735083/71036912-9d33a680-20ec-11ea-87fd-241257d26464.png">

Opera:
<img width="1399" alt="Screen Shot 2019-12-17 at 4 34 57 PM" src="https://user-images.githubusercontent.com/33735083/71036936-a7ee3b80-20ec-11ea-8b7d-ae77e79feb70.png">

**Comment by jennlove-um** [comment]
Testing passes: Links display in the same blue in different browsers.  Tested with Firefox and Chrome.
