### ISSUE TITLE
Add show_grade_type field into test sql file

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#833]
## Expected behavior (A clear and concise description of what you expected to happen) : 
MyLA courses do not display with the latest master and latest sql file.

## Describe the bug (Tell us what happens instead of the expected behavior) :
`myla_test_data_2019_10_16.sql` file doesn't have the `show_grade_type` field, causing the course `info` endpoint to fail with the error message attached below. 

## Steps to Reproduce :
1. Load the latest master and latest sql file. 
1. Navigate to any course.

## Screenshots/Video (If possible, add media to help explain your problem) :
<img width="763" alt="Screen Shot 2020-01-03 at 9 19 16 AM" src="https://user-images.githubusercontent.com/8836578/71738094-78d50b00-2e0a-11ea-8016-fa7682b3d874.png">

**Comment by jonespm** [comment]
Yeah, this should run fine if you just migrate but we'll need to include this in the next SQL script.

**Comment by justin0022** [comment]
Thanks!

**Comment by jennlove-um** [comment]
`myla_test_data_2020_12_08.sql` has the `show_grade_type` field added.  I'm closing this issue.
