### ISSUE TITLE
On the resource view, the file names start out okay but move when scrolling

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#836]
## Expected behavior (A clear and concise description of what you expected to happen) : 
File names should stay in place

## Describe the bug (Tell us what happens instead of the expected behavior) :
When you first view the files page the names appear correct, however after scrolling the display they appear to jump over to overlap. I think this is a recent change. 

Tested in Chrome 79 and Firefox. Not sure what's causing this yet.

![image](https://user-images.githubusercontent.com/27447/71746825-011fd400-2e3c-11ea-901a-4106813cee07.png)

**Comment by jonespm** [comment]
I think this is related to the createResourceAccessChart changes on 177816663c337f83740e3a75f3ead15a5c509ca3

**Comment by pushyamig** [comment]
I am going to tag it to the Winter 2020 project.

**Comment by jennlove-um** [comment]
Testing passes: The file names remain correctly aligned when I scroll up and down and resize the window.  I am not able to get them to go out of alignment.

**Comment by jennlove-um** [comment]
@johnpj Is this the problem you saw in testing today?

**Comment by johnpj** [comment]
@jennlove-um I saw something similar, but only one line was overlapping the adjoining bar chart. It only happend once and I could not reproduce it.

**Comment by jennlove-um** [comment]
Since neither @johnpj nor I can reproduce this behavior, I'm going to say testing passes for this issue.  If we see the behavior or something similar that we can replicate, I'll open a new issue.
