### ISSUE TITLE
Truncating to 7 characters feels a little short, should make this value larger

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#837]
## Expected behavior (A clear and concise description of what you expected to happen) : 
The new resources view is truncating to 7 characters with no way to change from https://github.com/tl-its-umich-edu/my-learning-analytics/blob/177816663c337f83740e3a75f3ead15a5c509ca3/assets/src/components/d3/createResourceAccessChart.js#L233

This seems a little short. It looks like file names in Canvas get about 40 characters until they're truncated. I think we should work to at least fit 20 characters and seems like there's more space.

![image](https://user-images.githubusercontent.com/27447/71747537-ec444000-2e3d-11ea-8166-1df06d056896.png)

**Comment by jonespm** [comment]
I wonder if we'd have to use a fixed width font here for these file names? 23 characters all caps looks like it overlaps at about character 18 now. Also I don't know why we have 4 dots for some of these? 

I think we either need to re-open this or still do something to fix this. Fixed width font, reduce the characters a few more or move everything more left. (There seems to be a lot of space in the margins)

![image](https://user-images.githubusercontent.com/27447/72260549-17b6ef80-35e1-11ea-8899-b8b26cd8104f.png)

**Comment by jennlove-um** [comment]
@pushyamig Testing is okay in myla-test.  Do you want to close this issue with the limited fix in place so far and open a new issue for improvements in the future?

**Comment by pushyamig** [comment]
We will close this issue, I will open another one and put it in winter.02.02
