### ISSUE TITLE
myla_globals is not available to some templates

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#843]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 

Pages that use the `base.html` template (most if not all of them) should have access to `myla_globals` since it's referenced there in a a `<script>` tag.

## Describe the bug (Tell us what happens instead of the expected behavior) :

When I moved `myla_globals` into the `get_home_template` view as part of #784, I neglected to consider that some other views might need `myla_globals` in their context. As part of my work on #842, I discovered that `registration/login.html` extends `base.html`, and because it doesn't have `myla_globals` in its context, it leads to errors in the logs and in the browser console (though it doesn't break the application).

**Log**
![Screen Shot 2020-01-13 at 10 34 04 AM](https://user-images.githubusercontent.com/35741256/72268708-52745400-35f0-11ea-9b83-7de029a34f5b.png)

**Browser console**
![Screen Shot 2020-01-13 at 10 35 37 AM](https://user-images.githubusercontent.com/35741256/72268780-759f0380-35f0-11ea-9c65-abd66743f44d.png)

## Steps to Reproduce :
1. Start MyLA locally.
2. Ensure you are logged out, and log out if necessary.
3. Visit `localhost:5001` or `localhost:5001/accounts/login`.
4. Observe log and web console.

## Additional context (Add any other context about the problem here) :

I have a fix for this as part of #842. I've elected to use a context processor, so that `myla_globals` will be automatically available to all templates using `base.html` without being specified in as part of a particular view's context.

**Comment by jonespm** [comment]
I'm not seeing any errors in the console log and this seems to be available as expected.
