### ISSUE TITLE
MyLA help URL in flat pages is not working as expected

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#846]
Per pull request #697, the help URL for MyLA can be set up using the flat pages.  I tried adding a flat page to test-myla.tl.it.umich.edu. 

Per the detail in the pull request, on the new flat page I set the URL to /help_url/ and entered the content as "https://its.umich.edu/academics-research/teaching-learning/my-learning-analytics" to test going to a different help page.  

When I click on help, I get the warning message "Course Copyright University of Michigan Regents, 2019. does not exist."  It looks like MyLA is trying to link to the copyright page instead of to the URL provided in the help flat page.

**Comment by ssciolla** [comment]
Yep, I'm fairly sure this isn't working because it assumes the Help URL entry is coming first. I'm not sure we are using flatpages as intended, but if we want a quick fix and like having it available to change through the Django admin, I think this small fix which I whipped should work:

https://github.com/ssciolla/my-learning-analytics/blob/96dea9677be10b577ed1e411f6425e1cd04a16e5/dashboard/common/utils.py#L69-L73

**Comment by jonespm** [comment]
Yeah, I don't think it makes sense to have the URL defined in the flatpages and #697 wasn't right to begin with. This should just be in the settings if it's a URL. The idea of flatpages it to store simple HTML content in the database for special one off pages. This doesn't make sense a a URL but would make sense if we wanted the entire help *content* in defined here. But I don't think someone would need to write a lot more content for their help. 

I can see putting future Help onto Github as Github Sites, then schools can fork this and customize their help. I think what we did was just the *quickie* help documents.  But it will still be a URL.

**Comment by ssciolla** [comment]
That makes sense to me. I can make this change.

**Comment by jennlove-um** [comment]
@ssciolla Have we configured test to use the new URL for help?

**Comment by jennlove-um** [comment]
Testing passed.  MyLA test was configured with the updated help link. I tested the help from the main page, a course main page, assignment page, resources page, and grade distribution page.  All help links went to the correct help page for the context.
