### ISSUE TITLE
Make the term in the admin UI uneditable and indicate when it will be updated

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#850]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added

The Terms dropdown in the Admin UI can be confusing as it's generally auto-populated by Canvas and shouldn't need to be set. The term is always updated because currently all of the terms are removed from the table during the cron job and reset. Because of this workflow we should just have the term as a read-only field rather than one that can be set by the user. It should display the current term that is detected or some placeholder like "Term will be set on next update" if it hasn't yet been set.

**Comment by ssciolla** [comment]
I'm confused. Isn't the field read-only already in the admin UI?

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/b167df95c33bf69d2f73d604e9538f26e55fbfbb/dashboard/admin.py#L50-L54

**Comment by jennlove-um** [comment]
I'm closing this issue.  The term field is not currently editable in the Admin UI.
