### ISSUE TITLE
Show Grade Counts not working in Grade Distribution view

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#851]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 

When the "Show Grade Counts" option is checked in the Django admin, the numbers should appear on the bars in the histogram in the Grade Distribution view.

## Describe the bug (Tell us what happens instead of the expected behavior) :

This doesn't appear to be working. It looks like there was a small typo in PR #793, to where the updated value for `show_number_on_bars` is assigned to `summary['show_summary_on_bar']`.

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/785acebff007c56e3090e65820ca4e6292668da5/dashboard/views.py#L328-L329

## Steps to Reproduce :
1. Make sure "Show Grade Counts" is checked for a course.
2. View Grades Distribution view for that course.

**Comment by jennlove-um** [comment]
Testing passes: I tested both checking and unchecking the setting.  The display correctly showed the numbers when checked and did not show them when unchecked.
