### ISSUE TITLE
Webpack watcher slow in noticing code changes

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#855]
Webpack watcher is great for instant code redeploy when changes are made. I can see a couple of things with the way it is performing
1. Takes a couple of seconds to redeploy not as instantaneous as Backend watcher 
2. Sometimes it saturates doesn't recognize change at all and needs a restart the instance to activate it back.
3. `console.log` statements are not recognized most of the time if that's the only change you made

**Comment by justin0022** [comment]
Sometimes, when webpack watcher acts up, I clean my Docker and restart, and then the problem seems to go away. Most of the time it works without issue for me. 

Have you tried deleting the files in `assets/dist`? It may be because that directory is getting big.

**Comment by pushyamig** [comment]
> I clean my Docker and restart

Most of the time I do this too

> Have you tried deleting the files in assets/dist? It may be because that directory is getting big.

I did try this approach as well.

but it just feels very annoying when you need the performance when you are working on an issue. In those times I feel if a manual redeploy command is available instead of restart docker.

**Comment by justin0022** [comment]
I'm going to try and improve this. Also hoping the improvements will address: #648.

**Comment by pushyamig** [comment]
I was reading how to delete the existing bundle before creating a new one. Some suggested using this https://www.npmjs.com/package/clean-webpack-plugin. But I did not get to a point testing it.
I don't know if delete the entire `/dist` folder is a good option since it also deletes the `static` folder that has font needed by material UI

**Comment by jennlove-um** [comment]
Per discussion with Pushyami, I'm closing this issue.
