### ISSUE TITLE
Traceback from Grade Distribution view with less than five grades

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#857]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 

The Grades Distribution view should provide a meaningful result, even when there are no grades or only a couple of them. The Django view should also execute without tracebacks.

## Describe the bug (Tell us what happens instead of the expected behavior) :

When I visited the Grades Distribution page for a course with only a couple of grades, I saw the standard "Something went wrong; please try again later" message. In the logs, there was a traceback from the `grade_distribution` view:

```
File "/code/dashboard/views.py", line 335, in grade_distribution
BinningGrade = find_binning_grade_value(grades)
File "/code/dashboard/views.py", line 658, in find_binning_grade_value
fifth_item = grades[4]
IndexError: list index out of range
```

## Steps to Reproduce :
1. Set up MyLA.
2. Run the cron for a course with less than five grades for students
3. Visit the Grades Distribution view for that course.

**Comment by ssciolla** [comment]
@pushyamig and @jennlove-um, have either of you seen this before? Is this something we need to fix for the next release?

**Comment by pushyamig** [comment]
I think we need to handle this case since binning logging trying to get the first 5 grades. In case of very few grades < 5 then we need to handle it gracefully.

**Comment by pushyamig** [comment]
@ssciolla  which course were you testing? This bug can happen when No. of student in course are < 4 but I don't we want to enable Grade distribution in that case. Or this bug can also happen when only < 5 grades released with class roster > 5

**Comment by jennlove-um** [comment]
Testing passed: I tested this with a class that has only 2 grades for students.  The Grade Distribution correctly displayed the message "Grade data is not available."
