### ISSUE TITLE
Course select query includes unnecessary fields

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#864]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 

In general, we should limit SQL select queries to only the data we need. This may provide slight performance improvements and minimize possible issues resulting from data appearing in the logs.

## Describe the bug (Tell us what happens instead of the expected behavior) :

As part of `cron.py`, we are using a `SELECT * from course_dim` query when pulling course data, which retrieves data for a number of fields we are not using, including syllabus content which can sometimes include long strings. We should limit the `SELECT` to only columns that are used by the cron process and MyLA application.

UPDATE: Previously, this issue mentioned Jenkins build failures that we thought might be caused by occurrences of error in course data that was logged. We think now this was caused by timeouts, not the occurrence of this string.

**Comment by ssciolla** [comment]
Odd, this doesn't seem to happen consistently. The same "error" appeared in recent runs of the cron. It still seems worth trying to minimize data that is logged, but it may be a different issue.

**Comment by ssciolla** [comment]
I merged my fix about limiting the select query, but let's keep the issue open, since I don't think we've fully diagnosed this problem.

**Comment by jonespm** [comment]
From what I can see in from the logs it failed because it timed out rather than an error. I created https://github.com/tl-its-umich-edu/openshift-jenkins-configs/issues/22 to better catch that case. It should only catch ERROR (in all caps) and I did test that locally. I don't think "error" in text should trigger this. I feel like if we need another issue to address this that's fine but we should change the title of this one to better reflect what was done and create that as another issue.

**Comment by ssciolla** [comment]
@jonespm, if you created an issue in the OpenShift repo, I think it's fine to make the changes you suggested.

**Comment by ssciolla** [comment]
@jonespm, okay, I've updated this issue to reflect what we actually ended up changing.

**Comment by jonespm** [comment]
Verified that this works now

**Comment by zqian** [comment]
Verified from the log message: 

It is now:

select id, canvas_id, enrollment_term_id, name, start_at, conclude_at from course_dim where c.id='...'

vs it was the following select before:

select * from course_dim c where c.id='...'
