### ISSUE TITLE
[Resources Accessed] Minor UI improvements

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#869]
Feedback from today's MyLA meeting for revising this view: 

- [x] Add the icon next to the checkboxes for the files type at the top as well to make it clear which icon is associated with each file type
- [x] Review the fonts on the page to make sure they are all the same (different sizes are fine, but different fonts aren't)

_Originally posted by @jennlove-um in https://github.com/tl-its-umich-edu/my-learning-analytics/issues/693#issuecomment-565182335_

**Comment by jennlove-um** [comment]
The researchers confirmed that the layout of the headings on the screen is find as is, so I'm removing this requirement: 
Left-align the text for the filters (selecting the grade range drop-down and checkboxes) and the legend (resources viewed/not viewed) to be aligned with the Y-axis.  The issue here is that there are too many different starting points for reading down the screen.

**Comment by ssciolla** [comment]
I think we can close this, since @vjcao seems to have resolved both of the remaining items in PR #925.

**Comment by jennlove-um** [comment]
testing passes - the icons display and the fonts look good.
