### ISSUE TITLE
When DataFrames from some queries are concatenated, NaT is replaced with None in datetime fields

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#870]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 

The code that updates the datetime fields in the course table should be able to run without error.

## Describe the bug (Tell us what happens instead of the expected behavior) :

After the changes in PR #868, we encountered errors when running the cron that suggested the null handling was no longer working. After some investigation, I determined that when we use pd.concat() on line 136, `None` values appears to be converted to `NaT`. This was not occurring before when we used `SELECT * FROM ...`, but is now happening when we specify fields. The `NaT`s are not properly handled by `update_datetime_field`, leading to errors further on in the code.

## Steps to Reproduce :
1. Add a course to MyLA that you know doesn't have a course start or end date, and one that you know does have course start and end dates.
2. Run the cron.
3. Observe the errors and premature ending in the log message.

**Comment by jonespm** [comment]
Fixed by #871

**Comment by jonespm** [comment]
I verified that the cron ran after this change. I believe it's good!
