### ISSUE TITLE
Find Earliest Start Date Time of course should display course where earliest date found

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#873]
## Describe the bug (Tell us what happens instead of the expected behavior) :
In the utils.py the line to log the earliest start date should include the course id that this date was found in to make it easier to track these early courses down.
https://github.com/tl-its-umich-edu/my-learning-analytics/blob/8723b0b79458a42c141f84ec98236820f295d8a8/dashboard/common/utils.py#L20

## Steps to Reproduce :
1. Run the cron
2. Log for the line 

> Earliest start datetime for all courses:

**Comment by jonespm** [comment]
I think to do this we'll have to have a map keeping the course id and the earliest date. Right now it looks like it's just keeping the dates

**Comment by jonespm** [comment]
To test this:

* Have at least 2 courses with different terms

* Look at the logs after running the cron you should see a line like
`[2020-03-11 14:48:25 -0400] [INFO] [utils.py:18] Earliest start datetime for all courses: 2020-01-08T01:55:00+00:00 found in course 123456`

This should match the earliest course. Some courses may have the same term (and thus same start date) this is fine.

**Comment by zqian** [comment]
verified from log files of both localhost and on MyLA test instance, that the text string of "Earliest start datetime for all courses: <timestamp> found in course <course_id>" is displayed.
