### ISSUE TITLE
createHistogram.test.js test fails after recent mylaGlobals changes

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#874]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 

All frontend tests that are implemented should run successfully and have access to any variables they need, even if they are `null`.

## Describe the bug (Tell us what happens instead of the expected behavior) :

When running the frontend tests currently using `docker exec -it webpack_watcher npm test`, the `createHitogram.test.js` suite fails because of a new line in `globals.js` (which the `d3` component, `createHistogram` relies on because of its use of `siteTheme.js`). `globals.js` tries to get the `textContent` from a nonexistent element (`null`), which then makes the test fail. Note: `globals.js` was introduced in PR #845.

## Steps to Reproduce :
1. Start MyLA locally.
2. Run `docker exec -it webpack_watcher npm test`

**Comment by zqian** [comment]
verified the tests all pass. 

![image](https://user-images.githubusercontent.com/359944/73877144-254d4700-4826-11ea-8f5a-c55748dd6e0a.png)

Logged in as root and verified nothing break.
