### ISSUE TITLE
[Redesign assignment] Write more tests (E2E & unit)

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#879]
For E2E, look into using https://www.cypress.io/?

**Comment by pushyamig** [comment]
This has gone through the First pass of development and this should be marked as done and close the issue

**Comment by pushyamig** [comment]
@chrisrrowland I don't know where you are at the Cypress set up locally. will you able to test this and resolve it.

**Comment by chrisrrowland** [comment]
@pushyamig I started out looking at a UI  issue. Haven't looked to deeply into Cypress yet.

**Comment by pushyamig** [comment]
@chrisrrowland Then I don't want to burden for testing and resolving it.

**Comment by pushyamig** [comment]
@jonespm can you test this and mark it as Done
