### ISSUE TITLE
[Redesign assignment] Weird rounding behaviour

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#881]
https://www.youtube.com/watch?v=S2fRNzXuGPs&feature=youtu.be

When lock grade is checked/unchecked, the goal grade changes sometimes.

**Comment by ssciolla** [comment]
I've started thinking about this again. It looks to me like when you lock a grade, you end up storing the rounded value, and the other scores adjust accordingly. This can lead to the behavior @justin0022 captured where it looks like things are changing when they shouldn't; locking the grade is actually changing the calculations behind the scenes.

I haven't figured out exactly how or if we should resolve this. We could store the actual score somewhere and lock that, but would that confuse people if they think they're locking the score they see?

The relevant files here are `util/assignment.js` and `container/AssignmentPlanningV2.js`.

**Comment by justin0022** [comment]
Is this behavior still occurring? I can do a quick test for it tomorrow - I'm asking because I vaguely recall thinking that this was fixed as a side effect of a different pull request.

**Comment by ssciolla** [comment]
Good question. If you could confirm it's no longer an issue, that would be great. I was having difficulty re-producing this, but I figured I just hadn't yet set up the right scenario.

**Comment by justin0022** [comment]
Working on it

**Comment by jennlove-um** [comment]
testing passes.  I am no longer able to produce the odd behavior
