### ISSUE TITLE
[Resources Accessed] Course showing the percent of students accessing the file as 101

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#886]
##  Expected behavior (A clear and concise description of what you expected to happen) : 
The percent of students who access the file in a course should never be above 100%.

## Describe the bug (Tell us what happens instead of the expected behavior) :
For one course, I'm seeing two files that show 101% of students in the course accessed the file.

## Steps to Reproduce :
Unclear how to reproduce yet based on the data in the course.

## Screenshots/Video (If possible, add media to help explain your problem) :
![image](https://user-images.githubusercontent.com/39634416/73943599-064ec380-48bf-11ea-9b8d-9778a13e4992.png)

**Comment by jonespm** [comment]
I rolled back to the 2019.02.x branch and it had the same problem back then so this isn't a new issue.

![image](https://user-images.githubusercontent.com/27447/73946418-e53ca180-48c3-11ea-85c7-f1a9978b014a.png)

**Comment by jennlove-um** [comment]
Testing passes.  I was able to verify that a the course in prod that shows 101% now shows 100% in test with the new code.
