### ISSUE TITLE
Add favicon to application

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#890]
We do have an icon for this tool, we should use this as the favicon so it will be used as an icon in the tabs. 

The favicon is a separate issue and should probably be split out. We don't actually have an icon for this tool but that could be created and placed.

To Test, open MyLA, look at the tab. It should be the icon rather than a generic globe.

![image](https://user-images.githubusercontent.com/27447/73978548-8c3c3000-48fa-11ea-840e-437c891aed06.png)

_Originally posted by @jonespm in https://github.com/tl-its-umich-edu/my-learning-analytics/issues/783#issuecomment-563428232_

**Comment by lsloan** [comment]
@jonespm when I run MyLA locally from the master branch, I see the favicon when I load the user pages.  However, when I use the admin interface, I do not.  It would be nice to have the favicon appear for those pages as well.  Like you said, it helps the MyLA tabs stand out in the browser, which is important to admins, too.

**Comment by jonespm** [comment]
Thanks for testing, I didn't even think about the admin, it looks like that has to have a separate fix. I can create a new issue for that as it will be some additional work on top of this.

**Comment by jennlove-um** [comment]
Favicon testing worked in non-admin views in Firefox and Chrome.  Testing passes.
