### ISSUE TITLE
All the API URL's should include a trailing slash for better fetching data

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#895]
The [path](https://docs.djangoproject.com/en/2.2/ref/urls/) function URL pattern should include trailing slash to enable fetching results if API is called with or without trailing slash. According to the documentation that's what is recommended. This was [fixed](https://github.com/tl-its-umich-edu/my-learning-analytics/pull/894) for `course_enabled` URL but need to apply the same pattern to other API URL's as well

**Comment by zqian** [comment]
@pushyamig @ssciolla  new URL endpoints got introduced lately without trailing slashes, e.g. "graphql", etc. Should we address those urls, too?

**Comment by ssciolla** [comment]
@zqian, please read through the comments on PR #899. Or the comments in `urls.py`. There were a couple cases, including `graphql`.

Also, I don't think any new URLs have been added since this was merged.

**Comment by zqian** [comment]
@ssciolla sorry for missing the comment line!
