### ISSUE TITLE
Hamburger Menu Button Focus Ambiguity

### ISSUE THREAD

**Issue by vjcao** [tl-its-umich-edu/my-learning-analytics#896]
## Describe the bug (Tell us what happens instead of the expected behavior) :
After PR #863, when using the keyboard to navigate the hamburger menu buttons, the currently selected view button looks the same as which button currently has keyboard focus. This introduces some ambiguity to which button has focus in the hamburger menu.

## Screenshots/Video (If possible, add media to help explain your problem) :
![Screen Shot 2020-02-11 at 4 51 21 PM](https://user-images.githubusercontent.com/33735083/74282818-cc325700-4cee-11ea-9cd3-6688d4592920.png)
Which button currently has keyboard focus? Your guess is as good as mine.

**Comment by jennlove-um** [comment]
Testing passes with SpringSummer  2020.02.01 release

**Comment by gsilver** [comment]
@pushyamig @jennlove-um - mark as done. Grey background clearly shows what menu item has focus.
