### ISSUE TITLE
Round resources access to whole numbers instead of to one decimal point

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#905]
@vjcao & @jonespm Could we go back to rounding to whole numbers instead of to one decimal point for this one?  I don't think we need to be any more precise than the whole number. With the addition of the percent sign, having another decimal place makes the information longer than necessary with no real pay off.

_Originally posted by @jennlove-um in https://github.com/tl-its-umich-edu/my-learning-analytics/issues/887#issuecomment-592132776_

**Comment by jonespm** [comment]
Were you looking at this one @vjcao ? I *think* it should only involve a simple change in the views.py in resource_access_within_week but haven't looked into it yet.

**Comment by vjcao** [comment]
@jonespm I wasn't sure if you were going to work on it so I unassigned myself. I can do it if you want.

**Comment by jennlove-um** [comment]
Testing passes.  Percents display in whole numbers.
