### ISSUE TITLE
Text does not fit inside new assignment planning goal box

### ISSUE THREAD

**Issue by mcrwong** [tl-its-umich-edu/my-learning-analytics#906]
## Expected behavior (A clear and concise description of what you expected to happen) : 
![working_text](https://user-images.githubusercontent.com/6541192/75567625-d5763000-5a1f-11ea-8e7d-11f8c82ce4b7.png)

The text should fit inside the box properly as seen above.

## Describe the bug (Tell us what happens instead of the expected behavior) :
![not_working_text](https://user-images.githubusercontent.com/6541192/75567678-e8890000-5a1f-11ea-8d27-7992b206f30b.png)

However some text is too large and no longer fits inside the box

## Steps to Reproduce :
1. Log in as a student without a full grade progress.
2. Go to the new Assignment Planing page

**Comment by justin0022** [comment]
@jennlove-um should we modifying the wording for this? `Math may no longer add up` is not that clear anyway.

**Comment by jennlove-um** [comment]
Testing passes.
