### ISSUE TITLE
reverse resource view scrolling direction

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/my-learning-analytics#913]
### Expected behavior

Resource view scrolling should follow same direction as page scrolling.

### Describe the bug

The action to scroll the resource view is currently the opposite of that to scroll the page.

### Steps to Reproduce

1. Try scrolling a long web page.
1. Try scrolling the resource view.
1. Notice the different action required.

### Environment:

* **OS**: macOS 10.14.5
* **Browser**: Google Chrome 80.0.3987.163
* **Scroll setting**: macOS "Trackpad" preference panel's "Scroll Direction: Natural" setting is enabled.

**Comment by yuandrew** [comment]
Hi, I would like to work on this issue!

**Comment by yuandrew** [comment]
I'm trying to reproduce the bug, but I'm having issues getting the resource view list to load. When I go to the resources page for a course, I get a grey pulsing circle. Any suggestions on getting resources to load? I've already tried run the demo_init.sh script to see if that helped load the data.


<img width="1238" alt="Screen Shot 2020-04-10 at 3 03 25 PM" src="https://user-images.githubusercontent.com/25187103/79016240-6fabb680-7b3c-11ea-9b73-e1f8507a90a9.png">

**Comment by jonespm** [comment]
Were you using the SQL file from Step 9 in the Installation? You currently need to load the database with this data.

**Comment by yuandrew** [comment]
Yes, I'm pretty sure I've set up the SQL database correctly, I've queried into it to get the list of available courses, as well as created a new user. The "assignment planning" and "grade distribution" pages both populate with data, I'm just having issues with the resource page for some reason.

**Comment by zqian** [comment]
@yuandrew is there any error message from docker log or browser console window?

**Comment by yuandrew** [comment]
Yeah, it looks like I'm getting 500 error for trying to send the API a GET request

GET http://localhost:5001/api/v1/courses/362855/resource_access_within_week/?week_num_start=1&week_num_end=9&grade=90-100&resource_type=Files 500 (Internal Server Error)

Also not sure if this is significant, but one of my docker containers has exited
![image](https://user-images.githubusercontent.com/25187103/79168337-a6d9cc00-7db7-11ea-9bc6-551e4105c0e1.png)

**Comment by vjcao** [comment]
Hi @yuandrew, I ran into the same issue as you when using the latest sample data, `myla_test_data_2020_03_11.sql`. After using `myla_test_data_1_16_20.sql` in the outdated sample folder in the [google drive](https://drive.google.com/drive/u/0/folders/1ILnY3ejEbNU9IM5wBj_UPuLN6dgvZNcn), the issue seems to be resolved.

**Comment by yuandrew** [comment]
@vjcao Thanks for helping look into the issue I'm having!
<img width="1280" alt="Screen Shot 2020-04-18 at 3 42 00 PM" src="https://user-images.githubusercontent.com/25187103/79669684-2fc37f80-818b-11ea-9a76-b5b5beac59e3.png">

I seem to still be getting the same issue, even after using the `myla_test_data_1_16_20.sql` file. Is there anything I might need to do outside of regular set of instructions? I am still able to load the assignments page without error, as well as the grades page.

From the Docker logs, it looks like the error says `(1054, "Unknown column 'r.resource_id' in 'where clause'")` from the query 
`SELECT a.resource_id as resource_id, r.resource_type as resource_type, r.name as resource_name, u.current_grade as current_grade, a.user_id as user_id
FROM resource r, resource_access a, user u, course c, academic_terms t
WHERE a.resource_id = r.resource_id and a.user_id = u.user_id
and r.course_id = c.id and c.term_id = t.id
and a.access_time > %(start_time)s
and a.access_time < %(end_time)s
and r.course_id = %(course_id)s
and u.course_id = %(course_id)s
and u.enrollment_type = 'StudentEnrollment`

**Comment by ssciolla** [comment]
@yuandrew, please make sure you have run the Django migrations after loading the January dump file. It looks like the code isn't matching the database schema.

To apply migrations (which you may already know how to do), you need to use `docker exec` to get into the shell:
```
docker exec -it student_dashboard /bin/bash
python manage.py migrate
```

You might also be able to just spin down the server, and start up again, since I believe `python manage.py migrate` gets run somewhere during the start up.

If you continue to have issues, please comment and @ me. I'm happy to set up a time to help you debug, if that's necessary. Also, apologies for the SQL dump difficulties; I'm investigating now why the latest one is having issues.

**Comment by ssciolla** [comment]
@yuandrew , okay, I have an update. The last two migrations from March and January seem to have been invalidated by some manual migration changes that were made during some recent commits. I have created and updated a new dump based on the October one that seems to work just fine. Please find try the dump file dated 2020_04_20 and try that one; you shouldn't need to run migrations.

**Comment by jennlove-um** [comment]
Testing passes in Firefox & Chrome on Windows.  

@lsloan Could you test on the Mac in Safari for this one since that's where the issue originally came up?

**Comment by jonespm** [comment]
I'd tested this out in Safari
