### ISSUE TITLE
Add favicon for Django Admin Pages

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#914]
@jonespm when I run MyLA locally from the master branch, I see the favicon when I load the user pages.  However, when I use the admin interface, I do not.  It would be nice to have the favicon appear for those pages as well.  Like you said, it helps the MyLA tabs stand out in the browser, which is important to admins, too.

_Originally posted by @lsloan in https://github.com/tl-its-umich-edu/my-learning-analytics/issues/890#issuecomment-597085084_

**Comment by jonespm** [comment]
I looks like [the suggestions here](https://stackoverflow.com/questions/34959897/set-favicon-in-django-admin)  might be the way to fix this if anyone wants to try it out.

**Comment by jennlove-um** [comment]
Since MyLA is an LTI tool, this is not an issue.
