### ISSUE TITLE
Small x-axis overflow bug

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#916]
## Describe the bug (Tell us what happens instead of the expected behavior) :
To the right of the screen, there's overflow a couple of pixels, which is causing the x-axis scroll bar to display. 
![Screen Shot 2020-03-11 at 2 44 16 PM](https://user-images.githubusercontent.com/8836578/76467465-eb340f80-63a6-11ea-8a07-b4c47e35d6c5.png)

May have been introduced in: https://github.com/tl-its-umich-edu/my-learning-analytics/pull/888

**Comment by jennlove-um** [comment]
Unable to reproduce the bug, so testing passes.
