### ISSUE TITLE
Cron fails when same resource is used in separate courses

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#918]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Describe the bug (Tell us what happens instead of the expected behavior) :
Cron is failing when accessing resources data( like lecture video )with the same id used on multiple courses. This is probably occurring due to the Primary key on the resource id which is the resource id of the file. 

The better solution to fix this will be use auto-increment id and a separate column called `resource_id` 

 By Default, cron is only checking if course exists in the Canvas Dataware house(CDH) and if some of the courses added to Myla don't have a presence in CDH then wiping of the data don't happen for those courses. 

## Steps to Reproduce :
1. 
2.
3.

**Comment by pushyamig** [comment]
Test plan:
The `resource ` table is now modified to take auto-increment id and instead of resource id as a primary key that way after each insert into DB table has the unique key is not dependent on resource id. This will work well in cases when instructor uses same Resource with same id in 2 different course 

1.  For courses with the Leccapture tool, uses same resource in 2 different course sections`331347`, `347677`. These courses are a good way to test it cron runs successfully.

**Comment by jennlove-um** [comment]
The lecture capture recording shows up correctly in both courses.
