### ISSUE TITLE
Add .snap files to be treated as binary in gitattributes

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#928]
Thank you for contributing to this project!

## Describe the bug (Tell us what happens instead of the expected behavior) :
With Cypress tests, there are large files called "snapshots" with a .snap extensionthat are committed. I feel like these should be treated as binary files rather than files to be diff'd. I'd forgotten we had a .gitattributes already where we can add this to. These are nothing we'll ever be able to see in a UI or a diff that makes sense.

https://stackoverflow.com/questions/11162267/how-do-i-make-git-treat-a-file-as-binary

**Comment by pushyamig** [comment]
The problem that is described here when implemented will remove all the `.snap` files from the repo. The snapshots are created for [Jest](https://github.com/tl-its-umich-edu/my-learning-analytics/tree/master/assets/src/__tests__/components/__snapshots__) and newly with [Cypress](https://github.com/tl-its-umich-edu/my-learning-analytics/tree/master/cypress/integration/myla/__snapshots__). 

Is this how the problem should be fixed?
1. Removing the all the  `.snap` file
2. add the `.snap` as binaries to `.gitattributes`

**Comment by jonespm** [comment]
2 shouldn't remove them from the repo, it just won't make them appear as diff's when looking at them in git diff, or count them toward "lines of code"
