### ISSUE TITLE
Update the cypress snapshot 

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#933]
Recent changes to the Resource accessed view look like Cypress tests are failing as the snapshot is not matching the previous one. This needs an update to the snapshot

**Comment by jonespm** [comment]
Should be fixed with #928. 

This is going to be the problem with these tests if they're not run automatically. Seems like if we use snapshot testing they'll have to be frequently updated.

**Comment by pushyamig** [comment]
I agree, but if they see a failing test then they get alarmed. The test case is trying to match the snapshot from previous that's when you see the failure test. If you don't have a snapshot then the run is fine. So I am trying to update it. 
Should we close the issue without updating the snapshot? I can update the readme what to do in case if they see a failure due to not matching snapshot
