### ISSUE TITLE
Lost "View on Site" button with change to course.absolute_url

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#936]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 

The admin page used to have a "View on Site" button, which is automatically generated when a model has a `get_absolute_url` method.

## Describe the bug (Tell us what happens instead of the expected behavior) :

It looks like in PR #915 when we changed to using a property (i.e. `course.absolute_url`), we lost this button, meaning a link is no longer available from the edit page, only from the course list.

## Screenshots/Video (If possible, add media to help explain your problem) :

![Screen Shot 2020-05-26 at 4 34 30 PM](https://user-images.githubusercontent.com/35741256/82949653-f6441800-9f71-11ea-8683-4180a586dc06.png)

The course referenced above is fabricated.

## Additional context (Add any other context about the problem here) :

I think we can keep the property implementation and just add back a `get_absolute_url` method that uses the property. Something like this:

```
def get_absolute_url(self):
   return self.absolute_url
```

**Comment by jennlove-um** [comment]
Testing passes: The button displays and works as expected.
