### ISSUE TITLE
Move FE Jest testing instructions to README.md

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#939]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 

All details about front-end tests (or all tests, really) should be in the same place.

## Describe the bug (Tell us what happens instead of the expected behavior) :

After the Cypress details were added, the test documentation is now split between the `README.md` (the Cypress stuff) and `CONTRIBUTING.md` (the Jest stuff). These should be consolidated, probably in the `README.md`.

**Comment by pushyamig** [comment]
Looks Good
