### ISSUE TITLE
Are goal input changes stored too quickly?

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#941]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 

Entering goals in the Assignment Planning (Redesign) view should be as simple and seamless a process as possible, and the number of GraphQL calls should be minimized.

## Describe the bug (Tell us what happens instead of the expected behavior) :

Upon entering a goal in the view, each new character entered or deleted seems to trigger a new call storing the setting (separate calls for each step of the in-progress goal are visible in the Network tab of Developer Tools). While this doesn't seem to cause any problems technically speaking, it may be jarring to users who expect only one Snackbar notification after a new goal has been entered (not multiple, beginning after the first character change). Also, it might help performance a little to make only one GraphQL after a goal has been fully entered.

## Steps to Reproduce :
1. Enter a goal in any of the input fields in the Assignment Planning Redesign view.
2. Observe the Snackbar activation as soon as one character is entered.
3. Examine the Network tab of Developer Tools to see the separate calls for each character change.

## Additional context (Add any other context about the problem here) :

@jennlove-um and @justin0022, do either of you think this is a significant problem? I find it to be noticeable, but I can't speak for everyone. In terms of a solution, I think the ideal would be to have some kind of listener waiting for the user to stop entering data or to click away. I vaguely remember there being something like this already in the works or implemented, but I'm not seeing any behavior like this now.

**Comment by justin0022** [comment]
I agree with minimizing the number of Snackbar notifications. 

As for the GraphQL calls, I've added a debouncer here: https://github.com/tl-its-umich-edu/my-learning-analytics/blob/cb82b0471d1db583c6504186e95a32e99cab26de/assets/src/hooks/useSetUserSettingGQL.js#L23

The debouncer should only call GraphQL at most every 500 milliseconds. Definitely possible that this is not working as expected. 

It's hard to know exactly when the user is 'done' inputing a grade. I think the best solution is to use some naive timeout method in which we make a call at most every X-milliseconds.

**Comment by ssciolla** [comment]
Ah, thanks, @justin0022, it seems you've already thought about this quite a bit.

Upon closer inspection, it doesn't appear to the user that the are multiple Snackbar notifications (and may it only is one behind the scenes, I'd need to look at that part of the code to be sure). It is activated though pretty early, for the first character entered (with maybe some delay).

I agree that this does seem like a tricky problem in general, but it seems like we should try to do something to limit the GraphQL calls. I will try modifying the `debounce` `wait` parameter and do a little more research to see what we can do.

**Comment by justin0022** [comment]
Sounds good @ssciolla, glad you're looking into this!

**Comment by jennlove-um** [comment]
Testing passes for this release.  The grade is not saving too fast.
