### ISSUE TITLE
Remove the unwanted ESLint packages from the package.json

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#947]
Based on the comment from the PR #942 [here](https://github.com/tl-its-umich-edu/my-learning-analytics/pull/942#issuecomment-637611665) and [here](https://github.com/tl-its-umich-edu/my-learning-analytics/pull/942#issuecomment-637643950) cleaning of package.json is needed to remove the unwanted ESLint packages.

**Comment by ssciolla** [comment]
Everything built fine without the `eslint` packages specified in `package.json`. Note that `eslint` is a dependency of `standard`, and so will still be installed. There are a couple instances of `estlint-disable`, but `standard` uses [this syntax, too](https://standardjs.com/#how-do-i-hide-a-certain-warning). I'm moving to Done.
