### ISSUE TITLE
Update Python from 3.7 to 3.8 look at new images

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#950]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added

Back at one time we looked at Alpine but it [sounds like just using the slim](https://pythonspeed.com/articles/base-image-python-docker-images/) is fine.

We should update to 3.8 since it's been out for over 3 months now and probably use the 3.8-slim Docker image as a base.

**Comment by jonespm** [comment]
It also looks like 3.7.8 released in June-2020 will be the last non-security release of 3.7

https://www.python.org/dev/peps/pep-0537/

**Comment by pushyamig** [comment]
Thank you for keeping track of all the Python-related changes. I think we should also do this with Frontend as well

**Comment by jonespm** [comment]
Yeah, I agree. We're on node:12 but looks like node:13 and node:14 is available. I'm not sure what impact that would have. Keeping the dependencies regularly updated (at least every 6-12 months) is important to consider too.

**Comment by pushyamig** [comment]
Node versioning is very interesting. Usually, their odd number versioning is short term support, experimental. Even number versioning is the LTS. So we should consider the even version of the node

**Comment by pushyamig** [comment]
> I'm also thinking of going to Django 3 which would make a few things easier and be in-line with other apps too. It would also improve the performance if we bumped to Django 3 and Python 3.8 as it supports asyncio. (A consideration for the fall in the performance category)

I agree!

**Comment by jonespm** [comment]
This was the update and cleanup I did for another project. https://github.com/tl-its-umich-edu/course-inventory/commit/4a86594210046fce6796597985fe0448e8043547

**Comment by pushyamig** [comment]
I have this working locally. I was able to get the build working. I Just need to test application/cron load fine. I will have a PR today

**Comment by zqian** [comment]
Verified on MyLA test server.
