### ISSUE TITLE
Upgrade to Django 3 and update other pip packages supporting it

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#952]
New version of the Django helps improve performance for Myla that we are hoping to achieve for Fall 2020. This has support for some of the features like asyncio.

Also update the pip packages in support of Django 3 or latest package updates from PyPi that directly not dependency on django

This is mentioned in #950

**Comment by pushyamig** [comment]
The [stable](https://pypi.org/project/Django/#history) release version for Django is `3.0.8`, The next version 3.1 is [scheduled](https://www.djangoproject.com/weblog/2020/jul/20/django-31-release-candidate-1-released/) to for a release is Aug. I will stick with 3.0.8 for Fall, thoughts???

**Comment by pushyamig** [comment]
I have been locally testing with 3.0.8 since June

**Comment by pushyamig** [comment]
I see this issue when upgrading to [Pixan-eventlog](https://github.com/pinax/pinax-eventlog/issues/32) library. I reported the issue

**Comment by pushyamig** [comment]
I also see this issues when upgrading the new version of [promise 2.3](https://github.com/tl-its-umich-edu/my-learning-analytics/issues/994)

**Comment by jonespm** [comment]
This looks like it's being incorporated by #982

**Comment by ssciolla** [comment]
I will QA.

**Comment by ssciolla** [comment]
I confirmed that the package updates are reflected in the images created by `docker-compose build`, everything seems to be still functioning with the changes -- with no glaring issues in the logs during build or performing regular application tasks. Will move to Done.
