### ISSUE TITLE
goalGradeSetByUser stored in DB with inconsistent data types

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/my-learning-analytics#953]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 

The data stored as JSON in the database for `default_view_value` as part of the Assignment Planning Redesign via a GraphQL mutation should be stored consistently, with consistent data types. (In an ideal world with infinite time, this data would atomized into one or more tables so we could use SQL data types to enforce some of this.)

## Describe the bug (Tell us what happens instead of the expected behavior) :

While testing PR #940, I noticed that sometimes the value of the `goalGradeSetByUser` property was sometimes stored as a boolean (`true` or `false`) and other times stored as the goal text input. I believe this is supposed to always be a boolean, since there is an alternative `goalGrade` property in the data.

## Steps to Reproduce :
1. Visit the Assignment Planning Redesign view.
2. Add a goal manually via a text input field.
3. Add another goal by clicking the Lock checkbox next to an auto-generated goal.
4. Look at the `user_default_selection` table in the database.

## Additional context (Add any other context about the problem here) :

I think (but am not positive) the reason for behavior described above is the following function, where it appears `goalGrade` is assigned to `goalGradeSetByUser`.

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/f55ced5cf4d6ba16a07f19f058bc4840fd24a5af/assets/src/util/assignment.js#L23-L33=

**Comment by ssciolla** [comment]
Hi @justin0022, any chance you could take a look at this? I'm not exactly sure of what your intentions were with these properties. It might be a one-line fix.

**Comment by justin0022** [comment]
Hi Sam, yes I think this is a bug. I'll look into this, thanks for pointing it out

**Comment by pushyamig** [comment]
goalGradeSetByUser property is logged a boolean.
Test passes
