### ISSUE TITLE
Messaging when data isn't yet available

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#964]
## Describe your problem or feature you'd like added
Because we have a delay until the course is added and the next job runs we'd have to have some message saying "The data for this course isn't available yet, please check back in X hour or tomorrow".

## Describe the solution you'd like
Ideally, a solution where the data is immediately available when an instructor adds MyLA to a course would be preferred.  However, if the data is not immediately available, a message needs to display to indicate when it will become available.

## Describe any possible alternatives you've considered
This issue may be impacted by some of the ongoing discussions on the process of getting and storing course data.

**Comment by jennlove-um** [comment]
Related to Instructor admin page for setting up the course: Instructor page to configure MyLA courses when added as LTI #849

**Comment by zqian** [comment]
I suggest use the User table as an indication: if there is no course user information, suggest MyLA user wait for the next round of data load.

**Comment by jonespm** [comment]
Its possible that this is related (or could resolve #768) should see if that's the case when this is resolved.

**Comment by zqian** [comment]
@jonespm I think the current fix (course added before cron data insert) won't address #768 (course removed before cron data removed). But I will add #768 to the Fall release.

**Comment by pushyamig** [comment]
Currently, If the tool is launched via LTI the idea is to create an entry in course table with 3 piece of information `1. Canvas long id 2. canvas short id 3. course name`

Immediately when you try to redirect to Home page the React stuff loads and API call is made to with `/info`(getting the course info) and due to the enforced rules check it will throw a 403 and an error message as "You don't have access to the course". 

I fell the possible solution will be either modify the rules check and identify that the course just added and cron is not run yet and enable access and in the `view.py` when getting the `get_course_info` having a check like this will give decent error message

if course.term_id is None:
        return HttpResponse("{msg: Course is not active yet}")

This should work

**Comment by jennlove-um** [comment]
Should we add more information to the message to indicate that the course how long it takes for a the course to become active?  For example, "Course data is not yet available.  It can take up to 24 hours for course data to populate."

**Comment by jonespm** [comment]
@jennlove-um The system doesn't know when the next reload will be. Though "Please wait for the next system data load." doesn't really say much either. Your 24 hours is more accurate and maybe it likely won't be ready until at least tomorrow.

**Comment by jennlove-um** [comment]
Did we implement this different warning message for when the course is first added and the cron hasn't run yet? 
 
When I add MyLA to a course in Canvas test as an instructor, I don't get any message about the data not being ready yet or to check back in 24 hours.  Instead, when I go to each of the visualizations, and I get the standard messages about no data being there.  The ones that show up if there is no data for the filters selected.  

It would be really helpful to have a different message when the course is first added and the cron hasn't run yet for the course so that instructors know the data is not expected to be there yet and will be coming soon.   Or am I missing something in the testing?

**Comment by pushyamig** [comment]
SO with LTI we create an entry into `course` table and add a record of his enrollment to the `user` table. This step eliminates to display of message and directly show then views page. When they click in each view that's when it shows No data is available if respective tables ( assignment, resources and grades) doesn't have data.

**Comment by jennlove-um** [comment]
From a functional perspective, it would be really helpful to have a specific message for when there is no data because the cron hasn't run.  Instructors won't know why there is no data when they first add MyLA unless we tell them that it will take up to 24 hours to add their course data to MyLA.  So without that information, from their perspective, MyLA immediately looks broken and like it's not working.

**Comment by pushyamig** [comment]
ok, I think in that case when LTI launch happens the course table is fed with course_id and course name and not Term id, the term id is replenished by cron. So when that column is empty assumption is data is not loaded via cron. That would be simplest with out going too deep into assignment/resources table check

**Comment by pushyamig** [comment]
@jennlove-um I have a fix for it [here](https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1036/files)

**Comment by jennlove-um** [comment]
Thanks, Pushyami.  Where does the warning message display and what does it say?

**Comment by jennlove-um** [comment]
The image correctly displays before the cron is run.  After the cron is run and data is available, the MyLA views tiles correctly display.  Testing passes for both published and unpublished courses.
