### ISSUE TITLE
In-tool links for LTI integration

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#970]
## Describe your problem or feature you'd like added
Currently when we manually add a course to MyLA, the in-tool links are embedded in Assignment, Grades, and Files pages.  When we move to the LTI, we need to determine how that will work.

## Describe the solution you'd like
In-tool links are placed on related pages when MyLA is added to the course based on which visualizations are used.

**Comment by jennlove-um** [comment]
#355 could also be related to this, but not required

**Comment by jennlove-um** [comment]
Notes from discussion; 
More investigation is needed for the in-tool links for the javascript.
It would have to see if the tool is placed, simulate clicking on the tool, and passing the parameters.
Unizin developers(IU dev might have experience) group may be able to provide some insights as to whether any of them have done this.  Maybe Indiana?

Canvas has 23 different placement, might have one close to our need
Current LTI Placements - https://github.com/instructure/canvas-lms/blob/0b742ad0b819b70125f54a3b492539e91d5d862d/app/models/lti/resource_placement.rb

**Comment by pushyamig** [comment]
The In-tool link only be available to the courses that has MyLA enabled in the left navigation. 
Test cases to test when Myla enabled for certain course and vice versa

**Comment by jennlove-um** [comment]
In tool links are working in Firefox and Chrome
