### ISSUE TITLE
Remove bootstrap references from code

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#986]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Describe the bug (Tell us what happens instead of the expected behavior) :

We still have one reference to bootstrap (in the rangeslider) but I don't think we're using it at all anymore and it semi-conflicts with the use of Materia-UI so we should just clean it all up.

**Comment by jennlove-um** [comment]
It looks like this was resolved with #1115.  I'm closing this issue.
