### ISSUE TITLE
Database seems to be latin1, need to convert to utf8mb4

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#989]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 
When looking at the database all of the tables and columns are latin1.

We should generate a conversion, add the database option for UTF8 and have a migration for this.

This could be run similar to this script.
https://stackoverflow.com/a/50935608/3708872

I'll work on this next week.

**Comment by jonespm** [comment]
All of the Openshift (dev/test/prod) were latin1. I manually converted dev but this should be able to run again on dev with no issue.

To be able to test this just try to insert an emoji 🐶 into something like a course title as an admin. It should save and display.

To test locally (if desired) you'll probably have to.
- Modify docker-compose.yml and change the line in the mysql from
`    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
`to
`    command: ['--character-set-server=latin1', '--collation-server=latin1_swedish_ci']`

Then `rm -rf .data` to remove the existing database and start up the instance before this patch. If you try to insert an emoji it should give you an error. After running this migration it should work as expected.

**Comment by lsloan** [comment]
Why Swedish‽

**Comment by jonespm** [comment]
It's the MySQL default collation. Not 100% sure why that is.

https://stackoverflow.com/questions/6769901/why-is-mysqls-default-collation-latin1-swedish-ci

**Comment by zqian** [comment]
Verified the conversion result on MyLA test db, that all relevant character_set params and collation params are all set to "utf8mb4":

show variables like "%character%";

Variable_name			Value
character_set_client	utf8mb4
character_set_connection	utf8mb4
character_set_database	utf8mb4
character_set_filesystem	binary
character_set_results	
character_set_server	utf8mb4
character_set_system	utf8
character_sets_dir	/rdsdbbin/mysql-5.7.26.R1/share/charsets/

and 

show variables like "%collation%"

Variable_name			Value
collation_connection	utf8mb4_general_ci
collation_database	utf8mb4_unicode_ci
collation_server	utf8mb4_general_ci
